package com.xoa.model.knowledge;

import com.alibaba.fastjson.annotation.JSONField;
import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;

public class KnowledgeDocfile {
    private Integer code;//临时封装参数
    private String isSysCode;

    public String getIsSysCode() {
        return isSysCode;
    }

    public void setIsSysCode(String isSysCode) {
        this.isSysCode = isSysCode;
    }

    private String serchTime;

    public String getSerchTime() {
        return serchTime;
    }

    public void setSerchTime(String serchTime) {
        this.serchTime = serchTime;
    }

    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JSONField(format = "yyyy-MM-dd HH:mm:ss")
    private Date beginTime;

    public Date getBeginTime() {
        return beginTime;
    }

    public void setBeginTime(Date beginTime) {
        this.beginTime = beginTime;
    }
    //查询用
    private String[] columnIds;

    public String[] getColumnIds() {
        return columnIds;
    }

    public void setColumnIds(String[] columnIds) {
        this.columnIds = columnIds;
    }

    //搜索用的查询id
    private String[] createUserIds;

    public String[] getCreateUserIds() {
        return createUserIds;
    }

    public void setCreateUserIds(String[] createUserIds) {
        this.createUserIds = createUserIds;
    }

    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JSONField(format = "yyyy-MM-dd HH:mm:ss")
    private Date endTime;

    public Date getEndTime() {
        return endTime;
    }

    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    private String attachmentId;
    private String attachmentName;

    public String getAttachmentId() {
        return attachmentId;
    }

    public void setAttachmentId(String attachmentId) {
        this.attachmentId = attachmentId;
    }

    public String getAttachmentName() {
        return attachmentName;
    }

    public void setAttachmentName(String attachmentName) {
        this.attachmentName = attachmentName;
    }

    private String browseStatus;

    private String downStatus;

    public String getCreateTimeN() {
        return createTimeN;
    }

    public void setCreateTimeN(String createTimeN) {
        this.createTimeN = createTimeN;
    }

    private String createTimeN;

    public String getBrowseStatus() {
        return browseStatus;
    }

    public void setBrowseStatus(String browseStatus) {
        this.browseStatus = browseStatus;
    }

    public String getDownStatus() {
        return downStatus;
    }

    public void setDownStatus(String downStatus) {
        this.downStatus = downStatus;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knowledge_docfile.DOCFILE_ID
     *
     * @mbggenerated
     */
    private Integer docfileId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knowledge_docfile.DOCFILE_NO
     *
     * @mbggenerated
     */
    private String docfileNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knowledge_docfile.DOCFILE_NAME
     *
     * @mbggenerated
     */
    private String docfileName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knowledge_docfile.KEY_WORD
     *
     * @mbggenerated
     */
    private String keyWord;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knowledge_docfile.COLUMN_ID
     *
     * @mbggenerated
     */
    private String columnId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knowledge_docfile.DOCFILE_CLASS
     *
     * @mbggenerated
     */
    private String docfileClass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knowledge_docfile.CREATE_USER_ID
     *
     * @mbggenerated
     */
    private String createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knowledge_docfile.CREATE_TIME
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JSONField(format = "yyyy-MM-dd HH:mm:ss")
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knowledge_docfile.DOWNLOAD_ADDRESS
     *
     * @mbggenerated
     */
    private String downloadAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knowledge_docfile.DOWNLOAD_PASSWORD
     *
     * @mbggenerated
     */
    private String downloadPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knowledge_docfile.DOCFILE_DESC
     *
     * @mbggenerated
     */
    private String docfileDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knowledge_docfile.DOCFILE_ID
     *
     * @return the value of knowledge_docfile.DOCFILE_ID
     *
     * @mbggenerated
     */
    public Integer getDocfileId() {
        return docfileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knowledge_docfile.DOCFILE_ID
     *
     * @param docfileId the value for knowledge_docfile.DOCFILE_ID
     *
     * @mbggenerated
     */
    public void setDocfileId(Integer docfileId) {
        this.docfileId = docfileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knowledge_docfile.DOCFILE_NO
     *
     * @return the value of knowledge_docfile.DOCFILE_NO
     *
     * @mbggenerated
     */
    public String getDocfileNo() {
        return docfileNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knowledge_docfile.DOCFILE_NO
     *
     * @param docfileNo the value for knowledge_docfile.DOCFILE_NO
     *
     * @mbggenerated
     */
    public void setDocfileNo(String docfileNo) {
        this.docfileNo = docfileNo == null ? null : docfileNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knowledge_docfile.DOCFILE_NAME
     *
     * @return the value of knowledge_docfile.DOCFILE_NAME
     *
     * @mbggenerated
     */
    public String getDocfileName() {
        return docfileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knowledge_docfile.DOCFILE_NAME
     *
     * @param docfileName the value for knowledge_docfile.DOCFILE_NAME
     *
     * @mbggenerated
     */
    public void setDocfileName(String docfileName) {
        this.docfileName = docfileName == null ? null : docfileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knowledge_docfile.KEY_WORD
     *
     * @return the value of knowledge_docfile.KEY_WORD
     *
     * @mbggenerated
     */
    public String getKeyWord() {
        return keyWord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knowledge_docfile.KEY_WORD
     *
     * @param keyWord the value for knowledge_docfile.KEY_WORD
     *
     * @mbggenerated
     */
    public void setKeyWord(String keyWord) {
        this.keyWord = keyWord == null ? null : keyWord.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knowledge_docfile.COLUMN_ID
     *
     * @return the value of knowledge_docfile.COLUMN_ID
     *
     * @mbggenerated
     */
    public String getColumnId() {
        return columnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knowledge_docfile.COLUMN_ID
     *
     * @param columnId the value for knowledge_docfile.COLUMN_ID
     *
     * @mbggenerated
     */
    public void setColumnId(String columnId) {
        this.columnId = columnId == null ? null : columnId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knowledge_docfile.DOCFILE_CLASS
     *
     * @return the value of knowledge_docfile.DOCFILE_CLASS
     *
     * @mbggenerated
     */
    public String getDocfileClass() {
        return docfileClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knowledge_docfile.DOCFILE_CLASS
     *
     * @param docfileClass the value for knowledge_docfile.DOCFILE_CLASS
     *
     * @mbggenerated
     */
    public void setDocfileClass(String docfileClass) {
        this.docfileClass = docfileClass == null ? null : docfileClass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knowledge_docfile.CREATE_USER_ID
     *
     * @return the value of knowledge_docfile.CREATE_USER_ID
     *
     * @mbggenerated
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knowledge_docfile.CREATE_USER_ID
     *
     * @param createUserId the value for knowledge_docfile.CREATE_USER_ID
     *
     * @mbggenerated
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId == null ? null : createUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knowledge_docfile.CREATE_TIME
     *
     * @return the value of knowledge_docfile.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knowledge_docfile.CREATE_TIME
     *
     * @param createTime the value for knowledge_docfile.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knowledge_docfile.DOWNLOAD_ADDRESS
     *
     * @return the value of knowledge_docfile.DOWNLOAD_ADDRESS
     *
     * @mbggenerated
     */
    public String getDownloadAddress() {
        return downloadAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knowledge_docfile.DOWNLOAD_ADDRESS
     *
     * @param downloadAddress the value for knowledge_docfile.DOWNLOAD_ADDRESS
     *
     * @mbggenerated
     */
    public void setDownloadAddress(String downloadAddress) {
        this.downloadAddress = downloadAddress == null ? null : downloadAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knowledge_docfile.DOWNLOAD_PASSWORD
     *
     * @return the value of knowledge_docfile.DOWNLOAD_PASSWORD
     *
     * @mbggenerated
     */
    public String getDownloadPassword() {
        return downloadPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knowledge_docfile.DOWNLOAD_PASSWORD
     *
     * @param downloadPassword the value for knowledge_docfile.DOWNLOAD_PASSWORD
     *
     * @mbggenerated
     */
    public void setDownloadPassword(String downloadPassword) {
        this.downloadPassword = downloadPassword == null ? null : downloadPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knowledge_docfile.DOCFILE_DESC
     *
     * @return the value of knowledge_docfile.DOCFILE_DESC
     *
     * @mbggenerated
     */
    public String getDocfileDesc() {
        return docfileDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knowledge_docfile.DOCFILE_DESC
     *
     * @param docfileDesc the value for knowledge_docfile.DOCFILE_DESC
     *
     * @mbggenerated
     */
    public void setDocfileDesc(String docfileDesc) {
        this.docfileDesc = docfileDesc == null ? null : docfileDesc.trim();
    }

    private String columnName;

    public String getColumnName() { return columnName; }

    public void setColumnName(String columnName) { this.columnName = columnName; }

    public Integer getCode() {
        return code;
    }

    public void setCode(Integer code) {
        this.code = code;
    }
}