package com.xoa.model.knowledge;

import java.util.List;

public class KnowledgeColumn {
    private boolean checked = false; //临时封装参数，下拉树回显


    private String columnTypeName; //临时封装字段 栏目类型名称
    private String parentColumnIdName; //临时封装字段 父级栏目名称

    public String getColumnTypeName() {
        return columnTypeName;
    }

    public void setColumnTypeName(String columnTypeName) {
        this.columnTypeName = columnTypeName;
    }

    public String getParentColumnIdName() {
        return parentColumnIdName;
    }

    public void setParentColumnIdName(String parentColumnIdName) {
        this.parentColumnIdName = parentColumnIdName;
    }

    private boolean isSysCode = false; //标识是否是sysCode的数据

    public boolean isSysCode() {
        return isSysCode;
    }

    public void setSysCode(boolean sysCode) {
        isSysCode = sysCode;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knowledge_column.COLUMN_ID
     *
     * @mbggenerated
     */
    private Integer columnId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knowledge_column.ORDER_NO
     *
     * @mbggenerated
     */
    private Integer orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knowledge_column.COLUMN_TYPE
     *
     * @mbggenerated
     */
    private String columnType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knowledge_column.COLUMN_CODE
     *
     * @mbggenerated
     */
    private String columnCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knowledge_column.COLUMN_NAME
     *
     * @mbggenerated
     */
    private String columnName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knowledge_column.PARENT_COLUMN_ID
     *
     * @mbggenerated
     */
    private Integer parentColumnId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knowledge_column.COLUMN_DESC
     *
     * @mbggenerated
     */
    private String columnDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knowledge_column.COLUMN_ID
     *
     * @return the value of knowledge_column.COLUMN_ID
     *
     * @mbggenerated
     */
    public Integer getColumnId() {
        return columnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knowledge_column.COLUMN_ID
     *
     * @param columnId the value for knowledge_column.COLUMN_ID
     *
     * @mbggenerated
     */
    public void setColumnId(Integer columnId) {
        this.columnId = columnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knowledge_column.ORDER_NO
     *
     * @return the value of knowledge_column.ORDER_NO
     *
     * @mbggenerated
     */
    public Integer getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knowledge_column.ORDER_NO
     *
     * @param orderNo the value for knowledge_column.ORDER_NO
     *
     * @mbggenerated
     */
    public void setOrderNo(Integer orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knowledge_column.COLUMN_TYPE
     *
     * @return the value of knowledge_column.COLUMN_TYPE
     *
     * @mbggenerated
     */
    public String getColumnType() {
        return columnType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knowledge_column.COLUMN_TYPE
     *
     * @param columnType the value for knowledge_column.COLUMN_TYPE
     *
     * @mbggenerated
     */
    public void setColumnType(String columnType) {
        this.columnType = columnType == null ? null : columnType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knowledge_column.COLUMN_CODE
     *
     * @return the value of knowledge_column.COLUMN_CODE
     *
     * @mbggenerated
     */
    public String getColumnCode() {
        return columnCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knowledge_column.COLUMN_CODE
     *
     * @param columnCode the value for knowledge_column.COLUMN_CODE
     *
     * @mbggenerated
     */
    public void setColumnCode(String columnCode) {
        this.columnCode = columnCode == null ? null : columnCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knowledge_column.COLUMN_NAME
     *
     * @return the value of knowledge_column.COLUMN_NAME
     *
     * @mbggenerated
     */
    public String getColumnName() {
        return columnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knowledge_column.COLUMN_NAME
     *
     * @param columnName the value for knowledge_column.COLUMN_NAME
     *
     * @mbggenerated
     */
    public void setColumnName(String columnName) {
        this.columnName = columnName == null ? null : columnName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knowledge_column.PARENT_COLUMN_ID
     *
     * @return the value of knowledge_column.PARENT_COLUMN_ID
     *
     * @mbggenerated
     */
    public Integer getParentColumnId() {
        return parentColumnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knowledge_column.PARENT_COLUMN_ID
     *
     * @param parentColumnId the value for knowledge_column.PARENT_COLUMN_ID
     *
     * @mbggenerated
     */
    public void setParentColumnId(Integer parentColumnId) {
        this.parentColumnId = parentColumnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knowledge_column.COLUMN_DESC
     *
     * @return the value of knowledge_column.COLUMN_DESC
     *
     * @mbggenerated
     */
    public String getColumnDesc() {
        return columnDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knowledge_column.COLUMN_DESC
     *
     * @param columnDesc the value for knowledge_column.COLUMN_DESC
     *
     * @mbggenerated
     */
    public void setColumnDesc(String columnDesc) {
        this.columnDesc = columnDesc == null ? null : columnDesc.trim();
    }

    private Integer id;

    private String name;

    private String label;

    private Boolean isLeaf = true;

    private List children;

    public Integer getId() { return id; }

    public void setId(Integer id) { this.id = id; }

    public String getName() { return name; }

    public void setName(String name) { this.name = name; }

    public String getLabel() { return label; }

    public void setLabel(String label) { this.label = label; }

    public Boolean getIsLeaf(){
        return isLeaf;
    }

    public void setIsLeaf(Boolean isLeaf){
        this.isLeaf = isLeaf;
    }

    public List getChildren() { return children; }

    public void setChildren(List children) { this.children = children; }

    public boolean isChecked() {
        return checked;
    }

    public void setChecked(boolean checked) {
        this.checked = checked;
    }
}