package com.xoa.model.knowledge;

import com.alibaba.fastjson.annotation.JSONField;
import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;

public class KnowledgeCustomer {
    private String docfileClass;
    private String appCode;
    private String engineCode;
    private String engineSecret;
    private String companyObjectId;

    public String getAppCode() {
        return appCode;
    }

    public void setAppCode(String appCode) {
        this.appCode = appCode;
    }

    public String getEngineCode() {
        return engineCode;
    }

    public void setEngineCode(String engineCode) {
        this.engineCode = engineCode;
    }

    public String getEngineSecret() {
        return engineSecret;
    }

    public void setEngineSecret(String engineSecret) {
        this.engineSecret = engineSecret;
    }

    public String getCompanyObjectId() {
        return companyObjectId;
    }

    public void setCompanyObjectId(String companyObjectId) {
        this.companyObjectId = companyObjectId;
    }

    //搜索用的查询id
    private String[] createUserIds;

    public String[] getCreateUserIds() {
        return createUserIds;
    }

    public void setCreateUserIds(String[] createUserIds) {
        this.createUserIds = createUserIds;
    }


    //查询用
    private String[] columnIds;

    public String[] getColumnIds() {
        return columnIds;
    }

    public void setColumnIds(String[] columnIds) {
        this.columnIds = columnIds;
    }

    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JSONField(format = "yyyy-MM-dd HH:mm:ss")
    private Date bTime; //临时封装参数，开始时间

    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JSONField(format = "yyyy-MM-dd HH:mm:ss")
    private Date eTime; //临时封装参数，结束时间

    private String userPrivName;
    private String byName; //临时封装字段 用户信息
    private String userName;//临时封装字段 用户信息
    private Integer userPriv;//临时封装字段 用户信息
    private Integer deptId;//临时封装字段 用户信息
    private String password;//临时封装字段 用户信息
    private String userId; //客户绑定oa用户，客户就是oa用户

    private String logingAccount;

    private String logingPassword;

    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JSONField(format = "yyyy-MM-dd HH:mm:ss")
    private Date browseBDate;

    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JSONField(format = "yyyy-MM-dd HH:mm:ss")
    private Date browseEDate;

    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JSONField(format = "yyyy-MM-dd HH:mm:ss")
    private Date downloadBDate;

    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JSONField(format = "yyyy-MM-dd HH:mm:ss")
    private Date downloadEDate;

    private String columnName; // 临时封装字段栏目名称

    public String getColumnName() {
        return columnName;
    }

    public void setColumnName(String columnName) {
        this.columnName = columnName;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knowledge_customer.CUSTOMER_ID
     *
     * @mbggenerated
     */
    private Integer customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knowledge_customer.COMPANY_NAME
     *
     * @mbggenerated
     */
    private String companyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knowledge_customer.COMPANY_CODE
     *
     * @mbggenerated
     */
    private String companyCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knowledge_customer.CONTACT_USER
     *
     * @mbggenerated
     */
    private String contactUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knowledge_customer.CONTACT_PHONE
     *
     * @mbggenerated
     */
    private String contactPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knowledge_customer.COMPANY_NATRUE
     *
     * @mbggenerated
     */
    private String companyNatrue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knowledge_customer.PRIV_TYPE
     *
     * @mbggenerated
     */
    private String privType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knowledge_customer.COLUMN_ID
     *
     * @mbggenerated
     */
    private String columnId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knowledge_customer.MEMO
     *
     * @mbggenerated
     */
    private String memo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knowledge_customer.CUSTOMER_ID
     *
     * @return the value of knowledge_customer.CUSTOMER_ID
     *
     * @mbggenerated
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knowledge_customer.CUSTOMER_ID
     *
     * @param customerId the value for knowledge_customer.CUSTOMER_ID
     *
     * @mbggenerated
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knowledge_customer.COMPANY_NAME
     *
     * @return the value of knowledge_customer.COMPANY_NAME
     *
     * @mbggenerated
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knowledge_customer.COMPANY_NAME
     *
     * @param companyName the value for knowledge_customer.COMPANY_NAME
     *
     * @mbggenerated
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knowledge_customer.COMPANY_CODE
     *
     * @return the value of knowledge_customer.COMPANY_CODE
     *
     * @mbggenerated
     */
    public String getCompanyCode() {
        return companyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knowledge_customer.COMPANY_CODE
     *
     * @param companyCode the value for knowledge_customer.COMPANY_CODE
     *
     * @mbggenerated
     */
    public void setCompanyCode(String companyCode) {
        this.companyCode = companyCode == null ? null : companyCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knowledge_customer.CONTACT_USER
     *
     * @return the value of knowledge_customer.CONTACT_USER
     *
     * @mbggenerated
     */
    public String getContactUser() {
        return contactUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knowledge_customer.CONTACT_USER
     *
     * @param contactUser the value for knowledge_customer.CONTACT_USER
     *
     * @mbggenerated
     */
    public void setContactUser(String contactUser) {
        this.contactUser = contactUser == null ? null : contactUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knowledge_customer.CONTACT_PHONE
     *
     * @return the value of knowledge_customer.CONTACT_PHONE
     *
     * @mbggenerated
     */
    public String getContactPhone() {
        return contactPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knowledge_customer.CONTACT_PHONE
     *
     * @param contactPhone the value for knowledge_customer.CONTACT_PHONE
     *
     * @mbggenerated
     */
    public void setContactPhone(String contactPhone) {
        this.contactPhone = contactPhone == null ? null : contactPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knowledge_customer.COMPANY_NATRUE
     *
     * @return the value of knowledge_customer.COMPANY_NATRUE
     *
     * @mbggenerated
     */
    public String getCompanyNatrue() {
        return companyNatrue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knowledge_customer.COMPANY_NATRUE
     *
     * @param companyNatrue the value for knowledge_customer.COMPANY_NATRUE
     *
     * @mbggenerated
     */
    public void setCompanyNatrue(String companyNatrue) {
        this.companyNatrue = companyNatrue == null ? null : companyNatrue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knowledge_customer.PRIV_TYPE
     *
     * @return the value of knowledge_customer.PRIV_TYPE
     *
     * @mbggenerated
     */
    public String getPrivType() {
        return privType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knowledge_customer.PRIV_TYPE
     *
     * @param privType the value for knowledge_customer.PRIV_TYPE
     *
     * @mbggenerated
     */
    public void setPrivType(String privType) {
        this.privType = privType == null ? null : privType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knowledge_customer.COLUMN_ID
     *
     * @return the value of knowledge_customer.COLUMN_ID
     *
     * @mbggenerated
     */
    public String getColumnId() {
        return columnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knowledge_customer.COLUMN_ID
     *
     * @param columnId the value for knowledge_customer.COLUMN_ID
     *
     * @mbggenerated
     */
    public void setColumnId(String columnId) {
        this.columnId = columnId == null ? null : columnId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knowledge_customer.MEMO
     *
     * @return the value of knowledge_customer.MEMO
     *
     * @mbggenerated
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knowledge_customer.MEMO
     *
     * @param memo the value for knowledge_customer.MEMO
     *
     * @mbggenerated
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    public String getLogingAccount() {
        return logingAccount;
    }

    public void setLogingAccount(String logingAccount) {
        this.logingAccount = logingAccount;
    }

    public String getLogingPassword() {
        return logingPassword;
    }

    public void setLogingPassword(String logingPassword) {
        this.logingPassword = logingPassword;
    }

    public Date getBrowseBDate() {
        return browseBDate;
    }

    public void setBrowseBDate(Date browseBDate) {
        this.browseBDate = browseBDate;
    }

    public Date getBrowseEDate() {
        return browseEDate;
    }

    public void setBrowseEDate(Date browseEDate) {
        this.browseEDate = browseEDate;
    }

    public Date getDownloadBDate() {
        return downloadBDate;
    }

    public void setDownloadBDate(Date downloadBDate) {
        this.downloadBDate = downloadBDate;
    }

    public Date getDownloadEDate() {
        return downloadEDate;
    }

    public void setDownloadEDate(Date downloadEDate) {
        this.downloadEDate = downloadEDate;
    }


    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getByName() {
        return byName;
    }

    public void setByName(String byName) {
        this.byName = byName;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public Integer getUserPriv() {
        return userPriv;
    }

    public void setUserPriv(Integer userPriv) {
        this.userPriv = userPriv;
    }

    public Integer getDeptId() {
        return deptId;
    }

    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getUserPrivName() {
        return userPrivName;
    }

    public void setUserPrivName(String userPrivName) {
        this.userPrivName = userPrivName;
    }
    public Date getbTime() {
        return bTime;
    }

    public void setbTime(Date bTime) {
        this.bTime = bTime;
    }

    public Date geteTime() {
        return eTime;
    }

    public void seteTime(Date eTime) {
        this.eTime = eTime;
    }

    public String getDocfileClass() {
        return docfileClass;
    }

    public void setDocfileClass(String docfileClass) {
        this.docfileClass = docfileClass;
    }
}