package com.xoa.dao.kg;

import com.xoa.kg.model.KgSignature;
import com.xoa.kg.model.KgSignatureExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface KgSignatureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kg_signature
     *
     * @mbggenerated
     */
    int countByExample(KgSignatureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kg_signature
     *
     * @mbggenerated
     */
    int deleteByExample(KgSignatureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kg_signature
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer signatureId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kg_signature
     *
     * @mbggenerated
     */
    int insert(KgSignature record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kg_signature
     *
     * @mbggenerated
     */
    int insertSelective(KgSignature record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kg_signature
     *
     * @mbggenerated
     */
    List<KgSignature> selectByExample(KgSignatureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kg_signature
     *
     * @mbggenerated
     */
    KgSignature selectByPrimaryKey(Integer signatureId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kg_signature
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") KgSignature record, @Param("example") KgSignatureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kg_signature
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") KgSignature record, @Param("example") KgSignatureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kg_signature
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(KgSignature record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kg_signature
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(KgSignature record);

    List<KgSignature> selectUserSign(@Param("userId") Integer userId);

    List<KgSignature> getKgSignatureList();
}