package com.xoa.model.oaSource;

import java.util.List;

public class OaSourceWithBLOBs extends OaSource {

    //临时封装，用于资源申请查询列表
    //周期时间
    private List weeks;

    //周期（时间加星期）
    private List WeekLits;

    //时间段
    private List SegmentList;

    public List getWeeks() {
        return weeks;
    }

    public void setWeeks(List weeks) {
        this.weeks = weeks;
    }

    public List getWeekLits() {
        return WeekLits;
    }

    public void setWeekLits(List weekLits) {
        WeekLits = weekLits;
    }

    public List getSegmentList() {
        return SegmentList;
    }

    public void setSegmentList(List segmentList) {
        SegmentList = segmentList;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_source.TIME_TITLE
     *
     * @mbggenerated
     */
    private String timeTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_source.MANAGE_USER
     *
     * @mbggenerated
     */
    private String manageUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_source.VISIT_USER
     *
     * @mbggenerated
     */
    private String visitUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_source.VISIT_PRIV
     *
     * @mbggenerated
     */
    private String visitPriv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_source.REMARK
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_source.TIME_TITLE
     *
     * @return the value of oa_source.TIME_TITLE
     *
     * @mbggenerated
     */
    public String getTimeTitle() {
        return timeTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_source.TIME_TITLE
     *
     * @param timeTitle the value for oa_source.TIME_TITLE
     *
     * @mbggenerated
     */
    public void setTimeTitle(String timeTitle) {
        this.timeTitle = timeTitle == null ? null : timeTitle.trim();
    }


    public String getManageUser() {
        return manageUser;
    }

    public void setManageUser(String manageUser) {
        this.manageUser = manageUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_source.VISIT_USER
     *
     * @return the value of oa_source.VISIT_USER
     *
     * @mbggenerated
     */
    public String getVisitUser() {
        return visitUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_source.VISIT_USER
     *
     * @param visitUser the value for oa_source.VISIT_USER
     *
     * @mbggenerated
     */
    public void setVisitUser(String visitUser) {
        this.visitUser = visitUser == null ? null : visitUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_source.VISIT_PRIV
     *
     * @return the value of oa_source.VISIT_PRIV
     *
     * @mbggenerated
     */
    public String getVisitPriv() {
        return visitPriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_source.VISIT_PRIV
     *
     * @param visitPriv the value for oa_source.VISIT_PRIV
     *
     * @mbggenerated
     */
    public void setVisitPriv(String visitPriv) {
        this.visitPriv = visitPriv == null ? null : visitPriv.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_source.REMARK
     *
     * @return the value of oa_source.REMARK
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_source.REMARK
     *
     * @param remark the value for oa_source.REMARK
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}