package com.xoa.model.equipment;

public class EquipmentCapys {

    private  String unitNames;
    public String getUnitNames(){ return unitNames; }
    public void setUnitName(String unitNames){this.unitNames=unitNames;}
    private String unitIds;

    public String getUnitIds() {
        return unitIds;
    }

    public void setUnitIds(String unitIds) {
        this.unitIds = unitIds;
    }

    private String typeCode;//注入设备能力类型

    public String getTypeCode() {
        return typeCode;
    }

    public void setTypeCode(String typeCode) {
        this.typeCode = typeCode;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equip_capys.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equip_capys.CAPY_ID
     *
     * @mbggenerated
     */
    private Integer capyId;

    private String capyName;

    public String getCapyName(){ return capyName;}
    public void  setCapyName(String capyName){this.capyName=capyName;}

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equip_capys.EQUIP_ID
     *
     * @mbggenerated
     */
    private Integer equipId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equip_capys.CAPY_INITIAL_VALUE
     *
     * @mbggenerated
     */
    private String capyInitialValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equip_capys.CALIBRATION_VALUE
     *
     * @mbggenerated
     */
    private String calibrationValue;

    private String protocolField;

    public String getProtocolField() {
        return protocolField;
    }

    public void setProtocolField(String protocolField) {
        this.protocolField = protocolField;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equip_capys.ID
     *
     * @return the value of lims_equip_capys.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equip_capys.ID
     *
     * @param id the value for lims_equip_capys.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equip_capys.CAPY_ID
     *
     * @return the value of lims_equip_capys.CAPY_ID
     *
     * @mbggenerated
     */
    public Integer getCapyId() {
        return capyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equip_capys.CAPY_ID
     *
     * @param capyId the value for lims_equip_capys.CAPY_ID
     *
     * @mbggenerated
     */
    public void setCapyId(Integer capyId) {
        this.capyId = capyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equip_capys.EQUIP_ID
     *
     * @return the value of lims_equip_capys.EQUIP_ID
     *
     * @mbggenerated
     */
    public Integer getEquipId() {
        return equipId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equip_capys.EQUIP_ID
     *
     * @param equipId the value for lims_equip_capys.EQUIP_ID
     *
     * @mbggenerated
     */
    public void setEquipId(Integer equipId) {
        this.equipId = equipId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equip_capys.CAPY_INITIAL_VALUE
     *
     * @return the value of lims_equip_capys.CAPY_INITIAL_VALUE
     *
     * @mbggenerated
     */
    public String getCapyInitialValue() {
        return capyInitialValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equip_capys.CAPY_INITIAL_VALUE
     *
     * @param capyInitialValue the value for lims_equip_capys.CAPY_INITIAL_VALUE
     *
     * @mbggenerated
     */
    public void setCapyInitialValue(String capyInitialValue) {
        this.capyInitialValue = capyInitialValue == null ? null : capyInitialValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equip_capys.CALIBRATION_VALUE
     *
     * @return the value of lims_equip_capys.CALIBRATION_VALUE
     *
     * @mbggenerated
     */
    public String getCalibrationValue() {
        return calibrationValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equip_capys.CALIBRATION_VALUE
     *
     * @param calibrationValue the value for lims_equip_capys.CALIBRATION_VALUE
     *
     * @mbggenerated
     */
    public void setCalibrationValue(String calibrationValue) {
        this.calibrationValue = calibrationValue == null ? null : calibrationValue.trim();
    }
}