package com.xoa.model.equipment;

import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;

public class Equipment {

    private  Integer equipRecomm;

    private String testPoints;//测点类型

    private String pointName;//测点名称

    public String getTestPoints(){return testPoints;}

    public void setTestPoints(String testPoints) { this.testPoints = testPoints; }

    public String getPointName() { return pointName; }

    public void setPointName(String pointName) { this.pointName = pointName; }

    public Integer getEquipRecomm() {
        return equipRecomm;
    }

    public void setEquipRecomm(Integer equipRecomm) {
        this.equipRecomm = equipRecomm;
    }

    private String equipStatuasName;

    public String getEquipStatuasName() {
        return equipStatuasName;
    }

    public void setEquipStatuasName(String equipStatuasName) {
        this.equipStatuasName = equipStatuasName;
    }

    private  Integer result;

    public Integer getResult(){return result;}

    public void setResult(Integer result){this.result=result;}

    private  String equipTypeCode;

    public String getEquipTypeCode(){return equipTypeCode;}

    public void setEquipTypeCode(String equipTypeCode){this.equipTypeCode=equipTypeCode;}

    private String parentTypeName;
    public String getParentTypeName(){return parentTypeName;
    }
    public void setParentTypeName(String parentTypeName){this.parentTypeName=parentTypeName;}
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equipment.EQUIP_ID
     *
     * @mbggenerated
     */
    private Integer equipId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equipment.EQUIP_NO
     *
     * @mbggenerated
     */
    private String equipNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equipment.EQUIP_NAME
     *
     * @mbggenerated
     */
    private String equipName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equipment.EQUIP_TYPE_ID
     *
     * @mbggenerated
     */
    private Integer equipTypeId;

    private String equipTypeName;

    public String getEquipTypeName(){ return equipTypeName; }

    public void setEquipTypeName(String equipTypeName){this.equipTypeName=equipTypeName;}
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equipment.DEPT_ID
     *
     * @mbggenerated
     */
    private Integer deptId;
    private String deptName;
    public String getDeptName(){return deptName;}
    public void setDeptName(String deptName){this.deptName=deptName;}

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equipment.EQUIP_STATUAS_ID
     *
     * @mbggenerated
     */
    //数据库中这个字段被改为EQUIP_STATUAS_CODE，由于改的时候会出现一些想不到的地方改不到，所以只改了xml中column，
    //其余的都不改，不会影响使用，别去纠结为什么不一样，不要去做杠精，如果喜欢那就自己去改
    private String equipStatuasId;
    private String codeName;

    public String getCodeName() {
        return codeName;
    }

    public void setCodeName(String codeName) {
        this.codeName = codeName;
    }

    //设备报修时 需要查询common_code 的设备状态 只在实体类里加个getset xml没有写 因为equipStatuasId值是“完好/占用”我需要数据库的code 用到的地方就equipStatusCode= equipStatuasId
    private String equipStatusCode;

    public String getEquipStatusCode() {
        return equipStatusCode;
    }

    public void setEquipStatusCode(String equipStatusCode) {
        this.equipStatusCode = equipStatusCode;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equipment.MODEL_NO
     *
     * @mbggenerated
     */
    private String modelNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equipment.SPEC
     *
     * @mbggenerated
     */
    private String spec;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equipment.ASSETS_COST
     *
     * @mbggenerated
     */
    private String assetsCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equipment.MANUFACTURER
     *
     * @mbggenerated
     */
    private String manufacturer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equipment.SUPPLIER
     *
     * @mbggenerated
     */
    private String supplier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equipment.PROPERTY_NO
     *
     * @mbggenerated
     */
   // private String propertyNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equipment.FACTORY_NO
     *
     * @mbggenerated
     */
    private String factoryNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equipment.DATE_PRODUC
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date dateProduc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equipment.RECORD_DATE
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date recordDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equipment.POSITION_ID
     *
     * @mbggenerated
     */
    private Integer positionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equipment.PROPERTY_ID
     *
     * @mbggenerated
     */
    //数据库中这个字段被改为PROPERTY_CODE，由于改的时候会出现一些想不到的地方改不到，所以只改了xml中column，
    //其余的都不改，不会影响使用，别去纠结为什么不一样，不要去做杠精，如果喜欢那就自己去改
    private String propertyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equipment.SOURCE_ASSETS
     *
     * @mbggenerated
     */
    private String sourceAssets;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equipment.ACCOUNT_FILE
     *
     * @mbggenerated
     */
    private String accountFile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equipment.CHECK_DIFF
     *
     * @mbggenerated
     */
    private String checkDiff;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equipment.TECHNICAL_PARM
     *
     * @mbggenerated
     */
    private String technicalParm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equipment.SENSITIVITY
     *
     * @mbggenerated
     */
    private String sensitivityX;

    private String sensitivityY;

    private String sensitivityZ;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equipment.PHY_QUANTI_ID
     *
     * @mbggenerated
     */
    private String phyQuantiId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equipment.COUPLING_ID
     *
     * @mbggenerated
     */
    private String couplingId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equipment.DIRECTION_ID
     *
     * @mbggenerated
     */
    private String directionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equipment.CLOUD_SN
     *
     * @mbggenerated
     */
    private String cloudSn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equipment.CUSTODIAN
     *
     * @mbggenerated
     */
    private String custodian;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equipment.STAND_MATE_YN
     *
     * @mbggenerated
     */
    private String standMateYn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equipment.MEMO
     *
     * @mbggenerated
     */
    private String memo;
    //设备关联的位置名称
private String positionName;

    public String getPositionName() {
        return positionName;
    }

    public void setPositionName(String positionName) {
        this.positionName = positionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equipment.EQUIP_ID
     *
     * @return the value of lims_equipment.EQUIP_ID
     *
     * @mbggenerated
     */
    public Integer getEquipId() {
        return equipId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equipment.EQUIP_ID
     *
     * @param equipId the value for lims_equipment.EQUIP_ID
     *
     * @mbggenerated
     */
    public void setEquipId(Integer equipId) {
        this.equipId = equipId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equipment.EQUIP_NO
     *
     * @return the value of lims_equipment.EQUIP_NO
     *
     * @mbggenerated
     */
    public String getEquipNo() {
        return equipNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equipment.EQUIP_NO
     *
     * @param equipNo the value for lims_equipment.EQUIP_NO
     *
     * @mbggenerated
     */
    public void setEquipNo(String equipNo) {
        this.equipNo = equipNo == null ? null : equipNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equipment.EQUIP_NAME
     *
     * @return the value of lims_equipment.EQUIP_NAME
     *
     * @mbggenerated
     */
    public String getEquipName() {
        return equipName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equipment.EQUIP_NAME
     *
     * @param equipName the value for lims_equipment.EQUIP_NAME
     *
     * @mbggenerated
     */
    public void setEquipName(String equipName) {
        this.equipName = equipName == null ? null : equipName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equipment.EQUIP_TYPE_ID
     *
     * @return the value of lims_equipment.EQUIP_TYPE_ID
     *
     * @mbggenerated
     */
    public Integer getEquipTypeId() {
        return equipTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equipment.EQUIP_TYPE_ID
     *
     * @param equipTypeId the value for lims_equipment.EQUIP_TYPE_ID
     *
     * @mbggenerated
     */
    public void setEquipTypeId(Integer equipTypeId) {
        this.equipTypeId = equipTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equipment.DEPT_ID
     *
     * @return the value of lims_equipment.DEPT_ID
     *
     * @mbggenerated
     */
    public Integer getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equipment.DEPT_ID
     *
     * @param deptId the value for lims_equipment.DEPT_ID
     *
     * @mbggenerated
     */
    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equipment.EQUIP_STATUAS_ID
     *
     * @return the value of lims_equipment.EQUIP_STATUAS_ID
     *
     * @mbggenerated
     */
    public String getEquipStatuasId() {
        return equipStatuasId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equipment.EQUIP_STATUAS_ID
     *
     * @param equipStatuasId the value for lims_equipment.EQUIP_STATUAS_ID
     *
     * @mbggenerated
     */
    public void setEquipStatuasId(String equipStatuasId) {
        this.equipStatuasId = equipStatuasId == null ? null : equipStatuasId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equipment.MODEL_NO
     *
     * @return the value of lims_equipment.MODEL_NO
     *
     * @mbggenerated
     */
    public String getModelNo() {
        return modelNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equipment.MODEL_NO
     *
     * @param modelNo the value for lims_equipment.MODEL_NO
     *
     * @mbggenerated
     */
    public void setModelNo(String modelNo) {
        this.modelNo = modelNo == null ? null : modelNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equipment.SPEC
     *
     * @return the value of lims_equipment.SPEC
     *
     * @mbggenerated
     */
    public String getSpec() {
        return spec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equipment.SPEC
     *
     * @param spec the value for lims_equipment.SPEC
     *
     * @mbggenerated
     */
    public void setSpec(String spec) {
        this.spec = spec == null ? null : spec.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equipment.ASSETS_COST
     *
     * @return the value of lims_equipment.ASSETS_COST
     *
     * @mbggenerated
     */
    public String getAssetsCost() {
        return assetsCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equipment.ASSETS_COST
     *
     * @param assetsCost the value for lims_equipment.ASSETS_COST
     *
     * @mbggenerated
     */
    public void setAssetsCost(String assetsCost) {
        this.assetsCost = assetsCost == null ? null : assetsCost.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equipment.MANUFACTURER
     *
     * @return the value of lims_equipment.MANUFACTURER
     *
     * @mbggenerated
     */
    public String getManufacturer() {
        return manufacturer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equipment.MANUFACTURER
     *
     * @param manufacturer the value for lims_equipment.MANUFACTURER
     *
     * @mbggenerated
     */
    public void setManufacturer(String manufacturer) {
        this.manufacturer = manufacturer == null ? null : manufacturer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equipment.SUPPLIER
     *
     * @return the value of lims_equipment.SUPPLIER
     *
     * @mbggenerated
     */
    public String getSupplier() {
        return supplier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equipment.SUPPLIER
     *
     * @param supplier the value for lims_equipment.SUPPLIER
     *
     * @mbggenerated
     */
    public void setSupplier(String supplier) {
        this.supplier = supplier == null ? null : supplier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equipment.PROPERTY_NO
     *
     * @return the value of lims_equipment.PROPERTY_NO
     *
     * @mbggenerated
     */
   /* public String getPropertyNo() {
        return propertyNo;
    }*/

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equipment.PROPERTY_NO
     *
     * @param propertyNo the value for lims_equipment.PROPERTY_NO
     *
     * @mbggenerated
     */
   /* public void setPropertyNo(String propertyNo) {
        this.propertyNo = propertyNo == null ? null : propertyNo.trim();
    }*/

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equipment.FACTORY_NO
     *
     * @return the value of lims_equipment.FACTORY_NO
     *
     * @mbggenerated
     */
    public String getFactoryNo() {
        return factoryNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equipment.FACTORY_NO
     *
     * @param factoryNo the value for lims_equipment.FACTORY_NO
     *
     * @mbggenerated
     */
    public void setFactoryNo(String factoryNo) {
        this.factoryNo = factoryNo == null ? null : factoryNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equipment.DATE_PRODUC
     *
     * @return the value of lims_equipment.DATE_PRODUC
     *
     * @mbggenerated
     */
    public Date getDateProduc() {
        return dateProduc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equipment.DATE_PRODUC
     *
     * @param dateProduc the value for lims_equipment.DATE_PRODUC
     *
     * @mbggenerated
     */
    public void setDateProduc(Date dateProduc) {
        this.dateProduc = dateProduc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equipment.RECORD_DATE
     *
     * @return the value of lims_equipment.RECORD_DATE
     *
     * @mbggenerated
     */
    public Date getRecordDate() {
        return recordDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equipment.RECORD_DATE
     *
     * @param recordDate the value for lims_equipment.RECORD_DATE
     *
     * @mbggenerated
     */
    public void setRecordDate(Date recordDate) {
        this.recordDate = recordDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equipment.POSITION_ID
     *
     * @return the value of lims_equipment.POSITION_ID
     *
     * @mbggenerated
     */
    public Integer getPositionId() {
        return positionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equipment.POSITION_ID
     *
     * @param positionId the value for lims_equipment.POSITION_ID
     *POSITION_ID
     * @mbggenerated
     */
    public void setPositionId(Integer positionId) {
        this.positionId = positionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equipment.PROPERTY_ID
     *
     * @return the value of lims_equipment.PROPERTY_ID
     *
     * @mbggenerated
     */
    public String getPropertyId() {
        return propertyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equipment.PROPERTY_ID
     *
     * @param propertyId the value for lims_equipment.PROPERTY_ID
     *
     * @mbggenerated
     */
    public void setPropertyId(String propertyId) {
        this.propertyId = propertyId == null ? null : propertyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equipment.SOURCE_ASSETS
     *
     * @return the value of lims_equipment.SOURCE_ASSETS
     *
     * @mbggenerated
     */
    public String getSourceAssets() {
        return sourceAssets;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equipment.SOURCE_ASSETS
     *
     * @param sourceAssets the value for lims_equipment.SOURCE_ASSETS
     *
     * @mbggenerated
     */
    public void setSourceAssets(String sourceAssets) {
        this.sourceAssets = sourceAssets == null ? null : sourceAssets.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equipment.ACCOUNT_FILE
     *
     * @return the value of lims_equipment.ACCOUNT_FILE
     *
     * @mbggenerated
     */
    public String getAccountFile() {
        return accountFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equipment.ACCOUNT_FILE
     *
     * @param accountFile the value for lims_equipment.ACCOUNT_FILE
     *
     * @mbggenerated
     */
    public void setAccountFile(String accountFile) {
        this.accountFile = accountFile == null ? null : accountFile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equipment.CHECK_DIFF
     *
     * @return the value of lims_equipment.CHECK_DIFF
     *
     * @mbggenerated
     */
    public String getCheckDiff() {
        return checkDiff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equipment.CHECK_DIFF
     *
     * @param checkDiff the value for lims_equipment.CHECK_DIFF
     *
     * @mbggenerated
     */
    public void setCheckDiff(String checkDiff) {
        this.checkDiff = checkDiff == null ? null : checkDiff.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equipment.TECHNICAL_PARM
     *
     * @return the value of lims_equipment.TECHNICAL_PARM
     *
     * @mbggenerated
     */
    public String getTechnicalParm() {
        return technicalParm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equipment.TECHNICAL_PARM
     *
     * @param technicalParm the value for lims_equipment.TECHNICAL_PARM
     *
     * @mbggenerated
     */
    public void setTechnicalParm(String technicalParm) {
        this.technicalParm = technicalParm == null ? null : technicalParm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equipment.SENSITIVITY
     *
     * @return the value of lims_equipment.SENSITIVITY
     *
     * @mbggenerated
     */
    public String getSensitivityX() {
        return sensitivityX;
    }

    public String getSensitivityY() {
        return sensitivityY;
    }

    public String getSensitivityZ() {
        return sensitivityZ;
    }


    public void setSensitivityX(String sensitivityX) {
        this.sensitivityX = sensitivityX == null ? null : sensitivityX.trim();
    }

    public void setSensitivityY(String sensitivityY) {
        this.sensitivityY = sensitivityY == null ? null : sensitivityY.trim();
    }

    public void setSensitivityZ(String sensitivityZ) {
        this.sensitivityZ = sensitivityZ == null ? null : sensitivityZ.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equipment.PHY_QUANTI_ID
     *
     * @return the value of lims_equipment.PHY_QUANTI_ID
     *
     * @mbggenerated
     */
    public String getPhyQuantiId() {
        return phyQuantiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equipment.PHY_QUANTI_ID
     *
     * @param phyQuantiId the value for lims_equipment.PHY_QUANTI_ID
     *
     * @mbggenerated
     */
    public void setPhyQuantiId(String phyQuantiId) {
        this.phyQuantiId = phyQuantiId == null ? null : phyQuantiId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equipment.COUPLING_ID
     *
     * @return the value of lims_equipment.COUPLING_ID
     *
     * @mbggenerated
     */
    public String getCouplingId() {
        return couplingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equipment.COUPLING_ID
     *
     * @param couplingId the value for lims_equipment.COUPLING_ID
     *
     * @mbggenerated
     */
    public void setCouplingId(String couplingId) {
        this.couplingId = couplingId == null ? null : couplingId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equipment.DIRECTION_ID
     *
     * @return the value of lims_equipment.DIRECTION_ID
     *
     * @mbggenerated
     */
    public String getDirectionId() {
        return directionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equipment.DIRECTION_ID
     *
     * @param directionId the value for lims_equipment.DIRECTION_ID
     *
     * @mbggenerated
     */
    public void setDirectionId(String directionId) {
        this.directionId = directionId == null ? null : directionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equipment.CLOUD_SN
     *
     * @return the value of lims_equipment.CLOUD_SN
     *
     * @mbggenerated
     */
    public String getCloudSn() {
        return cloudSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equipment.CLOUD_SN
     *
     * @param cloudSn the value for lims_equipment.CLOUD_SN
     *
     * @mbggenerated
     */
    public void setCloudSn(String cloudSn) {
        this.cloudSn = cloudSn == null ? null : cloudSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equipment.CUSTODIAN
     *
     * @return the value of lims_equipment.CUSTODIAN
     *
     * @mbggenerated
     */
    public String getCustodian() {
        return custodian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equipment.CUSTODIAN
     *
     * @param custodian the value for lims_equipment.CUSTODIAN
     *
     * @mbggenerated
     */
    public void setCustodian(String custodian) {
        this.custodian = custodian == null ? null : custodian.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equipment.STAND_MATE_YN
     *
     * @return the value of lims_equipment.STAND_MATE_YN
     *
     * @mbggenerated
     */
    public String getStandMateYn() {
        return standMateYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equipment.STAND_MATE_YN
     *
     * @param standMateYn the value for lims_equipment.STAND_MATE_YN
     *
     * @mbggenerated
     */
    public void setStandMateYn(String standMateYn) {
        this.standMateYn = standMateYn == null ? null : standMateYn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equipment.MEMO
     *
     * @return the value of lims_equipment.MEMO
     *
     * @mbggenerated
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equipment.MEMO
     *
     * @param memo the value for lims_equipment.MEMO
     *
     * @mbggenerated
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }
}