package com.xoa.model.equipment;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class EquipmentExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lims_equipment
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lims_equipment
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lims_equipment
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_equipment
     *
     * @mbggenerated
     */
    public EquipmentExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_equipment
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_equipment
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_equipment
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_equipment
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_equipment
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_equipment
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_equipment
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_equipment
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_equipment
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_equipment
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table lims_equipment
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andEquipIdIsNull() {
            addCriterion("EQUIP_ID is null");
            return (Criteria) this;
        }

        public Criteria andEquipIdIsNotNull() {
            addCriterion("EQUIP_ID is not null");
            return (Criteria) this;
        }

        public Criteria andEquipIdEqualTo(String value) {
            addCriterion("EQUIP_ID =", value, "equipId");
            return (Criteria) this;
        }

        public Criteria andEquipIdNotEqualTo(String value) {
            addCriterion("EQUIP_ID <>", value, "equipId");
            return (Criteria) this;
        }

        public Criteria andEquipIdGreaterThan(String value) {
            addCriterion("EQUIP_ID >", value, "equipId");
            return (Criteria) this;
        }

        public Criteria andEquipIdGreaterThanOrEqualTo(String value) {
            addCriterion("EQUIP_ID >=", value, "equipId");
            return (Criteria) this;
        }

        public Criteria andEquipIdLessThan(String value) {
            addCriterion("EQUIP_ID <", value, "equipId");
            return (Criteria) this;
        }

        public Criteria andEquipIdLessThanOrEqualTo(String value) {
            addCriterion("EQUIP_ID <=", value, "equipId");
            return (Criteria) this;
        }

        public Criteria andEquipIdLike(String value) {
            addCriterion("EQUIP_ID like", value, "equipId");
            return (Criteria) this;
        }

        public Criteria andEquipIdNotLike(String value) {
            addCriterion("EQUIP_ID not like", value, "equipId");
            return (Criteria) this;
        }

        public Criteria andEquipIdIn(List<String> values) {
            addCriterion("EQUIP_ID in", values, "equipId");
            return (Criteria) this;
        }

        public Criteria andEquipIdNotIn(List<String> values) {
            addCriterion("EQUIP_ID not in", values, "equipId");
            return (Criteria) this;
        }

        public Criteria andEquipIdBetween(String value1, String value2) {
            addCriterion("EQUIP_ID between", value1, value2, "equipId");
            return (Criteria) this;
        }

        public Criteria andEquipIdNotBetween(String value1, String value2) {
            addCriterion("EQUIP_ID not between", value1, value2, "equipId");
            return (Criteria) this;
        }

        public Criteria andEquipNoIsNull() {
            addCriterion("EQUIP_NO is null");
            return (Criteria) this;
        }

        public Criteria andEquipNoIsNotNull() {
            addCriterion("EQUIP_NO is not null");
            return (Criteria) this;
        }

        public Criteria andEquipNoEqualTo(String value) {
            addCriterion("EQUIP_NO =", value, "equipNo");
            return (Criteria) this;
        }

        public Criteria andEquipNoNotEqualTo(String value) {
            addCriterion("EQUIP_NO <>", value, "equipNo");
            return (Criteria) this;
        }

        public Criteria andEquipNoGreaterThan(String value) {
            addCriterion("EQUIP_NO >", value, "equipNo");
            return (Criteria) this;
        }

        public Criteria andEquipNoGreaterThanOrEqualTo(String value) {
            addCriterion("EQUIP_NO >=", value, "equipNo");
            return (Criteria) this;
        }

        public Criteria andEquipNoLessThan(String value) {
            addCriterion("EQUIP_NO <", value, "equipNo");
            return (Criteria) this;
        }

        public Criteria andEquipNoLessThanOrEqualTo(String value) {
            addCriterion("EQUIP_NO <=", value, "equipNo");
            return (Criteria) this;
        }

        public Criteria andEquipNoLike(String value) {
            addCriterion("EQUIP_NO like", value, "equipNo");
            return (Criteria) this;
        }

        public Criteria andEquipNoNotLike(String value) {
            addCriterion("EQUIP_NO not like", value, "equipNo");
            return (Criteria) this;
        }

        public Criteria andEquipNoIn(List<String> values) {
            addCriterion("EQUIP_NO in", values, "equipNo");
            return (Criteria) this;
        }

        public Criteria andEquipNoNotIn(List<String> values) {
            addCriterion("EQUIP_NO not in", values, "equipNo");
            return (Criteria) this;
        }

        public Criteria andEquipNoBetween(String value1, String value2) {
            addCriterion("EQUIP_NO between", value1, value2, "equipNo");
            return (Criteria) this;
        }

        public Criteria andEquipNoNotBetween(String value1, String value2) {
            addCriterion("EQUIP_NO not between", value1, value2, "equipNo");
            return (Criteria) this;
        }

        public Criteria andEquipNameIsNull() {
            addCriterion("EQUIP_NAME is null");
            return (Criteria) this;
        }

        public Criteria andEquipNameIsNotNull() {
            addCriterion("EQUIP_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andEquipNameEqualTo(String value) {
            addCriterion("EQUIP_NAME =", value, "equipName");
            return (Criteria) this;
        }

        public Criteria andEquipNameNotEqualTo(String value) {
            addCriterion("EQUIP_NAME <>", value, "equipName");
            return (Criteria) this;
        }

        public Criteria andEquipNameGreaterThan(String value) {
            addCriterion("EQUIP_NAME >", value, "equipName");
            return (Criteria) this;
        }

        public Criteria andEquipNameGreaterThanOrEqualTo(String value) {
            addCriterion("EQUIP_NAME >=", value, "equipName");
            return (Criteria) this;
        }

        public Criteria andEquipNameLessThan(String value) {
            addCriterion("EQUIP_NAME <", value, "equipName");
            return (Criteria) this;
        }

        public Criteria andEquipNameLessThanOrEqualTo(String value) {
            addCriterion("EQUIP_NAME <=", value, "equipName");
            return (Criteria) this;
        }

        public Criteria andEquipNameLike(String value) {
            addCriterion("EQUIP_NAME like", value, "equipName");
            return (Criteria) this;
        }

        public Criteria andEquipNameNotLike(String value) {
            addCriterion("EQUIP_NAME not like", value, "equipName");
            return (Criteria) this;
        }

        public Criteria andEquipNameIn(List<String> values) {
            addCriterion("EQUIP_NAME in", values, "equipName");
            return (Criteria) this;
        }

        public Criteria andEquipNameNotIn(List<String> values) {
            addCriterion("EQUIP_NAME not in", values, "equipName");
            return (Criteria) this;
        }

        public Criteria andEquipNameBetween(String value1, String value2) {
            addCriterion("EQUIP_NAME between", value1, value2, "equipName");
            return (Criteria) this;
        }

        public Criteria andEquipNameNotBetween(String value1, String value2) {
            addCriterion("EQUIP_NAME not between", value1, value2, "equipName");
            return (Criteria) this;
        }

        public Criteria andEquipTypeIdIsNull() {
            addCriterion("EQUIP_TYPE_ID is null");
            return (Criteria) this;
        }

        public Criteria andEquipTypeIdIsNotNull() {
            addCriterion("EQUIP_TYPE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andEquipTypeIdEqualTo(Integer value) {
            addCriterion("EQUIP_TYPE_ID =", value, "equipTypeId");
            return (Criteria) this;
        }

        public Criteria andEquipTypeIdNotEqualTo(Integer value) {
            addCriterion("EQUIP_TYPE_ID <>", value, "equipTypeId");
            return (Criteria) this;
        }

        public Criteria andEquipTypeIdGreaterThan(Integer value) {
            addCriterion("EQUIP_TYPE_ID >", value, "equipTypeId");
            return (Criteria) this;
        }

        public Criteria andEquipTypeIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("EQUIP_TYPE_ID >=", value, "equipTypeId");
            return (Criteria) this;
        }

        public Criteria andEquipTypeIdLessThan(Integer value) {
            addCriterion("EQUIP_TYPE_ID <", value, "equipTypeId");
            return (Criteria) this;
        }

        public Criteria andEquipTypeIdLessThanOrEqualTo(Integer value) {
            addCriterion("EQUIP_TYPE_ID <=", value, "equipTypeId");
            return (Criteria) this;
        }

        public Criteria andEquipTypeIdIn(List<Integer> values) {
            addCriterion("EQUIP_TYPE_ID in", values, "equipTypeId");
            return (Criteria) this;
        }

        public Criteria andEquipTypeIdNotIn(List<Integer> values) {
            addCriterion("EQUIP_TYPE_ID not in", values, "equipTypeId");
            return (Criteria) this;
        }

        public Criteria andEquipTypeIdBetween(Integer value1, Integer value2) {
            addCriterion("EQUIP_TYPE_ID between", value1, value2, "equipTypeId");
            return (Criteria) this;
        }

        public Criteria andEquipTypeIdNotBetween(Integer value1, Integer value2) {
            addCriterion("EQUIP_TYPE_ID not between", value1, value2, "equipTypeId");
            return (Criteria) this;
        }

        public Criteria andDeptIdIsNull() {
            addCriterion("DEPT_ID is null");
            return (Criteria) this;
        }

        public Criteria andDeptIdIsNotNull() {
            addCriterion("DEPT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andDeptIdEqualTo(Integer value) {
            addCriterion("DEPT_ID =", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdNotEqualTo(Integer value) {
            addCriterion("DEPT_ID <>", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdGreaterThan(Integer value) {
            addCriterion("DEPT_ID >", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("DEPT_ID >=", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdLessThan(Integer value) {
            addCriterion("DEPT_ID <", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdLessThanOrEqualTo(Integer value) {
            addCriterion("DEPT_ID <=", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdIn(List<Integer> values) {
            addCriterion("DEPT_ID in", values, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdNotIn(List<Integer> values) {
            addCriterion("DEPT_ID not in", values, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdBetween(Integer value1, Integer value2) {
            addCriterion("DEPT_ID between", value1, value2, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdNotBetween(Integer value1, Integer value2) {
            addCriterion("DEPT_ID not between", value1, value2, "deptId");
            return (Criteria) this;
        }

        public Criteria andEquipStatuasIdIsNull() {
            addCriterion("EQUIP_STATUAS_ID is null");
            return (Criteria) this;
        }

        public Criteria andEquipStatuasIdIsNotNull() {
            addCriterion("EQUIP_STATUAS_ID is not null");
            return (Criteria) this;
        }

        public Criteria andEquipStatuasIdEqualTo(String value) {
            addCriterion("EQUIP_STATUAS_ID =", value, "equipStatuasId");
            return (Criteria) this;
        }

        public Criteria andEquipStatuasIdNotEqualTo(String value) {
            addCriterion("EQUIP_STATUAS_ID <>", value, "equipStatuasId");
            return (Criteria) this;
        }

        public Criteria andEquipStatuasIdGreaterThan(String value) {
            addCriterion("EQUIP_STATUAS_ID >", value, "equipStatuasId");
            return (Criteria) this;
        }

        public Criteria andEquipStatuasIdGreaterThanOrEqualTo(String value) {
            addCriterion("EQUIP_STATUAS_ID >=", value, "equipStatuasId");
            return (Criteria) this;
        }

        public Criteria andEquipStatuasIdLessThan(String value) {
            addCriterion("EQUIP_STATUAS_ID <", value, "equipStatuasId");
            return (Criteria) this;
        }

        public Criteria andEquipStatuasIdLessThanOrEqualTo(String value) {
            addCriterion("EQUIP_STATUAS_ID <=", value, "equipStatuasId");
            return (Criteria) this;
        }

        public Criteria andEquipStatuasIdLike(String value) {
            addCriterion("EQUIP_STATUAS_ID like", value, "equipStatuasId");
            return (Criteria) this;
        }

        public Criteria andEquipStatuasIdNotLike(String value) {
            addCriterion("EQUIP_STATUAS_ID not like", value, "equipStatuasId");
            return (Criteria) this;
        }

        public Criteria andEquipStatuasIdIn(List<String> values) {
            addCriterion("EQUIP_STATUAS_ID in", values, "equipStatuasId");
            return (Criteria) this;
        }

        public Criteria andEquipStatuasIdNotIn(List<String> values) {
            addCriterion("EQUIP_STATUAS_ID not in", values, "equipStatuasId");
            return (Criteria) this;
        }

        public Criteria andEquipStatuasIdBetween(String value1, String value2) {
            addCriterion("EQUIP_STATUAS_ID between", value1, value2, "equipStatuasId");
            return (Criteria) this;
        }

        public Criteria andEquipStatuasIdNotBetween(String value1, String value2) {
            addCriterion("EQUIP_STATUAS_ID not between", value1, value2, "equipStatuasId");
            return (Criteria) this;
        }

        public Criteria andModelNoIsNull() {
            addCriterion("MODEL_NO is null");
            return (Criteria) this;
        }

        public Criteria andModelNoIsNotNull() {
            addCriterion("MODEL_NO is not null");
            return (Criteria) this;
        }

        public Criteria andModelNoEqualTo(String value) {
            addCriterion("MODEL_NO =", value, "modelNo");
            return (Criteria) this;
        }

        public Criteria andModelNoNotEqualTo(String value) {
            addCriterion("MODEL_NO <>", value, "modelNo");
            return (Criteria) this;
        }

        public Criteria andModelNoGreaterThan(String value) {
            addCriterion("MODEL_NO >", value, "modelNo");
            return (Criteria) this;
        }

        public Criteria andModelNoGreaterThanOrEqualTo(String value) {
            addCriterion("MODEL_NO >=", value, "modelNo");
            return (Criteria) this;
        }

        public Criteria andModelNoLessThan(String value) {
            addCriterion("MODEL_NO <", value, "modelNo");
            return (Criteria) this;
        }

        public Criteria andModelNoLessThanOrEqualTo(String value) {
            addCriterion("MODEL_NO <=", value, "modelNo");
            return (Criteria) this;
        }

        public Criteria andModelNoLike(String value) {
            addCriterion("MODEL_NO like", value, "modelNo");
            return (Criteria) this;
        }

        public Criteria andModelNoNotLike(String value) {
            addCriterion("MODEL_NO not like", value, "modelNo");
            return (Criteria) this;
        }

        public Criteria andModelNoIn(List<String> values) {
            addCriterion("MODEL_NO in", values, "modelNo");
            return (Criteria) this;
        }

        public Criteria andModelNoNotIn(List<String> values) {
            addCriterion("MODEL_NO not in", values, "modelNo");
            return (Criteria) this;
        }

        public Criteria andModelNoBetween(String value1, String value2) {
            addCriterion("MODEL_NO between", value1, value2, "modelNo");
            return (Criteria) this;
        }

        public Criteria andModelNoNotBetween(String value1, String value2) {
            addCriterion("MODEL_NO not between", value1, value2, "modelNo");
            return (Criteria) this;
        }

        public Criteria andSpecIsNull() {
            addCriterion("SPEC is null");
            return (Criteria) this;
        }

        public Criteria andSpecIsNotNull() {
            addCriterion("SPEC is not null");
            return (Criteria) this;
        }

        public Criteria andSpecEqualTo(String value) {
            addCriterion("SPEC =", value, "spec");
            return (Criteria) this;
        }

        public Criteria andSpecNotEqualTo(String value) {
            addCriterion("SPEC <>", value, "spec");
            return (Criteria) this;
        }

        public Criteria andSpecGreaterThan(String value) {
            addCriterion("SPEC >", value, "spec");
            return (Criteria) this;
        }

        public Criteria andSpecGreaterThanOrEqualTo(String value) {
            addCriterion("SPEC >=", value, "spec");
            return (Criteria) this;
        }

        public Criteria andSpecLessThan(String value) {
            addCriterion("SPEC <", value, "spec");
            return (Criteria) this;
        }

        public Criteria andSpecLessThanOrEqualTo(String value) {
            addCriterion("SPEC <=", value, "spec");
            return (Criteria) this;
        }

        public Criteria andSpecLike(String value) {
            addCriterion("SPEC like", value, "spec");
            return (Criteria) this;
        }

        public Criteria andSpecNotLike(String value) {
            addCriterion("SPEC not like", value, "spec");
            return (Criteria) this;
        }

        public Criteria andSpecIn(List<String> values) {
            addCriterion("SPEC in", values, "spec");
            return (Criteria) this;
        }

        public Criteria andSpecNotIn(List<String> values) {
            addCriterion("SPEC not in", values, "spec");
            return (Criteria) this;
        }

        public Criteria andSpecBetween(String value1, String value2) {
            addCriterion("SPEC between", value1, value2, "spec");
            return (Criteria) this;
        }

        public Criteria andSpecNotBetween(String value1, String value2) {
            addCriterion("SPEC not between", value1, value2, "spec");
            return (Criteria) this;
        }

        public Criteria andAssetsCostIsNull() {
            addCriterion("ASSETS_COST is null");
            return (Criteria) this;
        }

        public Criteria andAssetsCostIsNotNull() {
            addCriterion("ASSETS_COST is not null");
            return (Criteria) this;
        }

        public Criteria andAssetsCostEqualTo(String value) {
            addCriterion("ASSETS_COST =", value, "assetsCost");
            return (Criteria) this;
        }

        public Criteria andAssetsCostNotEqualTo(String value) {
            addCriterion("ASSETS_COST <>", value, "assetsCost");
            return (Criteria) this;
        }

        public Criteria andAssetsCostGreaterThan(String value) {
            addCriterion("ASSETS_COST >", value, "assetsCost");
            return (Criteria) this;
        }

        public Criteria andAssetsCostGreaterThanOrEqualTo(String value) {
            addCriterion("ASSETS_COST >=", value, "assetsCost");
            return (Criteria) this;
        }

        public Criteria andAssetsCostLessThan(String value) {
            addCriterion("ASSETS_COST <", value, "assetsCost");
            return (Criteria) this;
        }

        public Criteria andAssetsCostLessThanOrEqualTo(String value) {
            addCriterion("ASSETS_COST <=", value, "assetsCost");
            return (Criteria) this;
        }

        public Criteria andAssetsCostLike(String value) {
            addCriterion("ASSETS_COST like", value, "assetsCost");
            return (Criteria) this;
        }

        public Criteria andAssetsCostNotLike(String value) {
            addCriterion("ASSETS_COST not like", value, "assetsCost");
            return (Criteria) this;
        }

        public Criteria andAssetsCostIn(List<String> values) {
            addCriterion("ASSETS_COST in", values, "assetsCost");
            return (Criteria) this;
        }

        public Criteria andAssetsCostNotIn(List<String> values) {
            addCriterion("ASSETS_COST not in", values, "assetsCost");
            return (Criteria) this;
        }

        public Criteria andAssetsCostBetween(String value1, String value2) {
            addCriterion("ASSETS_COST between", value1, value2, "assetsCost");
            return (Criteria) this;
        }

        public Criteria andAssetsCostNotBetween(String value1, String value2) {
            addCriterion("ASSETS_COST not between", value1, value2, "assetsCost");
            return (Criteria) this;
        }

        public Criteria andManufacturerIsNull() {
            addCriterion("MANUFACTURER is null");
            return (Criteria) this;
        }

        public Criteria andManufacturerIsNotNull() {
            addCriterion("MANUFACTURER is not null");
            return (Criteria) this;
        }

        public Criteria andManufacturerEqualTo(String value) {
            addCriterion("MANUFACTURER =", value, "manufacturer");
            return (Criteria) this;
        }

        public Criteria andManufacturerNotEqualTo(String value) {
            addCriterion("MANUFACTURER <>", value, "manufacturer");
            return (Criteria) this;
        }

        public Criteria andManufacturerGreaterThan(String value) {
            addCriterion("MANUFACTURER >", value, "manufacturer");
            return (Criteria) this;
        }

        public Criteria andManufacturerGreaterThanOrEqualTo(String value) {
            addCriterion("MANUFACTURER >=", value, "manufacturer");
            return (Criteria) this;
        }

        public Criteria andManufacturerLessThan(String value) {
            addCriterion("MANUFACTURER <", value, "manufacturer");
            return (Criteria) this;
        }

        public Criteria andManufacturerLessThanOrEqualTo(String value) {
            addCriterion("MANUFACTURER <=", value, "manufacturer");
            return (Criteria) this;
        }

        public Criteria andManufacturerLike(String value) {
            addCriterion("MANUFACTURER like", value, "manufacturer");
            return (Criteria) this;
        }

        public Criteria andManufacturerNotLike(String value) {
            addCriterion("MANUFACTURER not like", value, "manufacturer");
            return (Criteria) this;
        }

        public Criteria andManufacturerIn(List<String> values) {
            addCriterion("MANUFACTURER in", values, "manufacturer");
            return (Criteria) this;
        }

        public Criteria andManufacturerNotIn(List<String> values) {
            addCriterion("MANUFACTURER not in", values, "manufacturer");
            return (Criteria) this;
        }

        public Criteria andManufacturerBetween(String value1, String value2) {
            addCriterion("MANUFACTURER between", value1, value2, "manufacturer");
            return (Criteria) this;
        }

        public Criteria andManufacturerNotBetween(String value1, String value2) {
            addCriterion("MANUFACTURER not between", value1, value2, "manufacturer");
            return (Criteria) this;
        }

        public Criteria andSupplierIsNull() {
            addCriterion("SUPPLIER is null");
            return (Criteria) this;
        }

        public Criteria andSupplierIsNotNull() {
            addCriterion("SUPPLIER is not null");
            return (Criteria) this;
        }

        public Criteria andSupplierEqualTo(String value) {
            addCriterion("SUPPLIER =", value, "supplier");
            return (Criteria) this;
        }

        public Criteria andSupplierNotEqualTo(String value) {
            addCriterion("SUPPLIER <>", value, "supplier");
            return (Criteria) this;
        }

        public Criteria andSupplierGreaterThan(String value) {
            addCriterion("SUPPLIER >", value, "supplier");
            return (Criteria) this;
        }

        public Criteria andSupplierGreaterThanOrEqualTo(String value) {
            addCriterion("SUPPLIER >=", value, "supplier");
            return (Criteria) this;
        }

        public Criteria andSupplierLessThan(String value) {
            addCriterion("SUPPLIER <", value, "supplier");
            return (Criteria) this;
        }

        public Criteria andSupplierLessThanOrEqualTo(String value) {
            addCriterion("SUPPLIER <=", value, "supplier");
            return (Criteria) this;
        }

        public Criteria andSupplierLike(String value) {
            addCriterion("SUPPLIER like", value, "supplier");
            return (Criteria) this;
        }

        public Criteria andSupplierNotLike(String value) {
            addCriterion("SUPPLIER not like", value, "supplier");
            return (Criteria) this;
        }

        public Criteria andSupplierIn(List<String> values) {
            addCriterion("SUPPLIER in", values, "supplier");
            return (Criteria) this;
        }

        public Criteria andSupplierNotIn(List<String> values) {
            addCriterion("SUPPLIER not in", values, "supplier");
            return (Criteria) this;
        }

        public Criteria andSupplierBetween(String value1, String value2) {
            addCriterion("SUPPLIER between", value1, value2, "supplier");
            return (Criteria) this;
        }

        public Criteria andSupplierNotBetween(String value1, String value2) {
            addCriterion("SUPPLIER not between", value1, value2, "supplier");
            return (Criteria) this;
        }

        public Criteria andPropertyNoIsNull() {
            addCriterion("PROPERTY_NO is null");
            return (Criteria) this;
        }

        public Criteria andPropertyNoIsNotNull() {
            addCriterion("PROPERTY_NO is not null");
            return (Criteria) this;
        }

        public Criteria andPropertyNoEqualTo(String value) {
            addCriterion("PROPERTY_NO =", value, "propertyNo");
            return (Criteria) this;
        }

        public Criteria andPropertyNoNotEqualTo(String value) {
            addCriterion("PROPERTY_NO <>", value, "propertyNo");
            return (Criteria) this;
        }

        public Criteria andPropertyNoGreaterThan(String value) {
            addCriterion("PROPERTY_NO >", value, "propertyNo");
            return (Criteria) this;
        }

        public Criteria andPropertyNoGreaterThanOrEqualTo(String value) {
            addCriterion("PROPERTY_NO >=", value, "propertyNo");
            return (Criteria) this;
        }

        public Criteria andPropertyNoLessThan(String value) {
            addCriterion("PROPERTY_NO <", value, "propertyNo");
            return (Criteria) this;
        }

        public Criteria andPropertyNoLessThanOrEqualTo(String value) {
            addCriterion("PROPERTY_NO <=", value, "propertyNo");
            return (Criteria) this;
        }

        public Criteria andPropertyNoLike(String value) {
            addCriterion("PROPERTY_NO like", value, "propertyNo");
            return (Criteria) this;
        }

        public Criteria andPropertyNoNotLike(String value) {
            addCriterion("PROPERTY_NO not like", value, "propertyNo");
            return (Criteria) this;
        }

        public Criteria andPropertyNoIn(List<String> values) {
            addCriterion("PROPERTY_NO in", values, "propertyNo");
            return (Criteria) this;
        }

        public Criteria andPropertyNoNotIn(List<String> values) {
            addCriterion("PROPERTY_NO not in", values, "propertyNo");
            return (Criteria) this;
        }

        public Criteria andPropertyNoBetween(String value1, String value2) {
            addCriterion("PROPERTY_NO between", value1, value2, "propertyNo");
            return (Criteria) this;
        }

        public Criteria andPropertyNoNotBetween(String value1, String value2) {
            addCriterion("PROPERTY_NO not between", value1, value2, "propertyNo");
            return (Criteria) this;
        }

        public Criteria andFactoryNoIsNull() {
            addCriterion("FACTORY_NO is null");
            return (Criteria) this;
        }

        public Criteria andFactoryNoIsNotNull() {
            addCriterion("FACTORY_NO is not null");
            return (Criteria) this;
        }

        public Criteria andFactoryNoEqualTo(String value) {
            addCriterion("FACTORY_NO =", value, "factoryNo");
            return (Criteria) this;
        }

        public Criteria andFactoryNoNotEqualTo(String value) {
            addCriterion("FACTORY_NO <>", value, "factoryNo");
            return (Criteria) this;
        }

        public Criteria andFactoryNoGreaterThan(String value) {
            addCriterion("FACTORY_NO >", value, "factoryNo");
            return (Criteria) this;
        }

        public Criteria andFactoryNoGreaterThanOrEqualTo(String value) {
            addCriterion("FACTORY_NO >=", value, "factoryNo");
            return (Criteria) this;
        }

        public Criteria andFactoryNoLessThan(String value) {
            addCriterion("FACTORY_NO <", value, "factoryNo");
            return (Criteria) this;
        }

        public Criteria andFactoryNoLessThanOrEqualTo(String value) {
            addCriterion("FACTORY_NO <=", value, "factoryNo");
            return (Criteria) this;
        }

        public Criteria andFactoryNoLike(String value) {
            addCriterion("FACTORY_NO like", value, "factoryNo");
            return (Criteria) this;
        }

        public Criteria andFactoryNoNotLike(String value) {
            addCriterion("FACTORY_NO not like", value, "factoryNo");
            return (Criteria) this;
        }

        public Criteria andFactoryNoIn(List<String> values) {
            addCriterion("FACTORY_NO in", values, "factoryNo");
            return (Criteria) this;
        }

        public Criteria andFactoryNoNotIn(List<String> values) {
            addCriterion("FACTORY_NO not in", values, "factoryNo");
            return (Criteria) this;
        }

        public Criteria andFactoryNoBetween(String value1, String value2) {
            addCriterion("FACTORY_NO between", value1, value2, "factoryNo");
            return (Criteria) this;
        }

        public Criteria andFactoryNoNotBetween(String value1, String value2) {
            addCriterion("FACTORY_NO not between", value1, value2, "factoryNo");
            return (Criteria) this;
        }

        public Criteria andDateProducIsNull() {
            addCriterion("DATE_PRODUC is null");
            return (Criteria) this;
        }

        public Criteria andDateProducIsNotNull() {
            addCriterion("DATE_PRODUC is not null");
            return (Criteria) this;
        }

        public Criteria andDateProducEqualTo(String value) {
            addCriterion("DATE_PRODUC =", value, "dateProduc");
            return (Criteria) this;
        }

        public Criteria andDateProducNotEqualTo(String value) {
            addCriterion("DATE_PRODUC <>", value, "dateProduc");
            return (Criteria) this;
        }

        public Criteria andDateProducGreaterThan(String value) {
            addCriterion("DATE_PRODUC >", value, "dateProduc");
            return (Criteria) this;
        }

        public Criteria andDateProducGreaterThanOrEqualTo(String value) {
            addCriterion("DATE_PRODUC >=", value, "dateProduc");
            return (Criteria) this;
        }

        public Criteria andDateProducLessThan(String value) {
            addCriterion("DATE_PRODUC <", value, "dateProduc");
            return (Criteria) this;
        }

        public Criteria andDateProducLessThanOrEqualTo(String value) {
            addCriterion("DATE_PRODUC <=", value, "dateProduc");
            return (Criteria) this;
        }

        public Criteria andDateProducLike(String value) {
            addCriterion("DATE_PRODUC like", value, "dateProduc");
            return (Criteria) this;
        }

        public Criteria andDateProducNotLike(String value) {
            addCriterion("DATE_PRODUC not like", value, "dateProduc");
            return (Criteria) this;
        }

        public Criteria andDateProducIn(List<String> values) {
            addCriterion("DATE_PRODUC in", values, "dateProduc");
            return (Criteria) this;
        }

        public Criteria andDateProducNotIn(List<String> values) {
            addCriterion("DATE_PRODUC not in", values, "dateProduc");
            return (Criteria) this;
        }

        public Criteria andDateProducBetween(String value1, String value2) {
            addCriterion("DATE_PRODUC between", value1, value2, "dateProduc");
            return (Criteria) this;
        }

        public Criteria andDateProducNotBetween(String value1, String value2) {
            addCriterion("DATE_PRODUC not between", value1, value2, "dateProduc");
            return (Criteria) this;
        }

        public Criteria andRecordDateIsNull() {
            addCriterion("RECORD_DATE is null");
            return (Criteria) this;
        }

        public Criteria andRecordDateIsNotNull() {
            addCriterion("RECORD_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andRecordDateEqualTo(Date value) {
            addCriterion("RECORD_DATE =", value, "recordDate");
            return (Criteria) this;
        }

        public Criteria andRecordDateNotEqualTo(Date value) {
            addCriterion("RECORD_DATE <>", value, "recordDate");
            return (Criteria) this;
        }

        public Criteria andRecordDateGreaterThan(Date value) {
            addCriterion("RECORD_DATE >", value, "recordDate");
            return (Criteria) this;
        }

        public Criteria andRecordDateGreaterThanOrEqualTo(Date value) {
            addCriterion("RECORD_DATE >=", value, "recordDate");
            return (Criteria) this;
        }

        public Criteria andRecordDateLessThan(Date value) {
            addCriterion("RECORD_DATE <", value, "recordDate");
            return (Criteria) this;
        }

        public Criteria andRecordDateLessThanOrEqualTo(Date value) {
            addCriterion("RECORD_DATE <=", value, "recordDate");
            return (Criteria) this;
        }

        public Criteria andRecordDateIn(List<Date> values) {
            addCriterion("RECORD_DATE in", values, "recordDate");
            return (Criteria) this;
        }

        public Criteria andRecordDateNotIn(List<Date> values) {
            addCriterion("RECORD_DATE not in", values, "recordDate");
            return (Criteria) this;
        }

        public Criteria andRecordDateBetween(Date value1, Date value2) {
            addCriterion("RECORD_DATE between", value1, value2, "recordDate");
            return (Criteria) this;
        }

        public Criteria andRecordDateNotBetween(Date value1, Date value2) {
            addCriterion("RECORD_DATE not between", value1, value2, "recordDate");
            return (Criteria) this;
        }

        public Criteria andPositionIdIsNull() {
            addCriterion("POSITION_ID is null");
            return (Criteria) this;
        }

        public Criteria andPositionIdIsNotNull() {
            addCriterion("POSITION_ID is not null");
            return (Criteria) this;
        }

        public Criteria andPositionIdEqualTo(String value) {
            addCriterion("POSITION_ID =", value, "positionId");
            return (Criteria) this;
        }

        public Criteria andPositionIdNotEqualTo(String value) {
            addCriterion("POSITION_ID <>", value, "positionId");
            return (Criteria) this;
        }

        public Criteria andPositionIdGreaterThan(String value) {
            addCriterion("POSITION_ID >", value, "positionId");
            return (Criteria) this;
        }

        public Criteria andPositionIdGreaterThanOrEqualTo(String value) {
            addCriterion("POSITION_ID >=", value, "positionId");
            return (Criteria) this;
        }

        public Criteria andPositionIdLessThan(String value) {
            addCriterion("POSITION_ID <", value, "positionId");
            return (Criteria) this;
        }

        public Criteria andPositionIdLessThanOrEqualTo(String value) {
            addCriterion("POSITION_ID <=", value, "positionId");
            return (Criteria) this;
        }

        public Criteria andPositionIdLike(String value) {
            addCriterion("POSITION_ID like", value, "positionId");
            return (Criteria) this;
        }

        public Criteria andPositionIdNotLike(String value) {
            addCriterion("POSITION_ID not like", value, "positionId");
            return (Criteria) this;
        }

        public Criteria andPositionIdIn(List<String> values) {
            addCriterion("POSITION_ID in", values, "positionId");
            return (Criteria) this;
        }

        public Criteria andPositionIdNotIn(List<String> values) {
            addCriterion("POSITION_ID not in", values, "positionId");
            return (Criteria) this;
        }

        public Criteria andPositionIdBetween(String value1, String value2) {
            addCriterion("POSITION_ID between", value1, value2, "positionId");
            return (Criteria) this;
        }

        public Criteria andPositionIdNotBetween(String value1, String value2) {
            addCriterion("POSITION_ID not between", value1, value2, "positionId");
            return (Criteria) this;
        }

        public Criteria andPropertyIdIsNull() {
            addCriterion("PROPERTY_ID is null");
            return (Criteria) this;
        }

        public Criteria andPropertyIdIsNotNull() {
            addCriterion("PROPERTY_ID is not null");
            return (Criteria) this;
        }

        public Criteria andPropertyIdEqualTo(String value) {
            addCriterion("PROPERTY_ID =", value, "propertyId");
            return (Criteria) this;
        }

        public Criteria andPropertyIdNotEqualTo(String value) {
            addCriterion("PROPERTY_ID <>", value, "propertyId");
            return (Criteria) this;
        }

        public Criteria andPropertyIdGreaterThan(String value) {
            addCriterion("PROPERTY_ID >", value, "propertyId");
            return (Criteria) this;
        }

        public Criteria andPropertyIdGreaterThanOrEqualTo(String value) {
            addCriterion("PROPERTY_ID >=", value, "propertyId");
            return (Criteria) this;
        }

        public Criteria andPropertyIdLessThan(String value) {
            addCriterion("PROPERTY_ID <", value, "propertyId");
            return (Criteria) this;
        }

        public Criteria andPropertyIdLessThanOrEqualTo(String value) {
            addCriterion("PROPERTY_ID <=", value, "propertyId");
            return (Criteria) this;
        }

        public Criteria andPropertyIdLike(String value) {
            addCriterion("PROPERTY_ID like", value, "propertyId");
            return (Criteria) this;
        }

        public Criteria andPropertyIdNotLike(String value) {
            addCriterion("PROPERTY_ID not like", value, "propertyId");
            return (Criteria) this;
        }

        public Criteria andPropertyIdIn(List<String> values) {
            addCriterion("PROPERTY_ID in", values, "propertyId");
            return (Criteria) this;
        }

        public Criteria andPropertyIdNotIn(List<String> values) {
            addCriterion("PROPERTY_ID not in", values, "propertyId");
            return (Criteria) this;
        }

        public Criteria andPropertyIdBetween(String value1, String value2) {
            addCriterion("PROPERTY_ID between", value1, value2, "propertyId");
            return (Criteria) this;
        }

        public Criteria andPropertyIdNotBetween(String value1, String value2) {
            addCriterion("PROPERTY_ID not between", value1, value2, "propertyId");
            return (Criteria) this;
        }

        public Criteria andSourceAssetsIsNull() {
            addCriterion("SOURCE_ASSETS is null");
            return (Criteria) this;
        }

        public Criteria andSourceAssetsIsNotNull() {
            addCriterion("SOURCE_ASSETS is not null");
            return (Criteria) this;
        }

        public Criteria andSourceAssetsEqualTo(String value) {
            addCriterion("SOURCE_ASSETS =", value, "sourceAssets");
            return (Criteria) this;
        }

        public Criteria andSourceAssetsNotEqualTo(String value) {
            addCriterion("SOURCE_ASSETS <>", value, "sourceAssets");
            return (Criteria) this;
        }

        public Criteria andSourceAssetsGreaterThan(String value) {
            addCriterion("SOURCE_ASSETS >", value, "sourceAssets");
            return (Criteria) this;
        }

        public Criteria andSourceAssetsGreaterThanOrEqualTo(String value) {
            addCriterion("SOURCE_ASSETS >=", value, "sourceAssets");
            return (Criteria) this;
        }

        public Criteria andSourceAssetsLessThan(String value) {
            addCriterion("SOURCE_ASSETS <", value, "sourceAssets");
            return (Criteria) this;
        }

        public Criteria andSourceAssetsLessThanOrEqualTo(String value) {
            addCriterion("SOURCE_ASSETS <=", value, "sourceAssets");
            return (Criteria) this;
        }

        public Criteria andSourceAssetsLike(String value) {
            addCriterion("SOURCE_ASSETS like", value, "sourceAssets");
            return (Criteria) this;
        }

        public Criteria andSourceAssetsNotLike(String value) {
            addCriterion("SOURCE_ASSETS not like", value, "sourceAssets");
            return (Criteria) this;
        }

        public Criteria andSourceAssetsIn(List<String> values) {
            addCriterion("SOURCE_ASSETS in", values, "sourceAssets");
            return (Criteria) this;
        }

        public Criteria andSourceAssetsNotIn(List<String> values) {
            addCriterion("SOURCE_ASSETS not in", values, "sourceAssets");
            return (Criteria) this;
        }

        public Criteria andSourceAssetsBetween(String value1, String value2) {
            addCriterion("SOURCE_ASSETS between", value1, value2, "sourceAssets");
            return (Criteria) this;
        }

        public Criteria andSourceAssetsNotBetween(String value1, String value2) {
            addCriterion("SOURCE_ASSETS not between", value1, value2, "sourceAssets");
            return (Criteria) this;
        }

        public Criteria andAccountFileIsNull() {
            addCriterion("ACCOUNT_FILE is null");
            return (Criteria) this;
        }

        public Criteria andAccountFileIsNotNull() {
            addCriterion("ACCOUNT_FILE is not null");
            return (Criteria) this;
        }

        public Criteria andAccountFileEqualTo(String value) {
            addCriterion("ACCOUNT_FILE =", value, "accountFile");
            return (Criteria) this;
        }

        public Criteria andAccountFileNotEqualTo(String value) {
            addCriterion("ACCOUNT_FILE <>", value, "accountFile");
            return (Criteria) this;
        }

        public Criteria andAccountFileGreaterThan(String value) {
            addCriterion("ACCOUNT_FILE >", value, "accountFile");
            return (Criteria) this;
        }

        public Criteria andAccountFileGreaterThanOrEqualTo(String value) {
            addCriterion("ACCOUNT_FILE >=", value, "accountFile");
            return (Criteria) this;
        }

        public Criteria andAccountFileLessThan(String value) {
            addCriterion("ACCOUNT_FILE <", value, "accountFile");
            return (Criteria) this;
        }

        public Criteria andAccountFileLessThanOrEqualTo(String value) {
            addCriterion("ACCOUNT_FILE <=", value, "accountFile");
            return (Criteria) this;
        }

        public Criteria andAccountFileLike(String value) {
            addCriterion("ACCOUNT_FILE like", value, "accountFile");
            return (Criteria) this;
        }

        public Criteria andAccountFileNotLike(String value) {
            addCriterion("ACCOUNT_FILE not like", value, "accountFile");
            return (Criteria) this;
        }

        public Criteria andAccountFileIn(List<String> values) {
            addCriterion("ACCOUNT_FILE in", values, "accountFile");
            return (Criteria) this;
        }

        public Criteria andAccountFileNotIn(List<String> values) {
            addCriterion("ACCOUNT_FILE not in", values, "accountFile");
            return (Criteria) this;
        }

        public Criteria andAccountFileBetween(String value1, String value2) {
            addCriterion("ACCOUNT_FILE between", value1, value2, "accountFile");
            return (Criteria) this;
        }

        public Criteria andAccountFileNotBetween(String value1, String value2) {
            addCriterion("ACCOUNT_FILE not between", value1, value2, "accountFile");
            return (Criteria) this;
        }

        public Criteria andCheckDiffIsNull() {
            addCriterion("CHECK_DIFF is null");
            return (Criteria) this;
        }

        public Criteria andCheckDiffIsNotNull() {
            addCriterion("CHECK_DIFF is not null");
            return (Criteria) this;
        }

        public Criteria andCheckDiffEqualTo(String value) {
            addCriterion("CHECK_DIFF =", value, "checkDiff");
            return (Criteria) this;
        }

        public Criteria andCheckDiffNotEqualTo(String value) {
            addCriterion("CHECK_DIFF <>", value, "checkDiff");
            return (Criteria) this;
        }

        public Criteria andCheckDiffGreaterThan(String value) {
            addCriterion("CHECK_DIFF >", value, "checkDiff");
            return (Criteria) this;
        }

        public Criteria andCheckDiffGreaterThanOrEqualTo(String value) {
            addCriterion("CHECK_DIFF >=", value, "checkDiff");
            return (Criteria) this;
        }

        public Criteria andCheckDiffLessThan(String value) {
            addCriterion("CHECK_DIFF <", value, "checkDiff");
            return (Criteria) this;
        }

        public Criteria andCheckDiffLessThanOrEqualTo(String value) {
            addCriterion("CHECK_DIFF <=", value, "checkDiff");
            return (Criteria) this;
        }

        public Criteria andCheckDiffLike(String value) {
            addCriterion("CHECK_DIFF like", value, "checkDiff");
            return (Criteria) this;
        }

        public Criteria andCheckDiffNotLike(String value) {
            addCriterion("CHECK_DIFF not like", value, "checkDiff");
            return (Criteria) this;
        }

        public Criteria andCheckDiffIn(List<String> values) {
            addCriterion("CHECK_DIFF in", values, "checkDiff");
            return (Criteria) this;
        }

        public Criteria andCheckDiffNotIn(List<String> values) {
            addCriterion("CHECK_DIFF not in", values, "checkDiff");
            return (Criteria) this;
        }

        public Criteria andCheckDiffBetween(String value1, String value2) {
            addCriterion("CHECK_DIFF between", value1, value2, "checkDiff");
            return (Criteria) this;
        }

        public Criteria andCheckDiffNotBetween(String value1, String value2) {
            addCriterion("CHECK_DIFF not between", value1, value2, "checkDiff");
            return (Criteria) this;
        }

        public Criteria andTechnicalParmIsNull() {
            addCriterion("TECHNICAL_PARM is null");
            return (Criteria) this;
        }

        public Criteria andTechnicalParmIsNotNull() {
            addCriterion("TECHNICAL_PARM is not null");
            return (Criteria) this;
        }

        public Criteria andTechnicalParmEqualTo(String value) {
            addCriterion("TECHNICAL_PARM =", value, "technicalParm");
            return (Criteria) this;
        }

        public Criteria andTechnicalParmNotEqualTo(String value) {
            addCriterion("TECHNICAL_PARM <>", value, "technicalParm");
            return (Criteria) this;
        }

        public Criteria andTechnicalParmGreaterThan(String value) {
            addCriterion("TECHNICAL_PARM >", value, "technicalParm");
            return (Criteria) this;
        }

        public Criteria andTechnicalParmGreaterThanOrEqualTo(String value) {
            addCriterion("TECHNICAL_PARM >=", value, "technicalParm");
            return (Criteria) this;
        }

        public Criteria andTechnicalParmLessThan(String value) {
            addCriterion("TECHNICAL_PARM <", value, "technicalParm");
            return (Criteria) this;
        }

        public Criteria andTechnicalParmLessThanOrEqualTo(String value) {
            addCriterion("TECHNICAL_PARM <=", value, "technicalParm");
            return (Criteria) this;
        }

        public Criteria andTechnicalParmLike(String value) {
            addCriterion("TECHNICAL_PARM like", value, "technicalParm");
            return (Criteria) this;
        }

        public Criteria andTechnicalParmNotLike(String value) {
            addCriterion("TECHNICAL_PARM not like", value, "technicalParm");
            return (Criteria) this;
        }

        public Criteria andTechnicalParmIn(List<String> values) {
            addCriterion("TECHNICAL_PARM in", values, "technicalParm");
            return (Criteria) this;
        }

        public Criteria andTechnicalParmNotIn(List<String> values) {
            addCriterion("TECHNICAL_PARM not in", values, "technicalParm");
            return (Criteria) this;
        }

        public Criteria andTechnicalParmBetween(String value1, String value2) {
            addCriterion("TECHNICAL_PARM between", value1, value2, "technicalParm");
            return (Criteria) this;
        }

        public Criteria andTechnicalParmNotBetween(String value1, String value2) {
            addCriterion("TECHNICAL_PARM not between", value1, value2, "technicalParm");
            return (Criteria) this;
        }

        public Criteria andSensitivityIsNull() {
            addCriterion("SENSITIVITY is null");
            return (Criteria) this;
        }

        public Criteria andSensitivityIsNotNull() {
            addCriterion("SENSITIVITY is not null");
            return (Criteria) this;
        }

        public Criteria andSensitivityEqualTo(String value) {
            addCriterion("SENSITIVITY =", value, "sensitivity");
            return (Criteria) this;
        }

        public Criteria andSensitivityNotEqualTo(String value) {
            addCriterion("SENSITIVITY <>", value, "sensitivity");
            return (Criteria) this;
        }

        public Criteria andSensitivityGreaterThan(String value) {
            addCriterion("SENSITIVITY >", value, "sensitivity");
            return (Criteria) this;
        }

        public Criteria andSensitivityGreaterThanOrEqualTo(String value) {
            addCriterion("SENSITIVITY >=", value, "sensitivity");
            return (Criteria) this;
        }

        public Criteria andSensitivityLessThan(String value) {
            addCriterion("SENSITIVITY <", value, "sensitivity");
            return (Criteria) this;
        }

        public Criteria andSensitivityLessThanOrEqualTo(String value) {
            addCriterion("SENSITIVITY <=", value, "sensitivity");
            return (Criteria) this;
        }

        public Criteria andSensitivityLike(String value) {
            addCriterion("SENSITIVITY like", value, "sensitivity");
            return (Criteria) this;
        }

        public Criteria andSensitivityNotLike(String value) {
            addCriterion("SENSITIVITY not like", value, "sensitivity");
            return (Criteria) this;
        }

        public Criteria andSensitivityIn(List<String> values) {
            addCriterion("SENSITIVITY in", values, "sensitivity");
            return (Criteria) this;
        }

        public Criteria andSensitivityNotIn(List<String> values) {
            addCriterion("SENSITIVITY not in", values, "sensitivity");
            return (Criteria) this;
        }

        public Criteria andSensitivityBetween(String value1, String value2) {
            addCriterion("SENSITIVITY between", value1, value2, "sensitivity");
            return (Criteria) this;
        }

        public Criteria andSensitivityNotBetween(String value1, String value2) {
            addCriterion("SENSITIVITY not between", value1, value2, "sensitivity");
            return (Criteria) this;
        }

        public Criteria andPhyQuantiIdIsNull() {
            addCriterion("PHY_QUANTI_ID is null");
            return (Criteria) this;
        }

        public Criteria andPhyQuantiIdIsNotNull() {
            addCriterion("PHY_QUANTI_ID is not null");
            return (Criteria) this;
        }

        public Criteria andPhyQuantiIdEqualTo(String value) {
            addCriterion("PHY_QUANTI_ID =", value, "phyQuantiId");
            return (Criteria) this;
        }

        public Criteria andPhyQuantiIdNotEqualTo(String value) {
            addCriterion("PHY_QUANTI_ID <>", value, "phyQuantiId");
            return (Criteria) this;
        }

        public Criteria andPhyQuantiIdGreaterThan(String value) {
            addCriterion("PHY_QUANTI_ID >", value, "phyQuantiId");
            return (Criteria) this;
        }

        public Criteria andPhyQuantiIdGreaterThanOrEqualTo(String value) {
            addCriterion("PHY_QUANTI_ID >=", value, "phyQuantiId");
            return (Criteria) this;
        }

        public Criteria andPhyQuantiIdLessThan(String value) {
            addCriterion("PHY_QUANTI_ID <", value, "phyQuantiId");
            return (Criteria) this;
        }

        public Criteria andPhyQuantiIdLessThanOrEqualTo(String value) {
            addCriterion("PHY_QUANTI_ID <=", value, "phyQuantiId");
            return (Criteria) this;
        }

        public Criteria andPhyQuantiIdLike(String value) {
            addCriterion("PHY_QUANTI_ID like", value, "phyQuantiId");
            return (Criteria) this;
        }

        public Criteria andPhyQuantiIdNotLike(String value) {
            addCriterion("PHY_QUANTI_ID not like", value, "phyQuantiId");
            return (Criteria) this;
        }

        public Criteria andPhyQuantiIdIn(List<String> values) {
            addCriterion("PHY_QUANTI_ID in", values, "phyQuantiId");
            return (Criteria) this;
        }

        public Criteria andPhyQuantiIdNotIn(List<String> values) {
            addCriterion("PHY_QUANTI_ID not in", values, "phyQuantiId");
            return (Criteria) this;
        }

        public Criteria andPhyQuantiIdBetween(String value1, String value2) {
            addCriterion("PHY_QUANTI_ID between", value1, value2, "phyQuantiId");
            return (Criteria) this;
        }

        public Criteria andPhyQuantiIdNotBetween(String value1, String value2) {
            addCriterion("PHY_QUANTI_ID not between", value1, value2, "phyQuantiId");
            return (Criteria) this;
        }

        public Criteria andCouplingIdIsNull() {
            addCriterion("COUPLING_ID is null");
            return (Criteria) this;
        }

        public Criteria andCouplingIdIsNotNull() {
            addCriterion("COUPLING_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCouplingIdEqualTo(String value) {
            addCriterion("COUPLING_ID =", value, "couplingId");
            return (Criteria) this;
        }

        public Criteria andCouplingIdNotEqualTo(String value) {
            addCriterion("COUPLING_ID <>", value, "couplingId");
            return (Criteria) this;
        }

        public Criteria andCouplingIdGreaterThan(String value) {
            addCriterion("COUPLING_ID >", value, "couplingId");
            return (Criteria) this;
        }

        public Criteria andCouplingIdGreaterThanOrEqualTo(String value) {
            addCriterion("COUPLING_ID >=", value, "couplingId");
            return (Criteria) this;
        }

        public Criteria andCouplingIdLessThan(String value) {
            addCriterion("COUPLING_ID <", value, "couplingId");
            return (Criteria) this;
        }

        public Criteria andCouplingIdLessThanOrEqualTo(String value) {
            addCriterion("COUPLING_ID <=", value, "couplingId");
            return (Criteria) this;
        }

        public Criteria andCouplingIdLike(String value) {
            addCriterion("COUPLING_ID like", value, "couplingId");
            return (Criteria) this;
        }

        public Criteria andCouplingIdNotLike(String value) {
            addCriterion("COUPLING_ID not like", value, "couplingId");
            return (Criteria) this;
        }

        public Criteria andCouplingIdIn(List<String> values) {
            addCriterion("COUPLING_ID in", values, "couplingId");
            return (Criteria) this;
        }

        public Criteria andCouplingIdNotIn(List<String> values) {
            addCriterion("COUPLING_ID not in", values, "couplingId");
            return (Criteria) this;
        }

        public Criteria andCouplingIdBetween(String value1, String value2) {
            addCriterion("COUPLING_ID between", value1, value2, "couplingId");
            return (Criteria) this;
        }

        public Criteria andCouplingIdNotBetween(String value1, String value2) {
            addCriterion("COUPLING_ID not between", value1, value2, "couplingId");
            return (Criteria) this;
        }

        public Criteria andDirectionIdIsNull() {
            addCriterion("DIRECTION_ID is null");
            return (Criteria) this;
        }

        public Criteria andDirectionIdIsNotNull() {
            addCriterion("DIRECTION_ID is not null");
            return (Criteria) this;
        }

        public Criteria andDirectionIdEqualTo(String value) {
            addCriterion("DIRECTION_ID =", value, "directionId");
            return (Criteria) this;
        }

        public Criteria andDirectionIdNotEqualTo(String value) {
            addCriterion("DIRECTION_ID <>", value, "directionId");
            return (Criteria) this;
        }

        public Criteria andDirectionIdGreaterThan(String value) {
            addCriterion("DIRECTION_ID >", value, "directionId");
            return (Criteria) this;
        }

        public Criteria andDirectionIdGreaterThanOrEqualTo(String value) {
            addCriterion("DIRECTION_ID >=", value, "directionId");
            return (Criteria) this;
        }

        public Criteria andDirectionIdLessThan(String value) {
            addCriterion("DIRECTION_ID <", value, "directionId");
            return (Criteria) this;
        }

        public Criteria andDirectionIdLessThanOrEqualTo(String value) {
            addCriterion("DIRECTION_ID <=", value, "directionId");
            return (Criteria) this;
        }

        public Criteria andDirectionIdLike(String value) {
            addCriterion("DIRECTION_ID like", value, "directionId");
            return (Criteria) this;
        }

        public Criteria andDirectionIdNotLike(String value) {
            addCriterion("DIRECTION_ID not like", value, "directionId");
            return (Criteria) this;
        }

        public Criteria andDirectionIdIn(List<String> values) {
            addCriterion("DIRECTION_ID in", values, "directionId");
            return (Criteria) this;
        }

        public Criteria andDirectionIdNotIn(List<String> values) {
            addCriterion("DIRECTION_ID not in", values, "directionId");
            return (Criteria) this;
        }

        public Criteria andDirectionIdBetween(String value1, String value2) {
            addCriterion("DIRECTION_ID between", value1, value2, "directionId");
            return (Criteria) this;
        }

        public Criteria andDirectionIdNotBetween(String value1, String value2) {
            addCriterion("DIRECTION_ID not between", value1, value2, "directionId");
            return (Criteria) this;
        }

        public Criteria andCloudSnIsNull() {
            addCriterion("CLOUD_SN is null");
            return (Criteria) this;
        }

        public Criteria andCloudSnIsNotNull() {
            addCriterion("CLOUD_SN is not null");
            return (Criteria) this;
        }

        public Criteria andCloudSnEqualTo(String value) {
            addCriterion("CLOUD_SN =", value, "cloudSn");
            return (Criteria) this;
        }

        public Criteria andCloudSnNotEqualTo(String value) {
            addCriterion("CLOUD_SN <>", value, "cloudSn");
            return (Criteria) this;
        }

        public Criteria andCloudSnGreaterThan(String value) {
            addCriterion("CLOUD_SN >", value, "cloudSn");
            return (Criteria) this;
        }

        public Criteria andCloudSnGreaterThanOrEqualTo(String value) {
            addCriterion("CLOUD_SN >=", value, "cloudSn");
            return (Criteria) this;
        }

        public Criteria andCloudSnLessThan(String value) {
            addCriterion("CLOUD_SN <", value, "cloudSn");
            return (Criteria) this;
        }

        public Criteria andCloudSnLessThanOrEqualTo(String value) {
            addCriterion("CLOUD_SN <=", value, "cloudSn");
            return (Criteria) this;
        }

        public Criteria andCloudSnLike(String value) {
            addCriterion("CLOUD_SN like", value, "cloudSn");
            return (Criteria) this;
        }

        public Criteria andCloudSnNotLike(String value) {
            addCriterion("CLOUD_SN not like", value, "cloudSn");
            return (Criteria) this;
        }

        public Criteria andCloudSnIn(List<String> values) {
            addCriterion("CLOUD_SN in", values, "cloudSn");
            return (Criteria) this;
        }

        public Criteria andCloudSnNotIn(List<String> values) {
            addCriterion("CLOUD_SN not in", values, "cloudSn");
            return (Criteria) this;
        }

        public Criteria andCloudSnBetween(String value1, String value2) {
            addCriterion("CLOUD_SN between", value1, value2, "cloudSn");
            return (Criteria) this;
        }

        public Criteria andCloudSnNotBetween(String value1, String value2) {
            addCriterion("CLOUD_SN not between", value1, value2, "cloudSn");
            return (Criteria) this;
        }

        public Criteria andCustodianIsNull() {
            addCriterion("CUSTODIAN is null");
            return (Criteria) this;
        }

        public Criteria andCustodianIsNotNull() {
            addCriterion("CUSTODIAN is not null");
            return (Criteria) this;
        }

        public Criteria andCustodianEqualTo(String value) {
            addCriterion("CUSTODIAN =", value, "custodian");
            return (Criteria) this;
        }

        public Criteria andCustodianNotEqualTo(String value) {
            addCriterion("CUSTODIAN <>", value, "custodian");
            return (Criteria) this;
        }

        public Criteria andCustodianGreaterThan(String value) {
            addCriterion("CUSTODIAN >", value, "custodian");
            return (Criteria) this;
        }

        public Criteria andCustodianGreaterThanOrEqualTo(String value) {
            addCriterion("CUSTODIAN >=", value, "custodian");
            return (Criteria) this;
        }

        public Criteria andCustodianLessThan(String value) {
            addCriterion("CUSTODIAN <", value, "custodian");
            return (Criteria) this;
        }

        public Criteria andCustodianLessThanOrEqualTo(String value) {
            addCriterion("CUSTODIAN <=", value, "custodian");
            return (Criteria) this;
        }

        public Criteria andCustodianLike(String value) {
            addCriterion("CUSTODIAN like", value, "custodian");
            return (Criteria) this;
        }

        public Criteria andCustodianNotLike(String value) {
            addCriterion("CUSTODIAN not like", value, "custodian");
            return (Criteria) this;
        }

        public Criteria andCustodianIn(List<String> values) {
            addCriterion("CUSTODIAN in", values, "custodian");
            return (Criteria) this;
        }

        public Criteria andCustodianNotIn(List<String> values) {
            addCriterion("CUSTODIAN not in", values, "custodian");
            return (Criteria) this;
        }

        public Criteria andCustodianBetween(String value1, String value2) {
            addCriterion("CUSTODIAN between", value1, value2, "custodian");
            return (Criteria) this;
        }

        public Criteria andCustodianNotBetween(String value1, String value2) {
            addCriterion("CUSTODIAN not between", value1, value2, "custodian");
            return (Criteria) this;
        }

        public Criteria andStandMateYnIsNull() {
            addCriterion("STAND_MATE_YN is null");
            return (Criteria) this;
        }

        public Criteria andStandMateYnIsNotNull() {
            addCriterion("STAND_MATE_YN is not null");
            return (Criteria) this;
        }

        public Criteria andStandMateYnEqualTo(String value) {
            addCriterion("STAND_MATE_YN =", value, "standMateYn");
            return (Criteria) this;
        }

        public Criteria andStandMateYnNotEqualTo(String value) {
            addCriterion("STAND_MATE_YN <>", value, "standMateYn");
            return (Criteria) this;
        }

        public Criteria andStandMateYnGreaterThan(String value) {
            addCriterion("STAND_MATE_YN >", value, "standMateYn");
            return (Criteria) this;
        }

        public Criteria andStandMateYnGreaterThanOrEqualTo(String value) {
            addCriterion("STAND_MATE_YN >=", value, "standMateYn");
            return (Criteria) this;
        }

        public Criteria andStandMateYnLessThan(String value) {
            addCriterion("STAND_MATE_YN <", value, "standMateYn");
            return (Criteria) this;
        }

        public Criteria andStandMateYnLessThanOrEqualTo(String value) {
            addCriterion("STAND_MATE_YN <=", value, "standMateYn");
            return (Criteria) this;
        }

        public Criteria andStandMateYnLike(String value) {
            addCriterion("STAND_MATE_YN like", value, "standMateYn");
            return (Criteria) this;
        }

        public Criteria andStandMateYnNotLike(String value) {
            addCriterion("STAND_MATE_YN not like", value, "standMateYn");
            return (Criteria) this;
        }

        public Criteria andStandMateYnIn(List<String> values) {
            addCriterion("STAND_MATE_YN in", values, "standMateYn");
            return (Criteria) this;
        }

        public Criteria andStandMateYnNotIn(List<String> values) {
            addCriterion("STAND_MATE_YN not in", values, "standMateYn");
            return (Criteria) this;
        }

        public Criteria andStandMateYnBetween(String value1, String value2) {
            addCriterion("STAND_MATE_YN between", value1, value2, "standMateYn");
            return (Criteria) this;
        }

        public Criteria andStandMateYnNotBetween(String value1, String value2) {
            addCriterion("STAND_MATE_YN not between", value1, value2, "standMateYn");
            return (Criteria) this;
        }

        public Criteria andMemoIsNull() {
            addCriterion("MEMO is null");
            return (Criteria) this;
        }

        public Criteria andMemoIsNotNull() {
            addCriterion("MEMO is not null");
            return (Criteria) this;
        }

        public Criteria andMemoEqualTo(String value) {
            addCriterion("MEMO =", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotEqualTo(String value) {
            addCriterion("MEMO <>", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoGreaterThan(String value) {
            addCriterion("MEMO >", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoGreaterThanOrEqualTo(String value) {
            addCriterion("MEMO >=", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoLessThan(String value) {
            addCriterion("MEMO <", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoLessThanOrEqualTo(String value) {
            addCriterion("MEMO <=", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoLike(String value) {
            addCriterion("MEMO like", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotLike(String value) {
            addCriterion("MEMO not like", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoIn(List<String> values) {
            addCriterion("MEMO in", values, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotIn(List<String> values) {
            addCriterion("MEMO not in", values, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoBetween(String value1, String value2) {
            addCriterion("MEMO between", value1, value2, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotBetween(String value1, String value2) {
            addCriterion("MEMO not between", value1, value2, "memo");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table lims_equipment
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table lims_equipment
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}