package com.xoa.model.equipment;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class LimsEquipEventsPlanExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lims_equip_events_plan
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lims_equip_events_plan
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lims_equip_events_plan
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_equip_events_plan
     *
     * @mbggenerated
     */
    public LimsEquipEventsPlanExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_equip_events_plan
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_equip_events_plan
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_equip_events_plan
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_equip_events_plan
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_equip_events_plan
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_equip_events_plan
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_equip_events_plan
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_equip_events_plan
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_equip_events_plan
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_equip_events_plan
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table lims_equip_events_plan
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andEventIdIsNull() {
            addCriterion("EVENT_ID is null");
            return (Criteria) this;
        }

        public Criteria andEventIdIsNotNull() {
            addCriterion("EVENT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andEventIdEqualTo(Integer value) {
            addCriterion("EVENT_ID =", value, "eventId");
            return (Criteria) this;
        }

        public Criteria andEventIdNotEqualTo(Integer value) {
            addCriterion("EVENT_ID <>", value, "eventId");
            return (Criteria) this;
        }

        public Criteria andEventIdGreaterThan(Integer value) {
            addCriterion("EVENT_ID >", value, "eventId");
            return (Criteria) this;
        }

        public Criteria andEventIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("EVENT_ID >=", value, "eventId");
            return (Criteria) this;
        }

        public Criteria andEventIdLessThan(Integer value) {
            addCriterion("EVENT_ID <", value, "eventId");
            return (Criteria) this;
        }

        public Criteria andEventIdLessThanOrEqualTo(Integer value) {
            addCriterion("EVENT_ID <=", value, "eventId");
            return (Criteria) this;
        }

        public Criteria andEventIdIn(List<Integer> values) {
            addCriterion("EVENT_ID in", values, "eventId");
            return (Criteria) this;
        }

        public Criteria andEventIdNotIn(List<Integer> values) {
            addCriterion("EVENT_ID not in", values, "eventId");
            return (Criteria) this;
        }

        public Criteria andEventIdBetween(Integer value1, Integer value2) {
            addCriterion("EVENT_ID between", value1, value2, "eventId");
            return (Criteria) this;
        }

        public Criteria andEventIdNotBetween(Integer value1, Integer value2) {
            addCriterion("EVENT_ID not between", value1, value2, "eventId");
            return (Criteria) this;
        }

        public Criteria andEquipEventTypeIsNull() {
            addCriterion("EQUIP_EVENT_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andEquipEventTypeIsNotNull() {
            addCriterion("EQUIP_EVENT_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andEquipEventTypeEqualTo(String value) {
            addCriterion("EQUIP_EVENT_TYPE =", value, "equipEventType");
            return (Criteria) this;
        }

        public Criteria andEquipEventTypeNotEqualTo(String value) {
            addCriterion("EQUIP_EVENT_TYPE <>", value, "equipEventType");
            return (Criteria) this;
        }

        public Criteria andEquipEventTypeGreaterThan(String value) {
            addCriterion("EQUIP_EVENT_TYPE >", value, "equipEventType");
            return (Criteria) this;
        }

        public Criteria andEquipEventTypeGreaterThanOrEqualTo(String value) {
            addCriterion("EQUIP_EVENT_TYPE >=", value, "equipEventType");
            return (Criteria) this;
        }

        public Criteria andEquipEventTypeLessThan(String value) {
            addCriterion("EQUIP_EVENT_TYPE <", value, "equipEventType");
            return (Criteria) this;
        }

        public Criteria andEquipEventTypeLessThanOrEqualTo(String value) {
            addCriterion("EQUIP_EVENT_TYPE <=", value, "equipEventType");
            return (Criteria) this;
        }

        public Criteria andEquipEventTypeLike(String value) {
            addCriterion("EQUIP_EVENT_TYPE like", value, "equipEventType");
            return (Criteria) this;
        }

        public Criteria andEquipEventTypeNotLike(String value) {
            addCriterion("EQUIP_EVENT_TYPE not like", value, "equipEventType");
            return (Criteria) this;
        }

        public Criteria andEquipEventTypeIn(List<String> values) {
            addCriterion("EQUIP_EVENT_TYPE in", values, "equipEventType");
            return (Criteria) this;
        }

        public Criteria andEquipEventTypeNotIn(List<String> values) {
            addCriterion("EQUIP_EVENT_TYPE not in", values, "equipEventType");
            return (Criteria) this;
        }

        public Criteria andEquipEventTypeBetween(String value1, String value2) {
            addCriterion("EQUIP_EVENT_TYPE between", value1, value2, "equipEventType");
            return (Criteria) this;
        }

        public Criteria andEquipEventTypeNotBetween(String value1, String value2) {
            addCriterion("EQUIP_EVENT_TYPE not between", value1, value2, "equipEventType");
            return (Criteria) this;
        }

        public Criteria andEquipIdIsNull() {
            addCriterion("EQUIP_ID is null");
            return (Criteria) this;
        }

        public Criteria andEquipIdIsNotNull() {
            addCriterion("EQUIP_ID is not null");
            return (Criteria) this;
        }

        public Criteria andEquipIdEqualTo(Integer value) {
            addCriterion("EQUIP_ID =", value, "equipId");
            return (Criteria) this;
        }

        public Criteria andEquipIdNotEqualTo(Integer value) {
            addCriterion("EQUIP_ID <>", value, "equipId");
            return (Criteria) this;
        }

        public Criteria andEquipIdGreaterThan(Integer value) {
            addCriterion("EQUIP_ID >", value, "equipId");
            return (Criteria) this;
        }

        public Criteria andEquipIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("EQUIP_ID >=", value, "equipId");
            return (Criteria) this;
        }

        public Criteria andEquipIdLessThan(Integer value) {
            addCriterion("EQUIP_ID <", value, "equipId");
            return (Criteria) this;
        }

        public Criteria andEquipIdLessThanOrEqualTo(Integer value) {
            addCriterion("EQUIP_ID <=", value, "equipId");
            return (Criteria) this;
        }

        public Criteria andEquipIdIn(List<Integer> values) {
            addCriterion("EQUIP_ID in", values, "equipId");
            return (Criteria) this;
        }

        public Criteria andEquipIdNotIn(List<Integer> values) {
            addCriterion("EQUIP_ID not in", values, "equipId");
            return (Criteria) this;
        }

        public Criteria andEquipIdBetween(Integer value1, Integer value2) {
            addCriterion("EQUIP_ID between", value1, value2, "equipId");
            return (Criteria) this;
        }

        public Criteria andEquipIdNotBetween(Integer value1, Integer value2) {
            addCriterion("EQUIP_ID not between", value1, value2, "equipId");
            return (Criteria) this;
        }

        public Criteria andEquipNameIsNull() {
            addCriterion("EQUIP_NAME is null");
            return (Criteria) this;
        }

        public Criteria andEquipNameIsNotNull() {
            addCriterion("EQUIP_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andEquipNameEqualTo(String value) {
            addCriterion("EQUIP_NAME =", value, "equipName");
            return (Criteria) this;
        }

        public Criteria andEquipNameNotEqualTo(String value) {
            addCriterion("EQUIP_NAME <>", value, "equipName");
            return (Criteria) this;
        }

        public Criteria andEquipNameGreaterThan(String value) {
            addCriterion("EQUIP_NAME >", value, "equipName");
            return (Criteria) this;
        }

        public Criteria andEquipNameGreaterThanOrEqualTo(String value) {
            addCriterion("EQUIP_NAME >=", value, "equipName");
            return (Criteria) this;
        }

        public Criteria andEquipNameLessThan(String value) {
            addCriterion("EQUIP_NAME <", value, "equipName");
            return (Criteria) this;
        }

        public Criteria andEquipNameLessThanOrEqualTo(String value) {
            addCriterion("EQUIP_NAME <=", value, "equipName");
            return (Criteria) this;
        }

        public Criteria andEquipNameLike(String value) {
            addCriterion("EQUIP_NAME like", value, "equipName");
            return (Criteria) this;
        }

        public Criteria andEquipNameNotLike(String value) {
            addCriterion("EQUIP_NAME not like", value, "equipName");
            return (Criteria) this;
        }

        public Criteria andEquipNameIn(List<String> values) {
            addCriterion("EQUIP_NAME in", values, "equipName");
            return (Criteria) this;
        }

        public Criteria andEquipNameNotIn(List<String> values) {
            addCriterion("EQUIP_NAME not in", values, "equipName");
            return (Criteria) this;
        }

        public Criteria andEquipNameBetween(String value1, String value2) {
            addCriterion("EQUIP_NAME between", value1, value2, "equipName");
            return (Criteria) this;
        }

        public Criteria andEquipNameNotBetween(String value1, String value2) {
            addCriterion("EQUIP_NAME not between", value1, value2, "equipName");
            return (Criteria) this;
        }

        public Criteria andEquipStatusIsNull() {
            addCriterion("EQUIP_STATUS is null");
            return (Criteria) this;
        }

        public Criteria andEquipStatusIsNotNull() {
            addCriterion("EQUIP_STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andEquipStatusEqualTo(String value) {
            addCriterion("EQUIP_STATUS =", value, "equipStatus");
            return (Criteria) this;
        }

        public Criteria andEquipStatusNotEqualTo(String value) {
            addCriterion("EQUIP_STATUS <>", value, "equipStatus");
            return (Criteria) this;
        }

        public Criteria andEquipStatusGreaterThan(String value) {
            addCriterion("EQUIP_STATUS >", value, "equipStatus");
            return (Criteria) this;
        }

        public Criteria andEquipStatusGreaterThanOrEqualTo(String value) {
            addCriterion("EQUIP_STATUS >=", value, "equipStatus");
            return (Criteria) this;
        }

        public Criteria andEquipStatusLessThan(String value) {
            addCriterion("EQUIP_STATUS <", value, "equipStatus");
            return (Criteria) this;
        }

        public Criteria andEquipStatusLessThanOrEqualTo(String value) {
            addCriterion("EQUIP_STATUS <=", value, "equipStatus");
            return (Criteria) this;
        }

        public Criteria andEquipStatusLike(String value) {
            addCriterion("EQUIP_STATUS like", value, "equipStatus");
            return (Criteria) this;
        }

        public Criteria andEquipStatusNotLike(String value) {
            addCriterion("EQUIP_STATUS not like", value, "equipStatus");
            return (Criteria) this;
        }

        public Criteria andEquipStatusIn(List<String> values) {
            addCriterion("EQUIP_STATUS in", values, "equipStatus");
            return (Criteria) this;
        }

        public Criteria andEquipStatusNotIn(List<String> values) {
            addCriterion("EQUIP_STATUS not in", values, "equipStatus");
            return (Criteria) this;
        }

        public Criteria andEquipStatusBetween(String value1, String value2) {
            addCriterion("EQUIP_STATUS between", value1, value2, "equipStatus");
            return (Criteria) this;
        }

        public Criteria andEquipStatusNotBetween(String value1, String value2) {
            addCriterion("EQUIP_STATUS not between", value1, value2, "equipStatus");
            return (Criteria) this;
        }

        public Criteria andEquipNoIsNull() {
            addCriterion("EQUIP_NO is null");
            return (Criteria) this;
        }

        public Criteria andEquipNoIsNotNull() {
            addCriterion("EQUIP_NO is not null");
            return (Criteria) this;
        }

        public Criteria andEquipNoEqualTo(String value) {
            addCriterion("EQUIP_NO =", value, "equipNo");
            return (Criteria) this;
        }

        public Criteria andEquipNoNotEqualTo(String value) {
            addCriterion("EQUIP_NO <>", value, "equipNo");
            return (Criteria) this;
        }

        public Criteria andEquipNoGreaterThan(String value) {
            addCriterion("EQUIP_NO >", value, "equipNo");
            return (Criteria) this;
        }

        public Criteria andEquipNoGreaterThanOrEqualTo(String value) {
            addCriterion("EQUIP_NO >=", value, "equipNo");
            return (Criteria) this;
        }

        public Criteria andEquipNoLessThan(String value) {
            addCriterion("EQUIP_NO <", value, "equipNo");
            return (Criteria) this;
        }

        public Criteria andEquipNoLessThanOrEqualTo(String value) {
            addCriterion("EQUIP_NO <=", value, "equipNo");
            return (Criteria) this;
        }

        public Criteria andEquipNoLike(String value) {
            addCriterion("EQUIP_NO like", value, "equipNo");
            return (Criteria) this;
        }

        public Criteria andEquipNoNotLike(String value) {
            addCriterion("EQUIP_NO not like", value, "equipNo");
            return (Criteria) this;
        }

        public Criteria andEquipNoIn(List<String> values) {
            addCriterion("EQUIP_NO in", values, "equipNo");
            return (Criteria) this;
        }

        public Criteria andEquipNoNotIn(List<String> values) {
            addCriterion("EQUIP_NO not in", values, "equipNo");
            return (Criteria) this;
        }

        public Criteria andEquipNoBetween(String value1, String value2) {
            addCriterion("EQUIP_NO between", value1, value2, "equipNo");
            return (Criteria) this;
        }

        public Criteria andEquipNoNotBetween(String value1, String value2) {
            addCriterion("EQUIP_NO not between", value1, value2, "equipNo");
            return (Criteria) this;
        }

        public Criteria andFactoryNoIsNull() {
            addCriterion("FACTORY_NO is null");
            return (Criteria) this;
        }

        public Criteria andFactoryNoIsNotNull() {
            addCriterion("FACTORY_NO is not null");
            return (Criteria) this;
        }

        public Criteria andFactoryNoEqualTo(String value) {
            addCriterion("FACTORY_NO =", value, "factoryNo");
            return (Criteria) this;
        }

        public Criteria andFactoryNoNotEqualTo(String value) {
            addCriterion("FACTORY_NO <>", value, "factoryNo");
            return (Criteria) this;
        }

        public Criteria andFactoryNoGreaterThan(String value) {
            addCriterion("FACTORY_NO >", value, "factoryNo");
            return (Criteria) this;
        }

        public Criteria andFactoryNoGreaterThanOrEqualTo(String value) {
            addCriterion("FACTORY_NO >=", value, "factoryNo");
            return (Criteria) this;
        }

        public Criteria andFactoryNoLessThan(String value) {
            addCriterion("FACTORY_NO <", value, "factoryNo");
            return (Criteria) this;
        }

        public Criteria andFactoryNoLessThanOrEqualTo(String value) {
            addCriterion("FACTORY_NO <=", value, "factoryNo");
            return (Criteria) this;
        }

        public Criteria andFactoryNoLike(String value) {
            addCriterion("FACTORY_NO like", value, "factoryNo");
            return (Criteria) this;
        }

        public Criteria andFactoryNoNotLike(String value) {
            addCriterion("FACTORY_NO not like", value, "factoryNo");
            return (Criteria) this;
        }

        public Criteria andFactoryNoIn(List<String> values) {
            addCriterion("FACTORY_NO in", values, "factoryNo");
            return (Criteria) this;
        }

        public Criteria andFactoryNoNotIn(List<String> values) {
            addCriterion("FACTORY_NO not in", values, "factoryNo");
            return (Criteria) this;
        }

        public Criteria andFactoryNoBetween(String value1, String value2) {
            addCriterion("FACTORY_NO between", value1, value2, "factoryNo");
            return (Criteria) this;
        }

        public Criteria andFactoryNoNotBetween(String value1, String value2) {
            addCriterion("FACTORY_NO not between", value1, value2, "factoryNo");
            return (Criteria) this;
        }

        public Criteria andModelNoIsNull() {
            addCriterion("MODEL_NO is null");
            return (Criteria) this;
        }

        public Criteria andModelNoIsNotNull() {
            addCriterion("MODEL_NO is not null");
            return (Criteria) this;
        }

        public Criteria andModelNoEqualTo(String value) {
            addCriterion("MODEL_NO =", value, "modelNo");
            return (Criteria) this;
        }

        public Criteria andModelNoNotEqualTo(String value) {
            addCriterion("MODEL_NO <>", value, "modelNo");
            return (Criteria) this;
        }

        public Criteria andModelNoGreaterThan(String value) {
            addCriterion("MODEL_NO >", value, "modelNo");
            return (Criteria) this;
        }

        public Criteria andModelNoGreaterThanOrEqualTo(String value) {
            addCriterion("MODEL_NO >=", value, "modelNo");
            return (Criteria) this;
        }

        public Criteria andModelNoLessThan(String value) {
            addCriterion("MODEL_NO <", value, "modelNo");
            return (Criteria) this;
        }

        public Criteria andModelNoLessThanOrEqualTo(String value) {
            addCriterion("MODEL_NO <=", value, "modelNo");
            return (Criteria) this;
        }

        public Criteria andModelNoLike(String value) {
            addCriterion("MODEL_NO like", value, "modelNo");
            return (Criteria) this;
        }

        public Criteria andModelNoNotLike(String value) {
            addCriterion("MODEL_NO not like", value, "modelNo");
            return (Criteria) this;
        }

        public Criteria andModelNoIn(List<String> values) {
            addCriterion("MODEL_NO in", values, "modelNo");
            return (Criteria) this;
        }

        public Criteria andModelNoNotIn(List<String> values) {
            addCriterion("MODEL_NO not in", values, "modelNo");
            return (Criteria) this;
        }

        public Criteria andModelNoBetween(String value1, String value2) {
            addCriterion("MODEL_NO between", value1, value2, "modelNo");
            return (Criteria) this;
        }

        public Criteria andModelNoNotBetween(String value1, String value2) {
            addCriterion("MODEL_NO not between", value1, value2, "modelNo");
            return (Criteria) this;
        }

        public Criteria andFrequencyIsNull() {
            addCriterion("FREQUENCY is null");
            return (Criteria) this;
        }

        public Criteria andFrequencyIsNotNull() {
            addCriterion("FREQUENCY is not null");
            return (Criteria) this;
        }

        public Criteria andFrequencyEqualTo(String value) {
            addCriterion("FREQUENCY =", value, "frequency");
            return (Criteria) this;
        }

        public Criteria andFrequencyNotEqualTo(String value) {
            addCriterion("FREQUENCY <>", value, "frequency");
            return (Criteria) this;
        }

        public Criteria andFrequencyGreaterThan(String value) {
            addCriterion("FREQUENCY >", value, "frequency");
            return (Criteria) this;
        }

        public Criteria andFrequencyGreaterThanOrEqualTo(String value) {
            addCriterion("FREQUENCY >=", value, "frequency");
            return (Criteria) this;
        }

        public Criteria andFrequencyLessThan(String value) {
            addCriterion("FREQUENCY <", value, "frequency");
            return (Criteria) this;
        }

        public Criteria andFrequencyLessThanOrEqualTo(String value) {
            addCriterion("FREQUENCY <=", value, "frequency");
            return (Criteria) this;
        }

        public Criteria andFrequencyLike(String value) {
            addCriterion("FREQUENCY like", value, "frequency");
            return (Criteria) this;
        }

        public Criteria andFrequencyNotLike(String value) {
            addCriterion("FREQUENCY not like", value, "frequency");
            return (Criteria) this;
        }

        public Criteria andFrequencyIn(List<String> values) {
            addCriterion("FREQUENCY in", values, "frequency");
            return (Criteria) this;
        }

        public Criteria andFrequencyNotIn(List<String> values) {
            addCriterion("FREQUENCY not in", values, "frequency");
            return (Criteria) this;
        }

        public Criteria andFrequencyBetween(String value1, String value2) {
            addCriterion("FREQUENCY between", value1, value2, "frequency");
            return (Criteria) this;
        }

        public Criteria andFrequencyNotBetween(String value1, String value2) {
            addCriterion("FREQUENCY not between", value1, value2, "frequency");
            return (Criteria) this;
        }

        public Criteria andRemindDaysIsNull() {
            addCriterion("REMIND_DAYS is null");
            return (Criteria) this;
        }

        public Criteria andRemindDaysIsNotNull() {
            addCriterion("REMIND_DAYS is not null");
            return (Criteria) this;
        }

        public Criteria andRemindDaysEqualTo(Integer value) {
            addCriterion("REMIND_DAYS =", value, "remindDays");
            return (Criteria) this;
        }

        public Criteria andRemindDaysNotEqualTo(Integer value) {
            addCriterion("REMIND_DAYS <>", value, "remindDays");
            return (Criteria) this;
        }

        public Criteria andRemindDaysGreaterThan(Integer value) {
            addCriterion("REMIND_DAYS >", value, "remindDays");
            return (Criteria) this;
        }

        public Criteria andRemindDaysGreaterThanOrEqualTo(Integer value) {
            addCriterion("REMIND_DAYS >=", value, "remindDays");
            return (Criteria) this;
        }

        public Criteria andRemindDaysLessThan(Integer value) {
            addCriterion("REMIND_DAYS <", value, "remindDays");
            return (Criteria) this;
        }

        public Criteria andRemindDaysLessThanOrEqualTo(Integer value) {
            addCriterion("REMIND_DAYS <=", value, "remindDays");
            return (Criteria) this;
        }

        public Criteria andRemindDaysIn(List<Integer> values) {
            addCriterion("REMIND_DAYS in", values, "remindDays");
            return (Criteria) this;
        }

        public Criteria andRemindDaysNotIn(List<Integer> values) {
            addCriterion("REMIND_DAYS not in", values, "remindDays");
            return (Criteria) this;
        }

        public Criteria andRemindDaysBetween(Integer value1, Integer value2) {
            addCriterion("REMIND_DAYS between", value1, value2, "remindDays");
            return (Criteria) this;
        }

        public Criteria andRemindDaysNotBetween(Integer value1, Integer value2) {
            addCriterion("REMIND_DAYS not between", value1, value2, "remindDays");
            return (Criteria) this;
        }

        public Criteria andLastExeTimeIsNull() {
            addCriterion("LAST_EXE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andLastExeTimeIsNotNull() {
            addCriterion("LAST_EXE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andLastExeTimeEqualTo(Date value) {
            addCriterion("LAST_EXE_TIME =", value, "lastExeTime");
            return (Criteria) this;
        }

        public Criteria andLastExeTimeNotEqualTo(Date value) {
            addCriterion("LAST_EXE_TIME <>", value, "lastExeTime");
            return (Criteria) this;
        }

        public Criteria andLastExeTimeGreaterThan(Date value) {
            addCriterion("LAST_EXE_TIME >", value, "lastExeTime");
            return (Criteria) this;
        }

        public Criteria andLastExeTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("LAST_EXE_TIME >=", value, "lastExeTime");
            return (Criteria) this;
        }

        public Criteria andLastExeTimeLessThan(Date value) {
            addCriterion("LAST_EXE_TIME <", value, "lastExeTime");
            return (Criteria) this;
        }

        public Criteria andLastExeTimeLessThanOrEqualTo(Date value) {
            addCriterion("LAST_EXE_TIME <=", value, "lastExeTime");
            return (Criteria) this;
        }

        public Criteria andLastExeTimeIn(List<Date> values) {
            addCriterion("LAST_EXE_TIME in", values, "lastExeTime");
            return (Criteria) this;
        }

        public Criteria andLastExeTimeNotIn(List<Date> values) {
            addCriterion("LAST_EXE_TIME not in", values, "lastExeTime");
            return (Criteria) this;
        }

        public Criteria andLastExeTimeBetween(Date value1, Date value2) {
            addCriterion("LAST_EXE_TIME between", value1, value2, "lastExeTime");
            return (Criteria) this;
        }

        public Criteria andLastExeTimeNotBetween(Date value1, Date value2) {
            addCriterion("LAST_EXE_TIME not between", value1, value2, "lastExeTime");
            return (Criteria) this;
        }

        public Criteria andNestExeTimeIsNull() {
            addCriterion("NEST_EXE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andNestExeTimeIsNotNull() {
            addCriterion("NEST_EXE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andNestExeTimeEqualTo(Date value) {
            addCriterion("NEST_EXE_TIME =", value, "nestExeTime");
            return (Criteria) this;
        }

        public Criteria andNestExeTimeNotEqualTo(Date value) {
            addCriterion("NEST_EXE_TIME <>", value, "nestExeTime");
            return (Criteria) this;
        }

        public Criteria andNestExeTimeGreaterThan(Date value) {
            addCriterion("NEST_EXE_TIME >", value, "nestExeTime");
            return (Criteria) this;
        }

        public Criteria andNestExeTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("NEST_EXE_TIME >=", value, "nestExeTime");
            return (Criteria) this;
        }

        public Criteria andNestExeTimeLessThan(Date value) {
            addCriterion("NEST_EXE_TIME <", value, "nestExeTime");
            return (Criteria) this;
        }

        public Criteria andNestExeTimeLessThanOrEqualTo(Date value) {
            addCriterion("NEST_EXE_TIME <=", value, "nestExeTime");
            return (Criteria) this;
        }

        public Criteria andNestExeTimeIn(List<Date> values) {
            addCriterion("NEST_EXE_TIME in", values, "nestExeTime");
            return (Criteria) this;
        }

        public Criteria andNestExeTimeNotIn(List<Date> values) {
            addCriterion("NEST_EXE_TIME not in", values, "nestExeTime");
            return (Criteria) this;
        }

        public Criteria andNestExeTimeBetween(Date value1, Date value2) {
            addCriterion("NEST_EXE_TIME between", value1, value2, "nestExeTime");
            return (Criteria) this;
        }

        public Criteria andNestExeTimeNotBetween(Date value1, Date value2) {
            addCriterion("NEST_EXE_TIME not between", value1, value2, "nestExeTime");
            return (Criteria) this;
        }

        public Criteria andDeptIdIsNull() {
            addCriterion("DEPT_ID is null");
            return (Criteria) this;
        }

        public Criteria andDeptIdIsNotNull() {
            addCriterion("DEPT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andDeptIdEqualTo(Integer value) {
            addCriterion("DEPT_ID =", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdNotEqualTo(Integer value) {
            addCriterion("DEPT_ID <>", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdGreaterThan(Integer value) {
            addCriterion("DEPT_ID >", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("DEPT_ID >=", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdLessThan(Integer value) {
            addCriterion("DEPT_ID <", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdLessThanOrEqualTo(Integer value) {
            addCriterion("DEPT_ID <=", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdIn(List<Integer> values) {
            addCriterion("DEPT_ID in", values, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdNotIn(List<Integer> values) {
            addCriterion("DEPT_ID not in", values, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdBetween(Integer value1, Integer value2) {
            addCriterion("DEPT_ID between", value1, value2, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdNotBetween(Integer value1, Integer value2) {
            addCriterion("DEPT_ID not between", value1, value2, "deptId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNull() {
            addCriterion("UPDATE_USER is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNotNull() {
            addCriterion("UPDATE_USER is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserEqualTo(String value) {
            addCriterion("UPDATE_USER =", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotEqualTo(String value) {
            addCriterion("UPDATE_USER <>", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThan(String value) {
            addCriterion("UPDATE_USER >", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATE_USER >=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThan(String value) {
            addCriterion("UPDATE_USER <", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThanOrEqualTo(String value) {
            addCriterion("UPDATE_USER <=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLike(String value) {
            addCriterion("UPDATE_USER like", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotLike(String value) {
            addCriterion("UPDATE_USER not like", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIn(List<String> values) {
            addCriterion("UPDATE_USER in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotIn(List<String> values) {
            addCriterion("UPDATE_USER not in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserBetween(String value1, String value2) {
            addCriterion("UPDATE_USER between", value1, value2, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotBetween(String value1, String value2) {
            addCriterion("UPDATE_USER not between", value1, value2, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateNameIsNull() {
            addCriterion("UPDATE_NAME is null");
            return (Criteria) this;
        }

        public Criteria andUpdateNameIsNotNull() {
            addCriterion("UPDATE_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateNameEqualTo(String value) {
            addCriterion("UPDATE_NAME =", value, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameNotEqualTo(String value) {
            addCriterion("UPDATE_NAME <>", value, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameGreaterThan(String value) {
            addCriterion("UPDATE_NAME >", value, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATE_NAME >=", value, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameLessThan(String value) {
            addCriterion("UPDATE_NAME <", value, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameLessThanOrEqualTo(String value) {
            addCriterion("UPDATE_NAME <=", value, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameLike(String value) {
            addCriterion("UPDATE_NAME like", value, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameNotLike(String value) {
            addCriterion("UPDATE_NAME not like", value, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameIn(List<String> values) {
            addCriterion("UPDATE_NAME in", values, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameNotIn(List<String> values) {
            addCriterion("UPDATE_NAME not in", values, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameBetween(String value1, String value2) {
            addCriterion("UPDATE_NAME between", value1, value2, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameNotBetween(String value1, String value2) {
            addCriterion("UPDATE_NAME not between", value1, value2, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("UPDATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("UPDATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("UPDATE_TIME =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("UPDATE_TIME <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("UPDATE_TIME >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("UPDATE_TIME <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("UPDATE_TIME in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("UPDATE_TIME not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andCompanyIsNull() {
            addCriterion("COMPANY is null");
            return (Criteria) this;
        }

        public Criteria andCompanyIsNotNull() {
            addCriterion("COMPANY is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyEqualTo(String value) {
            addCriterion("COMPANY =", value, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyNotEqualTo(String value) {
            addCriterion("COMPANY <>", value, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyGreaterThan(String value) {
            addCriterion("COMPANY >", value, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyGreaterThanOrEqualTo(String value) {
            addCriterion("COMPANY >=", value, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyLessThan(String value) {
            addCriterion("COMPANY <", value, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyLessThanOrEqualTo(String value) {
            addCriterion("COMPANY <=", value, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyLike(String value) {
            addCriterion("COMPANY like", value, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyNotLike(String value) {
            addCriterion("COMPANY not like", value, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyIn(List<String> values) {
            addCriterion("COMPANY in", values, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyNotIn(List<String> values) {
            addCriterion("COMPANY not in", values, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyBetween(String value1, String value2) {
            addCriterion("COMPANY between", value1, value2, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyNotBetween(String value1, String value2) {
            addCriterion("COMPANY not between", value1, value2, "company");
            return (Criteria) this;
        }

        public Criteria andInspectformIsNull() {
            addCriterion("INSPECTFORM is null");
            return (Criteria) this;
        }

        public Criteria andInspectformIsNotNull() {
            addCriterion("INSPECTFORM is not null");
            return (Criteria) this;
        }

        public Criteria andInspectformEqualTo(String value) {
            addCriterion("INSPECTFORM =", value, "inspectform");
            return (Criteria) this;
        }

        public Criteria andInspectformNotEqualTo(String value) {
            addCriterion("INSPECTFORM <>", value, "inspectform");
            return (Criteria) this;
        }

        public Criteria andInspectformGreaterThan(String value) {
            addCriterion("INSPECTFORM >", value, "inspectform");
            return (Criteria) this;
        }

        public Criteria andInspectformGreaterThanOrEqualTo(String value) {
            addCriterion("INSPECTFORM >=", value, "inspectform");
            return (Criteria) this;
        }

        public Criteria andInspectformLessThan(String value) {
            addCriterion("INSPECTFORM <", value, "inspectform");
            return (Criteria) this;
        }

        public Criteria andInspectformLessThanOrEqualTo(String value) {
            addCriterion("INSPECTFORM <=", value, "inspectform");
            return (Criteria) this;
        }

        public Criteria andInspectformLike(String value) {
            addCriterion("INSPECTFORM like", value, "inspectform");
            return (Criteria) this;
        }

        public Criteria andInspectformNotLike(String value) {
            addCriterion("INSPECTFORM not like", value, "inspectform");
            return (Criteria) this;
        }

        public Criteria andInspectformIn(List<String> values) {
            addCriterion("INSPECTFORM in", values, "inspectform");
            return (Criteria) this;
        }

        public Criteria andInspectformNotIn(List<String> values) {
            addCriterion("INSPECTFORM not in", values, "inspectform");
            return (Criteria) this;
        }

        public Criteria andInspectformBetween(String value1, String value2) {
            addCriterion("INSPECTFORM between", value1, value2, "inspectform");
            return (Criteria) this;
        }

        public Criteria andInspectformNotBetween(String value1, String value2) {
            addCriterion("INSPECTFORM not between", value1, value2, "inspectform");
            return (Criteria) this;
        }

        public Criteria andEquipTypeIdIsNull() {
            addCriterion("EQUIP_TYPE_ID is null");
            return (Criteria) this;
        }

        public Criteria andEquipTypeIdIsNotNull() {
            addCriterion("EQUIP_TYPE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andEquipTypeIdEqualTo(Integer value) {
            addCriterion("EQUIP_TYPE_ID =", value, "equipTypeId");
            return (Criteria) this;
        }

        public Criteria andEquipTypeIdNotEqualTo(Integer value) {
            addCriterion("EQUIP_TYPE_ID <>", value, "equipTypeId");
            return (Criteria) this;
        }

        public Criteria andEquipTypeIdGreaterThan(Integer value) {
            addCriterion("EQUIP_TYPE_ID >", value, "equipTypeId");
            return (Criteria) this;
        }

        public Criteria andEquipTypeIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("EQUIP_TYPE_ID >=", value, "equipTypeId");
            return (Criteria) this;
        }

        public Criteria andEquipTypeIdLessThan(Integer value) {
            addCriterion("EQUIP_TYPE_ID <", value, "equipTypeId");
            return (Criteria) this;
        }

        public Criteria andEquipTypeIdLessThanOrEqualTo(Integer value) {
            addCriterion("EQUIP_TYPE_ID <=", value, "equipTypeId");
            return (Criteria) this;
        }

        public Criteria andEquipTypeIdIn(List<Integer> values) {
            addCriterion("EQUIP_TYPE_ID in", values, "equipTypeId");
            return (Criteria) this;
        }

        public Criteria andEquipTypeIdNotIn(List<Integer> values) {
            addCriterion("EQUIP_TYPE_ID not in", values, "equipTypeId");
            return (Criteria) this;
        }

        public Criteria andEquipTypeIdBetween(Integer value1, Integer value2) {
            addCriterion("EQUIP_TYPE_ID between", value1, value2, "equipTypeId");
            return (Criteria) this;
        }

        public Criteria andEquipTypeIdNotBetween(Integer value1, Integer value2) {
            addCriterion("EQUIP_TYPE_ID not between", value1, value2, "equipTypeId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table lims_equip_events_plan
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table lims_equip_events_plan
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}