package com.xoa.model.equipment;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class LimsCommonCodeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lims_common_code
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lims_common_code
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lims_common_code
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_common_code
     *
     * @mbggenerated
     */
    public LimsCommonCodeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_common_code
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_common_code
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_common_code
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_common_code
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_common_code
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_common_code
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_common_code
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_common_code
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_common_code
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_common_code
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table lims_common_code
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCodeTyepIdIsNull() {
            addCriterion("CODE_TYEP_ID is null");
            return (Criteria) this;
        }

        public Criteria andCodeTyepIdIsNotNull() {
            addCriterion("CODE_TYEP_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCodeTyepIdEqualTo(Integer value) {
            addCriterion("CODE_TYEP_ID =", value, "codeTyepId");
            return (Criteria) this;
        }

        public Criteria andCodeTyepIdNotEqualTo(Integer value) {
            addCriterion("CODE_TYEP_ID <>", value, "codeTyepId");
            return (Criteria) this;
        }

        public Criteria andCodeTyepIdGreaterThan(Integer value) {
            addCriterion("CODE_TYEP_ID >", value, "codeTyepId");
            return (Criteria) this;
        }

        public Criteria andCodeTyepIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("CODE_TYEP_ID >=", value, "codeTyepId");
            return (Criteria) this;
        }

        public Criteria andCodeTyepIdLessThan(Integer value) {
            addCriterion("CODE_TYEP_ID <", value, "codeTyepId");
            return (Criteria) this;
        }

        public Criteria andCodeTyepIdLessThanOrEqualTo(Integer value) {
            addCriterion("CODE_TYEP_ID <=", value, "codeTyepId");
            return (Criteria) this;
        }

        public Criteria andCodeTyepIdIn(List<Integer> values) {
            addCriterion("CODE_TYEP_ID in", values, "codeTyepId");
            return (Criteria) this;
        }

        public Criteria andCodeTyepIdNotIn(List<Integer> values) {
            addCriterion("CODE_TYEP_ID not in", values, "codeTyepId");
            return (Criteria) this;
        }

        public Criteria andCodeTyepIdBetween(Integer value1, Integer value2) {
            addCriterion("CODE_TYEP_ID between", value1, value2, "codeTyepId");
            return (Criteria) this;
        }

        public Criteria andCodeTyepIdNotBetween(Integer value1, Integer value2) {
            addCriterion("CODE_TYEP_ID not between", value1, value2, "codeTyepId");
            return (Criteria) this;
        }

        public Criteria andCodeTyepNoIsNull() {
            addCriterion("CODE_TYEP_NO is null");
            return (Criteria) this;
        }

        public Criteria andCodeTyepNoIsNotNull() {
            addCriterion("CODE_TYEP_NO is not null");
            return (Criteria) this;
        }

        public Criteria andCodeTyepNoEqualTo(String value) {
            addCriterion("CODE_TYEP_NO =", value, "codeTyepNo");
            return (Criteria) this;
        }

        public Criteria andCodeTyepNoNotEqualTo(String value) {
            addCriterion("CODE_TYEP_NO <>", value, "codeTyepNo");
            return (Criteria) this;
        }

        public Criteria andCodeTyepNoGreaterThan(String value) {
            addCriterion("CODE_TYEP_NO >", value, "codeTyepNo");
            return (Criteria) this;
        }

        public Criteria andCodeTyepNoGreaterThanOrEqualTo(String value) {
            addCriterion("CODE_TYEP_NO >=", value, "codeTyepNo");
            return (Criteria) this;
        }

        public Criteria andCodeTyepNoLessThan(String value) {
            addCriterion("CODE_TYEP_NO <", value, "codeTyepNo");
            return (Criteria) this;
        }

        public Criteria andCodeTyepNoLessThanOrEqualTo(String value) {
            addCriterion("CODE_TYEP_NO <=", value, "codeTyepNo");
            return (Criteria) this;
        }

        public Criteria andCodeTyepNoLike(String value) {
            addCriterion("CODE_TYEP_NO like", value, "codeTyepNo");
            return (Criteria) this;
        }

        public Criteria andCodeTyepNoNotLike(String value) {
            addCriterion("CODE_TYEP_NO not like", value, "codeTyepNo");
            return (Criteria) this;
        }

        public Criteria andCodeTyepNoIn(List<String> values) {
            addCriterion("CODE_TYEP_NO in", values, "codeTyepNo");
            return (Criteria) this;
        }

        public Criteria andCodeTyepNoNotIn(List<String> values) {
            addCriterion("CODE_TYEP_NO not in", values, "codeTyepNo");
            return (Criteria) this;
        }

        public Criteria andCodeTyepNoBetween(String value1, String value2) {
            addCriterion("CODE_TYEP_NO between", value1, value2, "codeTyepNo");
            return (Criteria) this;
        }

        public Criteria andCodeTyepNoNotBetween(String value1, String value2) {
            addCriterion("CODE_TYEP_NO not between", value1, value2, "codeTyepNo");
            return (Criteria) this;
        }

        public Criteria andCodeTyepNameIsNull() {
            addCriterion("CODE_TYEP_NAME is null");
            return (Criteria) this;
        }

        public Criteria andCodeTyepNameIsNotNull() {
            addCriterion("CODE_TYEP_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andCodeTyepNameEqualTo(String value) {
            addCriterion("CODE_TYEP_NAME =", value, "codeTyepName");
            return (Criteria) this;
        }

        public Criteria andCodeTyepNameNotEqualTo(String value) {
            addCriterion("CODE_TYEP_NAME <>", value, "codeTyepName");
            return (Criteria) this;
        }

        public Criteria andCodeTyepNameGreaterThan(String value) {
            addCriterion("CODE_TYEP_NAME >", value, "codeTyepName");
            return (Criteria) this;
        }

        public Criteria andCodeTyepNameGreaterThanOrEqualTo(String value) {
            addCriterion("CODE_TYEP_NAME >=", value, "codeTyepName");
            return (Criteria) this;
        }

        public Criteria andCodeTyepNameLessThan(String value) {
            addCriterion("CODE_TYEP_NAME <", value, "codeTyepName");
            return (Criteria) this;
        }

        public Criteria andCodeTyepNameLessThanOrEqualTo(String value) {
            addCriterion("CODE_TYEP_NAME <=", value, "codeTyepName");
            return (Criteria) this;
        }

        public Criteria andCodeTyepNameLike(String value) {
            addCriterion("CODE_TYEP_NAME like", value, "codeTyepName");
            return (Criteria) this;
        }

        public Criteria andCodeTyepNameNotLike(String value) {
            addCriterion("CODE_TYEP_NAME not like", value, "codeTyepName");
            return (Criteria) this;
        }

        public Criteria andCodeTyepNameIn(List<String> values) {
            addCriterion("CODE_TYEP_NAME in", values, "codeTyepName");
            return (Criteria) this;
        }

        public Criteria andCodeTyepNameNotIn(List<String> values) {
            addCriterion("CODE_TYEP_NAME not in", values, "codeTyepName");
            return (Criteria) this;
        }

        public Criteria andCodeTyepNameBetween(String value1, String value2) {
            addCriterion("CODE_TYEP_NAME between", value1, value2, "codeTyepName");
            return (Criteria) this;
        }

        public Criteria andCodeTyepNameNotBetween(String value1, String value2) {
            addCriterion("CODE_TYEP_NAME not between", value1, value2, "codeTyepName");
            return (Criteria) this;
        }

        public Criteria andParentTyepNoIsNull() {
            addCriterion("PARENT_TYEP_NO is null");
            return (Criteria) this;
        }

        public Criteria andParentTyepNoIsNotNull() {
            addCriterion("PARENT_TYEP_NO is not null");
            return (Criteria) this;
        }

        public Criteria andParentTyepNoEqualTo(String value) {
            addCriterion("PARENT_TYEP_NO =", value, "parentTyepNo");
            return (Criteria) this;
        }

        public Criteria andParentTyepNoNotEqualTo(String value) {
            addCriterion("PARENT_TYEP_NO <>", value, "parentTyepNo");
            return (Criteria) this;
        }

        public Criteria andParentTyepNoGreaterThan(String value) {
            addCriterion("PARENT_TYEP_NO >", value, "parentTyepNo");
            return (Criteria) this;
        }

        public Criteria andParentTyepNoGreaterThanOrEqualTo(String value) {
            addCriterion("PARENT_TYEP_NO >=", value, "parentTyepNo");
            return (Criteria) this;
        }

        public Criteria andParentTyepNoLessThan(String value) {
            addCriterion("PARENT_TYEP_NO <", value, "parentTyepNo");
            return (Criteria) this;
        }

        public Criteria andParentTyepNoLessThanOrEqualTo(String value) {
            addCriterion("PARENT_TYEP_NO <=", value, "parentTyepNo");
            return (Criteria) this;
        }

        public Criteria andParentTyepNoLike(String value) {
            addCriterion("PARENT_TYEP_NO like", value, "parentTyepNo");
            return (Criteria) this;
        }

        public Criteria andParentTyepNoNotLike(String value) {
            addCriterion("PARENT_TYEP_NO not like", value, "parentTyepNo");
            return (Criteria) this;
        }

        public Criteria andParentTyepNoIn(List<String> values) {
            addCriterion("PARENT_TYEP_NO in", values, "parentTyepNo");
            return (Criteria) this;
        }

        public Criteria andParentTyepNoNotIn(List<String> values) {
            addCriterion("PARENT_TYEP_NO not in", values, "parentTyepNo");
            return (Criteria) this;
        }

        public Criteria andParentTyepNoBetween(String value1, String value2) {
            addCriterion("PARENT_TYEP_NO between", value1, value2, "parentTyepNo");
            return (Criteria) this;
        }

        public Criteria andParentTyepNoNotBetween(String value1, String value2) {
            addCriterion("PARENT_TYEP_NO not between", value1, value2, "parentTyepNo");
            return (Criteria) this;
        }

        public Criteria andCodeSortIsNull() {
            addCriterion("CODE_SORT is null");
            return (Criteria) this;
        }

        public Criteria andCodeSortIsNotNull() {
            addCriterion("CODE_SORT is not null");
            return (Criteria) this;
        }

        public Criteria andCodeSortEqualTo(String value) {
            addCriterion("CODE_SORT =", value, "codeSort");
            return (Criteria) this;
        }

        public Criteria andCodeSortNotEqualTo(String value) {
            addCriterion("CODE_SORT <>", value, "codeSort");
            return (Criteria) this;
        }

        public Criteria andCodeSortGreaterThan(String value) {
            addCriterion("CODE_SORT >", value, "codeSort");
            return (Criteria) this;
        }

        public Criteria andCodeSortGreaterThanOrEqualTo(String value) {
            addCriterion("CODE_SORT >=", value, "codeSort");
            return (Criteria) this;
        }

        public Criteria andCodeSortLessThan(String value) {
            addCriterion("CODE_SORT <", value, "codeSort");
            return (Criteria) this;
        }

        public Criteria andCodeSortLessThanOrEqualTo(String value) {
            addCriterion("CODE_SORT <=", value, "codeSort");
            return (Criteria) this;
        }

        public Criteria andCodeSortLike(String value) {
            addCriterion("CODE_SORT like", value, "codeSort");
            return (Criteria) this;
        }

        public Criteria andCodeSortNotLike(String value) {
            addCriterion("CODE_SORT not like", value, "codeSort");
            return (Criteria) this;
        }

        public Criteria andCodeSortIn(List<String> values) {
            addCriterion("CODE_SORT in", values, "codeSort");
            return (Criteria) this;
        }

        public Criteria andCodeSortNotIn(List<String> values) {
            addCriterion("CODE_SORT not in", values, "codeSort");
            return (Criteria) this;
        }

        public Criteria andCodeSortBetween(String value1, String value2) {
            addCriterion("CODE_SORT between", value1, value2, "codeSort");
            return (Criteria) this;
        }

        public Criteria andCodeSortNotBetween(String value1, String value2) {
            addCriterion("CODE_SORT not between", value1, value2, "codeSort");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagIsNull() {
            addCriterion("DELETE_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagIsNotNull() {
            addCriterion("DELETE_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagEqualTo(String value) {
            addCriterion("DELETE_FLAG =", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagNotEqualTo(String value) {
            addCriterion("DELETE_FLAG <>", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagGreaterThan(String value) {
            addCriterion("DELETE_FLAG >", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagGreaterThanOrEqualTo(String value) {
            addCriterion("DELETE_FLAG >=", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagLessThan(String value) {
            addCriterion("DELETE_FLAG <", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagLessThanOrEqualTo(String value) {
            addCriterion("DELETE_FLAG <=", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagLike(String value) {
            addCriterion("DELETE_FLAG like", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagNotLike(String value) {
            addCriterion("DELETE_FLAG not like", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagIn(List<String> values) {
            addCriterion("DELETE_FLAG in", values, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagNotIn(List<String> values) {
            addCriterion("DELETE_FLAG not in", values, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagBetween(String value1, String value2) {
            addCriterion("DELETE_FLAG between", value1, value2, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagNotBetween(String value1, String value2) {
            addCriterion("DELETE_FLAG not between", value1, value2, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andAddUsernameIsNull() {
            addCriterion("ADD_USERNAME is null");
            return (Criteria) this;
        }

        public Criteria andAddUsernameIsNotNull() {
            addCriterion("ADD_USERNAME is not null");
            return (Criteria) this;
        }

        public Criteria andAddUsernameEqualTo(String value) {
            addCriterion("ADD_USERNAME =", value, "addUsername");
            return (Criteria) this;
        }

        public Criteria andAddUsernameNotEqualTo(String value) {
            addCriterion("ADD_USERNAME <>", value, "addUsername");
            return (Criteria) this;
        }

        public Criteria andAddUsernameGreaterThan(String value) {
            addCriterion("ADD_USERNAME >", value, "addUsername");
            return (Criteria) this;
        }

        public Criteria andAddUsernameGreaterThanOrEqualTo(String value) {
            addCriterion("ADD_USERNAME >=", value, "addUsername");
            return (Criteria) this;
        }

        public Criteria andAddUsernameLessThan(String value) {
            addCriterion("ADD_USERNAME <", value, "addUsername");
            return (Criteria) this;
        }

        public Criteria andAddUsernameLessThanOrEqualTo(String value) {
            addCriterion("ADD_USERNAME <=", value, "addUsername");
            return (Criteria) this;
        }

        public Criteria andAddUsernameLike(String value) {
            addCriterion("ADD_USERNAME like", value, "addUsername");
            return (Criteria) this;
        }

        public Criteria andAddUsernameNotLike(String value) {
            addCriterion("ADD_USERNAME not like", value, "addUsername");
            return (Criteria) this;
        }

        public Criteria andAddUsernameIn(List<String> values) {
            addCriterion("ADD_USERNAME in", values, "addUsername");
            return (Criteria) this;
        }

        public Criteria andAddUsernameNotIn(List<String> values) {
            addCriterion("ADD_USERNAME not in", values, "addUsername");
            return (Criteria) this;
        }

        public Criteria andAddUsernameBetween(String value1, String value2) {
            addCriterion("ADD_USERNAME between", value1, value2, "addUsername");
            return (Criteria) this;
        }

        public Criteria andAddUsernameNotBetween(String value1, String value2) {
            addCriterion("ADD_USERNAME not between", value1, value2, "addUsername");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("UPDATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("UPDATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("UPDATE_TIME =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("UPDATE_TIME <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("UPDATE_TIME >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("UPDATE_TIME <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("UPDATE_TIME in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("UPDATE_TIME not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME not between", value1, value2, "updateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table lims_common_code
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table lims_common_code
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}