package com.xoa.model.equipment;

import java.util.Date;

public class LimsEquipReparlog {

    public String getCodeName() {
        return codeName;
    }

    public void setCodeName(String codeName) {
        this.codeName = codeName;
    }

    private String codeName; //现象分类
    private String propertyNo;

    public String getPropertyNo() {
        return propertyNo;
    }

    public void setPropertyNo(String propertyNo) {
        this.propertyNo = propertyNo;
    }
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equip_reparlog.REPALOG_ID
     *
     * @mbggenerated
     */
    private Integer repalogId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equip_reparlog.EQUIP_ID
     *
     * @mbggenerated
     */
    private Integer equipId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equip_reparlog.EQUIP_NO
     *
     * @mbggenerated
     */
    private String equipNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equip_reparlog.EQUIP_NAME
     *
     * @mbggenerated
     */
    private String equipName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equip_reparlog.EQUIP_STATUAS_CODE
     *
     * @mbggenerated
     */
    private String equipStatuasCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equip_reparlog.MODEL_NO
     *
     * @mbggenerated
     */
    private String modelNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equip_reparlog.SPEC
     *
     * @mbggenerated
     */
    private String spec;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equip_reparlog.FACTORY_NO
     *
     * @mbggenerated
     */
    private String factoryNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equip_reparlog.EQUIP_TYPE_ID
     *
     * @mbggenerated
     */
    private Integer equipTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equip_reparlog.EQUIP_TYPE_NAME
     *
     * @mbggenerated
     */
    private String equipTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equip_reparlog.FAULT_TYPE
     *
     * @mbggenerated
     */
    private String faultType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equip_reparlog.FAULT_POSITION
     *
     * @mbggenerated
     */
    private String faultPosition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equip_reparlog.FAULT_DESC
     *
     * @mbggenerated
     */
    private String faultDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equip_reparlog.ATMOSPHERE_TEMP
     *
     * @mbggenerated
     */
    private String atmosphereTemp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equip_reparlog.ATMOSPHERE_HUMI
     *
     * @mbggenerated
     */
    private String atmosphereHumi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equip_reparlog.ATMOSPHERE_PRESS
     *
     * @mbggenerated
     */
    private String atmospherePress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equip_reparlog.VOLTAGE
     *
     * @mbggenerated
     */
    private String voltage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equip_reparlog.RESISTANCE
     *
     * @mbggenerated
     */
    private String resistance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equip_reparlog.WATER PRESSURE
     *
     * @mbggenerated
     */
    private String waterPressure;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equip_reparlog.WATER TEMP
     *
     * @mbggenerated
     */
    private String waterTemp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equip_reparlog.PRESSURE
     *
     * @mbggenerated
     */
    private String pressure;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equip_reparlog.APPLICATION_TIME
     *
     * @mbggenerated
     */
    private String applicationTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equip_reparlog.IN_RESULT
     *
     * @mbggenerated
     */
    private String inResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equip_reparlog.IN_FAULT_POSITION
     *
     * @mbggenerated
     */
    private String inFaultPosition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equip_reparlog.IN_REASON
     *
     * @mbggenerated
     */
    private String inReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equip_reparlog.IN_REPAIR_MEASURE
     *
     * @mbggenerated
     */
    private String inRepairMeasure;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equip_reparlog.IN_REPAIR_MODE
     *
     * @mbggenerated
     */
    private String inRepairMode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equip_reparlog.IN_REPAIR_RANK
     *
     * @mbggenerated
     */
    private String inRepairRank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equip_reparlog.IN_PLAN_TIME
     *
     * @mbggenerated
     */
    private String inPlanTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equip_reparlog.IN_PRICE
     *
     * @mbggenerated
     */
    private String inPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equip_reparlog.IN_PERSON
     *
     * @mbggenerated
     */
    private String inPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equip_reparlog.IN_REPAIR_TIME
     *
     * @mbggenerated
     */
    private String inRepairTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equip_reparlog.OUT_RESULT
     *
     * @mbggenerated
     */
    private String outResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equip_reparlog.OUT_FAULT_POSITION
     *
     * @mbggenerated
     */
    private String outFaultPosition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equip_reparlog.OUT_REASON
     *
     * @mbggenerated
     */
    private String outReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equip_reparlog.OUT_REPAIR_MEASURE
     *
     * @mbggenerated
     */
    private String outRepairMeasure;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equip_reparlog.OUT_REPAIR_MODE
     *
     * @mbggenerated
     */
    private String outRepairMode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equip_reparlog.OUT_REPAIR_RANK
     *
     * @mbggenerated
     */
    private String outRepairRank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equip_reparlog.OUT_PLAN_TIME
     *
     * @mbggenerated
     */
    private String outPlanTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equip_reparlog.OUT_PRICE
     *
     * @mbggenerated
     */
    private String outPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equip_reparlog.OUT_PERSON
     *
     * @mbggenerated
     */
    private String outPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equip_reparlog.OUT_REPAIR_TIME
     *
     * @mbggenerated
     */
    private String outRepairTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equip_reparlog.VERIFY_MEASURE
     *
     * @mbggenerated
     */
    private String verifyMeasure;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equip_reparlog.EQUIP_VERIFY_MODE
     *
     * @mbggenerated
     */
    private String equipVerifyMode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equip_reparlog.EQUIP_REPAIR_RESULT
     *
     * @mbggenerated
     */
    private String equipRepairResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equip_reparlog.REPORT_DONE_TIME
     *
     * @mbggenerated
     */
    private String reportDoneTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equip_reparlog.VERIFY_USER
     *
     * @mbggenerated
     */
    private String verifyUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equip_reparlog.VERIFY_TIME
     *
     * @mbggenerated
     */
    private String verifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equip_reparlog.APPLICANT
     *
     * @mbggenerated
     */
    private String applicant;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equip_reparlog.APPLICANT_TIME
     *
     * @mbggenerated
     */
    private Date applicantTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equip_reparlog.MEMO
     *
     * @mbggenerated
     */
    private String memo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equip_reparlog.WORKFLOW_NO
     *
     * @mbggenerated
     */
    private String workflowNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equip_reparlog.REPAIR_STATUS
     *
     * @mbggenerated
     */
    private String repairStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equip_reparlog.REPALOG_ID
     *
     * @return the value of lims_equip_reparlog.REPALOG_ID
     *
     * @mbggenerated
     */
    public Integer getRepalogId() {
        return repalogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equip_reparlog.REPALOG_ID
     *
     * @param repalogId the value for lims_equip_reparlog.REPALOG_ID
     *
     * @mbggenerated
     */
    public void setRepalogId(Integer repalogId) {
        this.repalogId = repalogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equip_reparlog.EQUIP_ID
     *
     * @return the value of lims_equip_reparlog.EQUIP_ID
     *
     * @mbggenerated
     */
    public Integer getEquipId() {
        return equipId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equip_reparlog.EQUIP_ID
     *
     * @param equipId the value for lims_equip_reparlog.EQUIP_ID
     *
     * @mbggenerated
     */
    public void setEquipId(Integer equipId) {
        this.equipId = equipId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equip_reparlog.EQUIP_NO
     *
     * @return the value of lims_equip_reparlog.EQUIP_NO
     *
     * @mbggenerated
     */
    public String getEquipNo() {
        return equipNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equip_reparlog.EQUIP_NO
     *
     * @param equipNo the value for lims_equip_reparlog.EQUIP_NO
     *
     * @mbggenerated
     */
    public void setEquipNo(String equipNo) {
        this.equipNo = equipNo == null ? null : equipNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equip_reparlog.EQUIP_NAME
     *
     * @return the value of lims_equip_reparlog.EQUIP_NAME
     *
     * @mbggenerated
     */
    public String getEquipName() {
        return equipName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equip_reparlog.EQUIP_NAME
     *
     * @param equipName the value for lims_equip_reparlog.EQUIP_NAME
     *
     * @mbggenerated
     */
    public void setEquipName(String equipName) {
        this.equipName = equipName == null ? null : equipName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equip_reparlog.EQUIP_STATUAS_CODE
     *
     * @return the value of lims_equip_reparlog.EQUIP_STATUAS_CODE
     *
     * @mbggenerated
     */
    public String getEquipStatuasCode() {
        return equipStatuasCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equip_reparlog.EQUIP_STATUAS_CODE
     *
     * @param equipStatuasCode the value for lims_equip_reparlog.EQUIP_STATUAS_CODE
     *
     * @mbggenerated
     */
    public void setEquipStatuasCode(String equipStatuasCode) {
        this.equipStatuasCode = equipStatuasCode == null ? null : equipStatuasCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equip_reparlog.MODEL_NO
     *
     * @return the value of lims_equip_reparlog.MODEL_NO
     *
     * @mbggenerated
     */
    public String getModelNo() {
        return modelNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equip_reparlog.MODEL_NO
     *
     * @param modelNo the value for lims_equip_reparlog.MODEL_NO
     *
     * @mbggenerated
     */
    public void setModelNo(String modelNo) {
        this.modelNo = modelNo == null ? null : modelNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equip_reparlog.SPEC
     *
     * @return the value of lims_equip_reparlog.SPEC
     *
     * @mbggenerated
     */
    public String getSpec() {
        return spec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equip_reparlog.SPEC
     *
     * @param spec the value for lims_equip_reparlog.SPEC
     *
     * @mbggenerated
     */
    public void setSpec(String spec) {
        this.spec = spec == null ? null : spec.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equip_reparlog.FACTORY_NO
     *
     * @return the value of lims_equip_reparlog.FACTORY_NO
     *
     * @mbggenerated
     */
    public String getFactoryNo() {
        return factoryNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equip_reparlog.FACTORY_NO
     *
     * @param factoryNo the value for lims_equip_reparlog.FACTORY_NO
     *
     * @mbggenerated
     */
    public void setFactoryNo(String factoryNo) {
        this.factoryNo = factoryNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equip_reparlog.EQUIP_TYPE_ID
     *
     * @return the value of lims_equip_reparlog.EQUIP_TYPE_ID
     *
     * @mbggenerated
     */
    public Integer getEquipTypeId() {
        return equipTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equip_reparlog.EQUIP_TYPE_ID
     *
     * @param equipTypeId the value for lims_equip_reparlog.EQUIP_TYPE_ID
     *
     * @mbggenerated
     */
    public void setEquipTypeId(Integer equipTypeId) {
        this.equipTypeId = equipTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equip_reparlog.EQUIP_TYPE_NAME
     *
     * @return the value of lims_equip_reparlog.EQUIP_TYPE_NAME
     *
     * @mbggenerated
     */
    public String getEquipTypeName() {
        return equipTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equip_reparlog.EQUIP_TYPE_NAME
     *
     * @param equipTypeName the value for lims_equip_reparlog.EQUIP_TYPE_NAME
     *
     * @mbggenerated
     */
    public void setEquipTypeName(String equipTypeName) {
        this.equipTypeName = equipTypeName == null ? null : equipTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equip_reparlog.FAULT_TYPE
     *
     * @return the value of lims_equip_reparlog.FAULT_TYPE
     *
     * @mbggenerated
     */
    public String getFaultType() {
        return faultType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equip_reparlog.FAULT_TYPE
     *
     * @param faultType the value for lims_equip_reparlog.FAULT_TYPE
     *
     * @mbggenerated
     */
    public void setFaultType(String faultType) {
        this.faultType = faultType == null ? null : faultType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equip_reparlog.FAULT_POSITION
     *
     * @return the value of lims_equip_reparlog.FAULT_POSITION
     *
     * @mbggenerated
     */
    public String getFaultPosition() {
        return faultPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equip_reparlog.FAULT_POSITION
     *
     * @param faultPosition the value for lims_equip_reparlog.FAULT_POSITION
     *
     * @mbggenerated
     */
    public void setFaultPosition(String faultPosition) {
        this.faultPosition = faultPosition == null ? null : faultPosition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equip_reparlog.FAULT_DESC
     *
     * @return the value of lims_equip_reparlog.FAULT_DESC
     *
     * @mbggenerated
     */
    public String getFaultDesc() {
        return faultDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equip_reparlog.FAULT_DESC
     *
     * @param faultDesc the value for lims_equip_reparlog.FAULT_DESC
     *
     * @mbggenerated
     */
    public void setFaultDesc(String faultDesc) {
        this.faultDesc = faultDesc == null ? null : faultDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equip_reparlog.ATMOSPHERE_TEMP
     *
     * @return the value of lims_equip_reparlog.ATMOSPHERE_TEMP
     *
     * @mbggenerated
     */
    public String getAtmosphereTemp() {
        return atmosphereTemp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equip_reparlog.ATMOSPHERE_TEMP
     *
     * @param atmosphereTemp the value for lims_equip_reparlog.ATMOSPHERE_TEMP
     *
     * @mbggenerated
     */
    public void setAtmosphereTemp(String atmosphereTemp) {
        this.atmosphereTemp = atmosphereTemp == null ? null : atmosphereTemp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equip_reparlog.ATMOSPHERE_HUMI
     *
     * @return the value of lims_equip_reparlog.ATMOSPHERE_HUMI
     *
     * @mbggenerated
     */
    public String getAtmosphereHumi() {
        return atmosphereHumi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equip_reparlog.ATMOSPHERE_HUMI
     *
     * @param atmosphereHumi the value for lims_equip_reparlog.ATMOSPHERE_HUMI
     *
     * @mbggenerated
     */
    public void setAtmosphereHumi(String atmosphereHumi) {
        this.atmosphereHumi = atmosphereHumi == null ? null : atmosphereHumi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equip_reparlog.ATMOSPHERE_PRESS
     *
     * @return the value of lims_equip_reparlog.ATMOSPHERE_PRESS
     *
     * @mbggenerated
     */
    public String getAtmospherePress() {
        return atmospherePress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equip_reparlog.ATMOSPHERE_PRESS
     *
     * @param atmospherePress the value for lims_equip_reparlog.ATMOSPHERE_PRESS
     *
     * @mbggenerated
     */
    public void setAtmospherePress(String atmospherePress) {
        this.atmospherePress = atmospherePress == null ? null : atmospherePress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equip_reparlog.VOLTAGE
     *
     * @return the value of lims_equip_reparlog.VOLTAGE
     *
     * @mbggenerated
     */
    public String getVoltage() {
        return voltage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equip_reparlog.VOLTAGE
     *
     * @param voltage the value for lims_equip_reparlog.VOLTAGE
     *
     * @mbggenerated
     */
    public void setVoltage(String voltage) {
        this.voltage = voltage == null ? null : voltage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equip_reparlog.RESISTANCE
     *
     * @return the value of lims_equip_reparlog.RESISTANCE
     *
     * @mbggenerated
     */
    public String getResistance() {
        return resistance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equip_reparlog.RESISTANCE
     *
     * @param resistance the value for lims_equip_reparlog.RESISTANCE
     *
     * @mbggenerated
     */
    public void setResistance(String resistance) {
        this.resistance = resistance == null ? null : resistance.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equip_reparlog.WATER PRESSURE
     *
     * @return the value of lims_equip_reparlog.WATER PRESSURE
     *
     * @mbggenerated
     */
    public String getWaterPressure() {
        return waterPressure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equip_reparlog.WATER PRESSURE
     *
     * @param waterPressure the value for lims_equip_reparlog.WATER PRESSURE
     *
     * @mbggenerated
     */
    public void setWaterPressure(String waterPressure) {
        this.waterPressure = waterPressure == null ? null : waterPressure.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equip_reparlog.WATER TEMP
     *
     * @return the value of lims_equip_reparlog.WATER TEMP
     *
     * @mbggenerated
     */
    public String getWaterTemp() {
        return waterTemp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equip_reparlog.WATER TEMP
     *
     * @param waterTemp the value for lims_equip_reparlog.WATER TEMP
     *
     * @mbggenerated
     */
    public void setWaterTemp(String waterTemp) {
        this.waterTemp = waterTemp == null ? null : waterTemp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equip_reparlog.PRESSURE
     *
     * @return the value of lims_equip_reparlog.PRESSURE
     *
     * @mbggenerated
     */
    public String getPressure() {
        return pressure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equip_reparlog.PRESSURE
     *
     * @param pressure the value for lims_equip_reparlog.PRESSURE
     *
     * @mbggenerated
     */
    public void setPressure(String pressure) {
        this.pressure = pressure == null ? null : pressure.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equip_reparlog.APPLICATION_TIME
     *
     * @return the value of lims_equip_reparlog.APPLICATION_TIME
     *
     * @mbggenerated
     */
    public String getApplicationTime() {
        return applicationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equip_reparlog.APPLICATION_TIME
     *
     * @param applicationTime the value for lims_equip_reparlog.APPLICATION_TIME
     *
     * @mbggenerated
     */
    public void setApplicationTime(String applicationTime) {
        this.applicationTime = applicationTime == null ? null : applicationTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equip_reparlog.IN_RESULT
     *
     * @return the value of lims_equip_reparlog.IN_RESULT
     *
     * @mbggenerated
     */
    public String getInResult() {
        return inResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equip_reparlog.IN_RESULT
     *
     * @param inResult the value for lims_equip_reparlog.IN_RESULT
     *
     * @mbggenerated
     */
    public void setInResult(String inResult) {
        this.inResult = inResult == null ? null : inResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equip_reparlog.IN_FAULT_POSITION
     *
     * @return the value of lims_equip_reparlog.IN_FAULT_POSITION
     *
     * @mbggenerated
     */
    public String getInFaultPosition() {
        return inFaultPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equip_reparlog.IN_FAULT_POSITION
     *
     * @param inFaultPosition the value for lims_equip_reparlog.IN_FAULT_POSITION
     *
     * @mbggenerated
     */
    public void setInFaultPosition(String inFaultPosition) {
        this.inFaultPosition = inFaultPosition == null ? null : inFaultPosition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equip_reparlog.IN_REASON
     *
     * @return the value of lims_equip_reparlog.IN_REASON
     *
     * @mbggenerated
     */
    public String getInReason() {
        return inReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equip_reparlog.IN_REASON
     *
     * @param inReason the value for lims_equip_reparlog.IN_REASON
     *
     * @mbggenerated
     */
    public void setInReason(String inReason) {
        this.inReason = inReason == null ? null : inReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equip_reparlog.IN_REPAIR_MEASURE
     *
     * @return the value of lims_equip_reparlog.IN_REPAIR_MEASURE
     *
     * @mbggenerated
     */
    public String getInRepairMeasure() {
        return inRepairMeasure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equip_reparlog.IN_REPAIR_MEASURE
     *
     * @param inRepairMeasure the value for lims_equip_reparlog.IN_REPAIR_MEASURE
     *
     * @mbggenerated
     */
    public void setInRepairMeasure(String inRepairMeasure) {
        this.inRepairMeasure = inRepairMeasure == null ? null : inRepairMeasure.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equip_reparlog.IN_REPAIR_MODE
     *
     * @return the value of lims_equip_reparlog.IN_REPAIR_MODE
     *
     * @mbggenerated
     */
    public String getInRepairMode() {
        return inRepairMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equip_reparlog.IN_REPAIR_MODE
     *
     * @param inRepairMode the value for lims_equip_reparlog.IN_REPAIR_MODE
     *
     * @mbggenerated
     */
    public void setInRepairMode(String inRepairMode) {
        this.inRepairMode = inRepairMode == null ? null : inRepairMode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equip_reparlog.IN_REPAIR_RANK
     *
     * @return the value of lims_equip_reparlog.IN_REPAIR_RANK
     *
     * @mbggenerated
     */
    public String getInRepairRank() {
        return inRepairRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equip_reparlog.IN_REPAIR_RANK
     *
     * @param inRepairRank the value for lims_equip_reparlog.IN_REPAIR_RANK
     *
     * @mbggenerated
     */
    public void setInRepairRank(String inRepairRank) {
        this.inRepairRank = inRepairRank == null ? null : inRepairRank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equip_reparlog.IN_PLAN_TIME
     *
     * @return the value of lims_equip_reparlog.IN_PLAN_TIME
     *
     * @mbggenerated
     */
    public String getInPlanTime() {
        return inPlanTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equip_reparlog.IN_PLAN_TIME
     *
     * @param inPlanTime the value for lims_equip_reparlog.IN_PLAN_TIME
     *
     * @mbggenerated
     */
    public void setInPlanTime(String inPlanTime) {
        this.inPlanTime = inPlanTime == null ? null : inPlanTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equip_reparlog.IN_PRICE
     *
     * @return the value of lims_equip_reparlog.IN_PRICE
     *
     * @mbggenerated
     */
    public String getInPrice() {
        return inPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equip_reparlog.IN_PRICE
     *
     * @param inPrice the value for lims_equip_reparlog.IN_PRICE
     *
     * @mbggenerated
     */
    public void setInPrice(String inPrice) {
        this.inPrice = inPrice == null ? null : inPrice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equip_reparlog.IN_PERSON
     *
     * @return the value of lims_equip_reparlog.IN_PERSON
     *
     * @mbggenerated
     */
    public String getInPerson() {
        return inPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equip_reparlog.IN_PERSON
     *
     * @param inPerson the value for lims_equip_reparlog.IN_PERSON
     *
     * @mbggenerated
     */
    public void setInPerson(String inPerson) {
        this.inPerson = inPerson == null ? null : inPerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equip_reparlog.IN_REPAIR_TIME
     *
     * @return the value of lims_equip_reparlog.IN_REPAIR_TIME
     *
     * @mbggenerated
     */
    public String getInRepairTime() {
        return inRepairTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equip_reparlog.IN_REPAIR_TIME
     *
     * @param inRepairTime the value for lims_equip_reparlog.IN_REPAIR_TIME
     *
     * @mbggenerated
     */
    public void setInRepairTime(String inRepairTime) {
        this.inRepairTime = inRepairTime == null ? null : inRepairTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equip_reparlog.OUT_RESULT
     *
     * @return the value of lims_equip_reparlog.OUT_RESULT
     *
     * @mbggenerated
     */
    public String getOutResult() {
        return outResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equip_reparlog.OUT_RESULT
     *
     * @param outResult the value for lims_equip_reparlog.OUT_RESULT
     *
     * @mbggenerated
     */
    public void setOutResult(String outResult) {
        this.outResult = outResult == null ? null : outResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equip_reparlog.OUT_FAULT_POSITION
     *
     * @return the value of lims_equip_reparlog.OUT_FAULT_POSITION
     *
     * @mbggenerated
     */
    public String getOutFaultPosition() {
        return outFaultPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equip_reparlog.OUT_FAULT_POSITION
     *
     * @param outFaultPosition the value for lims_equip_reparlog.OUT_FAULT_POSITION
     *
     * @mbggenerated
     */
    public void setOutFaultPosition(String outFaultPosition) {
        this.outFaultPosition = outFaultPosition == null ? null : outFaultPosition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equip_reparlog.OUT_REASON
     *
     * @return the value of lims_equip_reparlog.OUT_REASON
     *
     * @mbggenerated
     */
    public String getOutReason() {
        return outReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equip_reparlog.OUT_REASON
     *
     * @param outReason the value for lims_equip_reparlog.OUT_REASON
     *
     * @mbggenerated
     */
    public void setOutReason(String outReason) {
        this.outReason = outReason == null ? null : outReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equip_reparlog.OUT_REPAIR_MEASURE
     *
     * @return the value of lims_equip_reparlog.OUT_REPAIR_MEASURE
     *
     * @mbggenerated
     */
    public String getOutRepairMeasure() {
        return outRepairMeasure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equip_reparlog.OUT_REPAIR_MEASURE
     *
     * @param outRepairMeasure the value for lims_equip_reparlog.OUT_REPAIR_MEASURE
     *
     * @mbggenerated
     */
    public void setOutRepairMeasure(String outRepairMeasure) {
        this.outRepairMeasure = outRepairMeasure == null ? null : outRepairMeasure.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equip_reparlog.OUT_REPAIR_MODE
     *
     * @return the value of lims_equip_reparlog.OUT_REPAIR_MODE
     *
     * @mbggenerated
     */
    public String getOutRepairMode() {
        return outRepairMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equip_reparlog.OUT_REPAIR_MODE
     *
     * @param outRepairMode the value for lims_equip_reparlog.OUT_REPAIR_MODE
     *
     * @mbggenerated
     */
    public void setOutRepairMode(String outRepairMode) {
        this.outRepairMode = outRepairMode == null ? null : outRepairMode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equip_reparlog.OUT_REPAIR_RANK
     *
     * @return the value of lims_equip_reparlog.OUT_REPAIR_RANK
     *
     * @mbggenerated
     */
    public String getOutRepairRank() {
        return outRepairRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equip_reparlog.OUT_REPAIR_RANK
     *
     * @param outRepairRank the value for lims_equip_reparlog.OUT_REPAIR_RANK
     *
     * @mbggenerated
     */
    public void setOutRepairRank(String outRepairRank) {
        this.outRepairRank = outRepairRank == null ? null : outRepairRank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equip_reparlog.OUT_PLAN_TIME
     *
     * @return the value of lims_equip_reparlog.OUT_PLAN_TIME
     *
     * @mbggenerated
     */
    public String getOutPlanTime() {
        return outPlanTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equip_reparlog.OUT_PLAN_TIME
     *
     * @param outPlanTime the value for lims_equip_reparlog.OUT_PLAN_TIME
     *
     * @mbggenerated
     */
    public void setOutPlanTime(String outPlanTime) {
        this.outPlanTime = outPlanTime == null ? null : outPlanTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equip_reparlog.OUT_PRICE
     *
     * @return the value of lims_equip_reparlog.OUT_PRICE
     *
     * @mbggenerated
     */
    public String getOutPrice() {
        return outPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equip_reparlog.OUT_PRICE
     *
     * @param outPrice the value for lims_equip_reparlog.OUT_PRICE
     *
     * @mbggenerated
     */
    public void setOutPrice(String outPrice) {
        this.outPrice = outPrice == null ? null : outPrice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equip_reparlog.OUT_PERSON
     *
     * @return the value of lims_equip_reparlog.OUT_PERSON
     *
     * @mbggenerated
     */
    public String getOutPerson() {
        return outPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equip_reparlog.OUT_PERSON
     *
     * @param outPerson the value for lims_equip_reparlog.OUT_PERSON
     *
     * @mbggenerated
     */
    public void setOutPerson(String outPerson) {
        this.outPerson = outPerson == null ? null : outPerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equip_reparlog.OUT_REPAIR_TIME
     *
     * @return the value of lims_equip_reparlog.OUT_REPAIR_TIME
     *
     * @mbggenerated
     */
    public String getOutRepairTime() {
        return outRepairTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equip_reparlog.OUT_REPAIR_TIME
     *
     * @param outRepairTime the value for lims_equip_reparlog.OUT_REPAIR_TIME
     *
     * @mbggenerated
     */
    public void setOutRepairTime(String outRepairTime) {
        this.outRepairTime = outRepairTime == null ? null : outRepairTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equip_reparlog.VERIFY_MEASURE
     *
     * @return the value of lims_equip_reparlog.VERIFY_MEASURE
     *
     * @mbggenerated
     */
    public String getVerifyMeasure() {
        return verifyMeasure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equip_reparlog.VERIFY_MEASURE
     *
     * @param verifyMeasure the value for lims_equip_reparlog.VERIFY_MEASURE
     *
     * @mbggenerated
     */
    public void setVerifyMeasure(String verifyMeasure) {
        this.verifyMeasure = verifyMeasure == null ? null : verifyMeasure.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equip_reparlog.EQUIP_VERIFY_MODE
     *
     * @return the value of lims_equip_reparlog.EQUIP_VERIFY_MODE
     *
     * @mbggenerated
     */
    public String getEquipVerifyMode() {
        return equipVerifyMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equip_reparlog.EQUIP_VERIFY_MODE
     *
     * @param equipVerifyMode the value for lims_equip_reparlog.EQUIP_VERIFY_MODE
     *
     * @mbggenerated
     */
    public void setEquipVerifyMode(String equipVerifyMode) {
        this.equipVerifyMode = equipVerifyMode == null ? null : equipVerifyMode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equip_reparlog.EQUIP_REPAIR_RESULT
     *
     * @return the value of lims_equip_reparlog.EQUIP_REPAIR_RESULT
     *
     * @mbggenerated
     */
    public String getEquipRepairResult() {
        return equipRepairResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equip_reparlog.EQUIP_REPAIR_RESULT
     *
     * @param equipRepairResult the value for lims_equip_reparlog.EQUIP_REPAIR_RESULT
     *
     * @mbggenerated
     */
    public void setEquipRepairResult(String equipRepairResult) {
        this.equipRepairResult = equipRepairResult == null ? null : equipRepairResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equip_reparlog.REPORT_DONE_TIME
     *
     * @return the value of lims_equip_reparlog.REPORT_DONE_TIME
     *
     * @mbggenerated
     */
    public String getReportDoneTime() {
        return reportDoneTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equip_reparlog.REPORT_DONE_TIME
     *
     * @param reportDoneTime the value for lims_equip_reparlog.REPORT_DONE_TIME
     *
     * @mbggenerated
     */
    public void setReportDoneTime(String reportDoneTime) {
        this.reportDoneTime = reportDoneTime == null ? null : reportDoneTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equip_reparlog.VERIFY_USER
     *
     * @return the value of lims_equip_reparlog.VERIFY_USER
     *
     * @mbggenerated
     */
    public String getVerifyUser() {
        return verifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equip_reparlog.VERIFY_USER
     *
     * @param verifyUser the value for lims_equip_reparlog.VERIFY_USER
     *
     * @mbggenerated
     */
    public void setVerifyUser(String verifyUser) {
        this.verifyUser = verifyUser == null ? null : verifyUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equip_reparlog.VERIFY_TIME
     *
     * @return the value of lims_equip_reparlog.VERIFY_TIME
     *
     * @mbggenerated
     */
    public String getVerifyTime() {
        return verifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equip_reparlog.VERIFY_TIME
     *
     * @param verifyTime the value for lims_equip_reparlog.VERIFY_TIME
     *
     * @mbggenerated
     */
    public void setVerifyTime(String verifyTime) {
        this.verifyTime = verifyTime == null ? null : verifyTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equip_reparlog.APPLICANT
     *
     * @return the value of lims_equip_reparlog.APPLICANT
     *
     * @mbggenerated
     */
    public String getApplicant() {
        return applicant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equip_reparlog.APPLICANT
     *
     * @param applicant the value for lims_equip_reparlog.APPLICANT
     *
     * @mbggenerated
     */
    public void setApplicant(String applicant) {
        this.applicant = applicant == null ? null : applicant.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equip_reparlog.APPLICANT_TIME
     *
     * @return the value of lims_equip_reparlog.APPLICANT_TIME
     *
     * @mbggenerated
     */
    public Date getApplicantTime() {
        return applicantTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equip_reparlog.APPLICANT_TIME
     *
     * @param applicantTime the value for lims_equip_reparlog.APPLICANT_TIME
     *
     * @mbggenerated
     */
    public void setApplicantTime(Date applicantTime) {
        this.applicantTime = applicantTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equip_reparlog.MEMO
     *
     * @return the value of lims_equip_reparlog.MEMO
     *
     * @mbggenerated
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equip_reparlog.MEMO
     *
     * @param memo the value for lims_equip_reparlog.MEMO
     *
     * @mbggenerated
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equip_reparlog.WORKFLOW_NO
     *
     * @return the value of lims_equip_reparlog.WORKFLOW_NO
     *
     * @mbggenerated
     */
    public String getWorkflowNo() {
        return workflowNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equip_reparlog.WORKFLOW_NO
     *
     * @param workflowNo the value for lims_equip_reparlog.WORKFLOW_NO
     *
     * @mbggenerated
     */
    public void setWorkflowNo(String workflowNo) {
        this.workflowNo = workflowNo == null ? null : workflowNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equip_reparlog.REPAIR_STATUS
     *
     * @return the value of lims_equip_reparlog.REPAIR_STATUS
     *
     * @mbggenerated
     */
    public String getRepairStatus() {
        return repairStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equip_reparlog.REPAIR_STATUS
     *
     * @param repairStatus the value for lims_equip_reparlog.REPAIR_STATUS
     *
     * @mbggenerated
     */
    public void setRepairStatus(String repairStatus) {
        this.repairStatus = repairStatus == null ? null : repairStatus.trim();
    }

    public String getAttachmentName() {
        return attachmentName;
    }

    public void setAttachmentName(String attachmentName) {
        this.attachmentName = attachmentName;
    }

    public String getAttachmentId() {
        return attachmentId;
    }

    public void setAttachmentId(String attachmentId) {
        this.attachmentId = attachmentId;
    }

    private String attachmentName; //附件名称
    private String attachmentId;   //附件文件地址

    public Integer getDeptId() {
        return deptId;
    }

    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }

    //
    private Integer deptId; //报修部门id

    public String getCodeTyepName() {
        return codeTyepName;
    }

    public void setCodeTyepName(String codeTyepName) {
        this.codeTyepName = codeTyepName;
    }

    private  String codeTyepName;//现象分类

    public String getDeptName() {  // 部门名称
        return deptName;
    }

    public void setDeptName(String deptName) {
        this.deptName = deptName;
    }

    private String deptName;



}