package com.xoa.model.equipment;

import java.util.Date;

public class LimsEquipScraplist {

    public String getEquipStatusName() {
        return equipStatusName;
    }

    public void setEquipStatusName(String equipStatusName) {
        this.equipStatusName = equipStatusName;
    }

    private String equipStatusName; //资产状态中文名称

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equip_scraplist.SCRAPLIST_ID
     *
     * @mbggenerated
     */
    private Integer scraplistId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equip_scraplist.SCRAPLOG_ID
     *
     * @mbggenerated
     */
    private Integer scraplogId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equip_scraplist.EQUIP_ID
     *
     * @mbggenerated
     */
    private Integer equipId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equip_scraplist.EQUIP_NO
     *
     * @mbggenerated
     */
    private String equipNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equip_scraplist.EQUIP_NAME
     *
     * @mbggenerated
     */
    private String equipName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equip_scraplist.MODEL_NO
     *
     * @mbggenerated
     */
    private String modelNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equip_scraplist.SPEC
     *
     * @mbggenerated
     */
    private String spec;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equip_scraplist.FACTORY_NO
     *
     * @mbggenerated
     */
    private String factoryNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equip_scraplist.SCRAP_DATE
     *
     * @mbggenerated
     */
    private Date scrapDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equip_scraplist.REPORTER
     *
     * @mbggenerated
     */
    private String reporter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equip_scraplist.OPERA
     *
     * @mbggenerated
     */
    private String opera;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equip_scraplist.OPERA_TIME
     *
     * @mbggenerated
     */
    private Date operaTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equip_scraplist.MEMO
     *
     * @mbggenerated
     */
    private String memo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equip_scraplist.WORKFLOW_NO
     *
     * @mbggenerated
     */
    private String workflowNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equip_scraplist.EQUIP_STATUAS_CODE
     *
     * @mbggenerated
     */
    private String equipStatuasCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equip_scraplist.EQUIP_TYPE_ID
     *
     * @mbggenerated
     */
    private Integer equipTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equip_scraplist.EQUIP_TYPE_NAME
     *
     * @mbggenerated
     */
    private String equipTypeName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equip_scraplist.SCRAPLIST_ID
     *
     * @return the value of lims_equip_scraplist.SCRAPLIST_ID
     *
     * @mbggenerated
     */
    public Integer getScraplistId() {
        return scraplistId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equip_scraplist.SCRAPLIST_ID
     *
     * @param scraplistId the value for lims_equip_scraplist.SCRAPLIST_ID
     *
     * @mbggenerated
     */
    public void setScraplistId(Integer scraplistId) {
        this.scraplistId = scraplistId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equip_scraplist.SCRAPLOG_ID
     *
     * @return the value of lims_equip_scraplist.SCRAPLOG_ID
     *
     * @mbggenerated
     */
    public Integer getScraplogId() {
        return scraplogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equip_scraplist.SCRAPLOG_ID
     *
     * @param scraplogId the value for lims_equip_scraplist.SCRAPLOG_ID
     *
     * @mbggenerated
     */
    public void setScraplogId(Integer scraplogId) {
        this.scraplogId = scraplogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equip_scraplist.EQUIP_ID
     *
     * @return the value of lims_equip_scraplist.EQUIP_ID
     *
     * @mbggenerated
     */
    public Integer getEquipId() {
        return equipId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equip_scraplist.EQUIP_ID
     *
     * @param equipId the value for lims_equip_scraplist.EQUIP_ID
     *
     * @mbggenerated
     */
    public void setEquipId(Integer equipId) {
        this.equipId = equipId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equip_scraplist.EQUIP_NO
     *
     * @return the value of lims_equip_scraplist.EQUIP_NO
     *
     * @mbggenerated
     */
    public String getEquipNo() {
        return equipNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equip_scraplist.EQUIP_NO
     *
     * @param equipNo the value for lims_equip_scraplist.EQUIP_NO
     *
     * @mbggenerated
     */
    public void setEquipNo(String equipNo) {
        this.equipNo = equipNo == null ? null : equipNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equip_scraplist.EQUIP_NAME
     *
     * @return the value of lims_equip_scraplist.EQUIP_NAME
     *
     * @mbggenerated
     */
    public String getEquipName() {
        return equipName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equip_scraplist.EQUIP_NAME
     *
     * @param equipName the value for lims_equip_scraplist.EQUIP_NAME
     *
     * @mbggenerated
     */
    public void setEquipName(String equipName) {
        this.equipName = equipName == null ? null : equipName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equip_scraplist.MODEL_NO
     *
     * @return the value of lims_equip_scraplist.MODEL_NO
     *
     * @mbggenerated
     */
    public String getModelNo() {
        return modelNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equip_scraplist.MODEL_NO
     *
     * @param modelNo the value for lims_equip_scraplist.MODEL_NO
     *
     * @mbggenerated
     */
    public void setModelNo(String modelNo) {
        this.modelNo = modelNo == null ? null : modelNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equip_scraplist.SPEC
     *
     * @return the value of lims_equip_scraplist.SPEC
     *
     * @mbggenerated
     */
    public String getSpec() {
        return spec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equip_scraplist.SPEC
     *
     * @param spec the value for lims_equip_scraplist.SPEC
     *
     * @mbggenerated
     */
    public void setSpec(String spec) {
        this.spec = spec == null ? null : spec.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equip_scraplist.FACTORY_NO
     *
     * @return the value of lims_equip_scraplist.FACTORY_NO
     *
     * @mbggenerated
     */
    public String getFactoryNo() {
        return factoryNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equip_scraplist.FACTORY_NO
     *
     * @param factoryNo the value for lims_equip_scraplist.FACTORY_NO
     *
     * @mbggenerated
     */
    public void setFactoryNo(String factoryNo) {
        this.factoryNo = factoryNo == null ? null : factoryNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equip_scraplist.SCRAP_DATE
     *
     * @return the value of lims_equip_scraplist.SCRAP_DATE
     *
     * @mbggenerated
     */
    public Date getScrapDate() {
        return scrapDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equip_scraplist.SCRAP_DATE
     *
     * @param scrapDate the value for lims_equip_scraplist.SCRAP_DATE
     *
     * @mbggenerated
     */
    public void setScrapDate(Date scrapDate) {
        this.scrapDate = scrapDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equip_scraplist.REPORTER
     *
     * @return the value of lims_equip_scraplist.REPORTER
     *
     * @mbggenerated
     */
    public String getReporter() {
        return reporter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equip_scraplist.REPORTER
     *
     * @param reporter the value for lims_equip_scraplist.REPORTER
     *
     * @mbggenerated
     */
    public void setReporter(String reporter) {
        this.reporter = reporter == null ? null : reporter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equip_scraplist.OPERA
     *
     * @return the value of lims_equip_scraplist.OPERA
     *
     * @mbggenerated
     */
    public String getOpera() {
        return opera;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equip_scraplist.OPERA
     *
     * @param opera the value for lims_equip_scraplist.OPERA
     *
     * @mbggenerated
     */
    public void setOpera(String opera) {
        this.opera = opera == null ? null : opera.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equip_scraplist.OPERA_TIME
     *
     * @return the value of lims_equip_scraplist.OPERA_TIME
     *
     * @mbggenerated
     */
    public Date getOperaTime() {
        return operaTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equip_scraplist.OPERA_TIME
     *
     * @param operaTime the value for lims_equip_scraplist.OPERA_TIME
     *
     * @mbggenerated
     */
    public void setOperaTime(Date operaTime) {
        this.operaTime = operaTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equip_scraplist.MEMO
     *
     * @return the value of lims_equip_scraplist.MEMO
     *
     * @mbggenerated
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equip_scraplist.MEMO
     *
     * @param memo the value for lims_equip_scraplist.MEMO
     *
     * @mbggenerated
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equip_scraplist.WORKFLOW_NO
     *
     * @return the value of lims_equip_scraplist.WORKFLOW_NO
     *
     * @mbggenerated
     */
    public String getWorkflowNo() {
        return workflowNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equip_scraplist.WORKFLOW_NO
     *
     * @param workflowNo the value for lims_equip_scraplist.WORKFLOW_NO
     *
     * @mbggenerated
     */
    public void setWorkflowNo(String workflowNo) {
        this.workflowNo = workflowNo == null ? null : workflowNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equip_scraplist.EQUIP_STATUAS_CODE
     *
     * @return the value of lims_equip_scraplist.EQUIP_STATUAS_CODE
     *
     * @mbggenerated
     */
    public String getEquipStatuasCode() {
        return equipStatuasCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equip_scraplist.EQUIP_STATUAS_CODE
     *
     * @param equipStatuasCode the value for lims_equip_scraplist.EQUIP_STATUAS_CODE
     *
     * @mbggenerated
     */
    public void setEquipStatuasCode(String equipStatuasCode) {
        this.equipStatuasCode = equipStatuasCode == null ? null : equipStatuasCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equip_scraplist.EQUIP_TYPE_ID
     *
     * @return the value of lims_equip_scraplist.EQUIP_TYPE_ID
     *
     * @mbggenerated
     */
    public Integer getEquipTypeId() {
        return equipTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equip_scraplist.EQUIP_TYPE_ID
     *
     * @param equipTypeId the value for lims_equip_scraplist.EQUIP_TYPE_ID
     *
     * @mbggenerated
     */
    public void setEquipTypeId(Integer equipTypeId) {
        this.equipTypeId = equipTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equip_scraplist.EQUIP_TYPE_NAME
     *
     * @return the value of lims_equip_scraplist.EQUIP_TYPE_NAME
     *
     * @mbggenerated
     */
    public String getEquipTypeName() {
        return equipTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equip_scraplist.EQUIP_TYPE_NAME
     *
     * @param equipTypeName the value for lims_equip_scraplist.EQUIP_TYPE_NAME
     *
     * @mbggenerated
     */
    public void setEquipTypeName(String equipTypeName) {
        this.equipTypeName = equipTypeName == null ? null : equipTypeName.trim();
    }
}