package com.xoa.model.equipment;

import java.util.Date;

public class LimsEquipInventory {

    private String inveStatus;

    public String getInveStatus() {
        return inveStatus;
    }

    public void setInveStatus(String inveStatus) {
        this.inveStatus = inveStatus;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equip_inventory.DETAIL_ID
     *
     * @mbggenerated
     */
    private Integer detailId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equip_inventory.INVE_ID
     *
     * @mbggenerated
     */
    private Integer inveId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equip_inventory.EQUIP_ID
     *
     * @mbggenerated
     */
    private Integer equipId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equip_inventory.DEPT_ID
     *
     * @mbggenerated
     */
    private Integer deptId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equip_inventory.POSITION_ID
     *
     * @mbggenerated
     */
    private Integer positionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equip_inventory.EQUIP_NO
     *
     * @mbggenerated
     */
    private String equipNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equip_inventory.EQUIP_NAME
     *
     * @mbggenerated
     */
    private String equipName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equip_inventory.EQUIP_STATUAS_CODE
     *
     * @mbggenerated
     */
    private String equipStatuasCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equip_inventory.MODEL_NO
     *
     * @mbggenerated
     */
    private String modelNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equip_inventory.CHECK_USER
     *
     * @mbggenerated
     */
    private String checkUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equip_inventory.CHECK_TIME
     *
     * @mbggenerated
     */
    private Date checkTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equip_inventory.WHETHER_CHANGES
     *
     * @mbggenerated
     */
    private String whetherChanges;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equip_inventory.ASSETS_COST
     *
     * @mbggenerated
     */
    private String assetsCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equip_inventory.MANUFACTURER
     *
     * @mbggenerated
     */
    private String manufacturer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equip_inventory.SUPPLIER
     *
     * @mbggenerated
     */
    private String supplier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equip_inventory.FACTORY_NO
     *
     * @mbggenerated
     */
    private String factoryNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lims_equip_inventory.MEMO
     *
     * @mbggenerated
     */
    private String memo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equip_inventory.DETAIL_ID
     *
     * @return the value of lims_equip_inventory.DETAIL_ID
     *
     * @mbggenerated
     */
    public Integer getDetailId() {
        return detailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equip_inventory.DETAIL_ID
     *
     * @param detailId the value for lims_equip_inventory.DETAIL_ID
     *
     * @mbggenerated
     */
    public void setDetailId(Integer detailId) {
        this.detailId = detailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equip_inventory.INVE_ID
     *
     * @return the value of lims_equip_inventory.INVE_ID
     *
     * @mbggenerated
     */
    public Integer getInveId() {
        return inveId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equip_inventory.INVE_ID
     *
     * @param inveId the value for lims_equip_inventory.INVE_ID
     *
     * @mbggenerated
     */
    public void setInveId(Integer inveId) {
        this.inveId = inveId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equip_inventory.EQUIP_ID
     *
     * @return the value of lims_equip_inventory.EQUIP_ID
     *
     * @mbggenerated
     */
    public Integer getEquipId() {
        return equipId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equip_inventory.EQUIP_ID
     *
     * @param equipId the value for lims_equip_inventory.EQUIP_ID
     *
     * @mbggenerated
     */
    public void setEquipId(Integer equipId) {
        this.equipId = equipId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equip_inventory.DEPT_ID
     *
     * @return the value of lims_equip_inventory.DEPT_ID
     *
     * @mbggenerated
     */
    public Integer getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equip_inventory.DEPT_ID
     *
     * @param deptId the value for lims_equip_inventory.DEPT_ID
     *
     * @mbggenerated
     */
    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equip_inventory.POSITION_ID
     *
     * @return the value of lims_equip_inventory.POSITION_ID
     *
     * @mbggenerated
     */
    public Integer getPositionId() {
        return positionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equip_inventory.POSITION_ID
     *
     * @param positionId the value for lims_equip_inventory.POSITION_ID
     *
     * @mbggenerated
     */
    public void setPositionId(Integer positionId) {
        this.positionId = positionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equip_inventory.EQUIP_NO
     *
     * @return the value of lims_equip_inventory.EQUIP_NO
     *
     * @mbggenerated
     */
    public String getEquipNo() {
        return equipNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equip_inventory.EQUIP_NO
     *
     * @param equipNo the value for lims_equip_inventory.EQUIP_NO
     *
     * @mbggenerated
     */
    public void setEquipNo(String equipNo) {
        this.equipNo = equipNo == null ? null : equipNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equip_inventory.EQUIP_NAME
     *
     * @return the value of lims_equip_inventory.EQUIP_NAME
     *
     * @mbggenerated
     */
    public String getEquipName() {
        return equipName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equip_inventory.EQUIP_NAME
     *
     * @param equipName the value for lims_equip_inventory.EQUIP_NAME
     *
     * @mbggenerated
     */
    public void setEquipName(String equipName) {
        this.equipName = equipName == null ? null : equipName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equip_inventory.EQUIP_STATUAS_CODE
     *
     * @return the value of lims_equip_inventory.EQUIP_STATUAS_CODE
     *
     * @mbggenerated
     */
    public String getEquipStatuasCode() {
        return equipStatuasCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equip_inventory.EQUIP_STATUAS_CODE
     *
     * @param equipStatuasCode the value for lims_equip_inventory.EQUIP_STATUAS_CODE
     *
     * @mbggenerated
     */
    public void setEquipStatuasCode(String equipStatuasCode) {
        this.equipStatuasCode = equipStatuasCode == null ? null : equipStatuasCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equip_inventory.MODEL_NO
     *
     * @return the value of lims_equip_inventory.MODEL_NO
     *
     * @mbggenerated
     */
    public String getModelNo() {
        return modelNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equip_inventory.MODEL_NO
     *
     * @param modelNo the value for lims_equip_inventory.MODEL_NO
     *
     * @mbggenerated
     */
    public void setModelNo(String modelNo) {
        this.modelNo = modelNo == null ? null : modelNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equip_inventory.CHECK_USER
     *
     * @return the value of lims_equip_inventory.CHECK_USER
     *
     * @mbggenerated
     */
    public String getCheckUser() {
        return checkUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equip_inventory.CHECK_USER
     *
     * @param checkUser the value for lims_equip_inventory.CHECK_USER
     *
     * @mbggenerated
     */
    public void setCheckUser(String checkUser) {
        this.checkUser = checkUser == null ? null : checkUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equip_inventory.CHECK_TIME
     *
     * @return the value of lims_equip_inventory.CHECK_TIME
     *
     * @mbggenerated
     */
    public Date getCheckTime() {
        return checkTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equip_inventory.CHECK_TIME
     *
     * @param checkTime the value for lims_equip_inventory.CHECK_TIME
     *
     * @mbggenerated
     */
    public void setCheckTime(Date checkTime) {
        this.checkTime = checkTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equip_inventory.WHETHER_CHANGES
     *
     * @return the value of lims_equip_inventory.WHETHER_CHANGES
     *
     * @mbggenerated
     */
    public String getWhetherChanges() {
        return whetherChanges;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equip_inventory.WHETHER_CHANGES
     *
     * @param whetherChanges the value for lims_equip_inventory.WHETHER_CHANGES
     *
     * @mbggenerated
     */
    public void setWhetherChanges(String whetherChanges) {
        this.whetherChanges = whetherChanges == null ? null : whetherChanges.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equip_inventory.ASSETS_COST
     *
     * @return the value of lims_equip_inventory.ASSETS_COST
     *
     * @mbggenerated
     */
    public String getAssetsCost() {
        return assetsCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equip_inventory.ASSETS_COST
     *
     * @param assetsCost the value for lims_equip_inventory.ASSETS_COST
     *
     * @mbggenerated
     */
    public void setAssetsCost(String assetsCost) {
        this.assetsCost = assetsCost == null ? null : assetsCost.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equip_inventory.MANUFACTURER
     *
     * @return the value of lims_equip_inventory.MANUFACTURER
     *
     * @mbggenerated
     */
    public String getManufacturer() {
        return manufacturer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equip_inventory.MANUFACTURER
     *
     * @param manufacturer the value for lims_equip_inventory.MANUFACTURER
     *
     * @mbggenerated
     */
    public void setManufacturer(String manufacturer) {
        this.manufacturer = manufacturer == null ? null : manufacturer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equip_inventory.SUPPLIER
     *
     * @return the value of lims_equip_inventory.SUPPLIER
     *
     * @mbggenerated
     */
    public String getSupplier() {
        return supplier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equip_inventory.SUPPLIER
     *
     * @param supplier the value for lims_equip_inventory.SUPPLIER
     *
     * @mbggenerated
     */
    public void setSupplier(String supplier) {
        this.supplier = supplier == null ? null : supplier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equip_inventory.FACTORY_NO
     *
     * @return the value of lims_equip_inventory.FACTORY_NO
     *
     * @mbggenerated
     */
    public String getFactoryNo() {
        return factoryNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equip_inventory.FACTORY_NO
     *
     * @param factoryNo the value for lims_equip_inventory.FACTORY_NO
     *
     * @mbggenerated
     */
    public void setFactoryNo(String factoryNo) {
        this.factoryNo = factoryNo == null ? null : factoryNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lims_equip_inventory.MEMO
     *
     * @return the value of lims_equip_inventory.MEMO
     *
     * @mbggenerated
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lims_equip_inventory.MEMO
     *
     * @param memo the value for lims_equip_inventory.MEMO
     *
     * @mbggenerated
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }
}