package com.xoa.model.meet;

import java.util.ArrayList;
import java.util.List;

public class MeetingExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table meeting
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table meeting
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table meeting
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting
     *
     * @mbggenerated
     */
    public MeetingExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table meeting
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSidIsNull() {
            addCriterion("SID is null");
            return (Criteria) this;
        }

        public Criteria andSidIsNotNull() {
            addCriterion("SID is not null");
            return (Criteria) this;
        }

        public Criteria andSidEqualTo(Integer value) {
            addCriterion("SID =", value, "sid");
            return (Criteria) this;
        }

        public Criteria andSidNotEqualTo(Integer value) {
            addCriterion("SID <>", value, "sid");
            return (Criteria) this;
        }

        public Criteria andSidGreaterThan(Integer value) {
            addCriterion("SID >", value, "sid");
            return (Criteria) this;
        }

        public Criteria andSidGreaterThanOrEqualTo(Integer value) {
            addCriterion("SID >=", value, "sid");
            return (Criteria) this;
        }

        public Criteria andSidLessThan(Integer value) {
            addCriterion("SID <", value, "sid");
            return (Criteria) this;
        }

        public Criteria andSidLessThanOrEqualTo(Integer value) {
            addCriterion("SID <=", value, "sid");
            return (Criteria) this;
        }

        public Criteria andSidIn(List<Integer> values) {
            addCriterion("SID in", values, "sid");
            return (Criteria) this;
        }

        public Criteria andSidNotIn(List<Integer> values) {
            addCriterion("SID not in", values, "sid");
            return (Criteria) this;
        }

        public Criteria andSidBetween(Integer value1, Integer value2) {
            addCriterion("SID between", value1, value2, "sid");
            return (Criteria) this;
        }

        public Criteria andSidNotBetween(Integer value1, Integer value2) {
            addCriterion("SID not between", value1, value2, "sid");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Long value) {
            addCriterion("CREATE_TIME =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Long value) {
            addCriterion("CREATE_TIME <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Long value) {
            addCriterion("CREATE_TIME >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Long value) {
            addCriterion("CREATE_TIME >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Long value) {
            addCriterion("CREATE_TIME <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Long value) {
            addCriterion("CREATE_TIME <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Long> values) {
            addCriterion("CREATE_TIME in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Long> values) {
            addCriterion("CREATE_TIME not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Long value1, Long value2) {
            addCriterion("CREATE_TIME between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Long value1, Long value2) {
            addCriterion("CREATE_TIME not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNull() {
            addCriterion("END_TIME is null");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNotNull() {
            addCriterion("END_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andEndTimeEqualTo(Long value) {
            addCriterion("END_TIME =", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotEqualTo(Long value) {
            addCriterion("END_TIME <>", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThan(Long value) {
            addCriterion("END_TIME >", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThanOrEqualTo(Long value) {
            addCriterion("END_TIME >=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThan(Long value) {
            addCriterion("END_TIME <", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThanOrEqualTo(Long value) {
            addCriterion("END_TIME <=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIn(List<Long> values) {
            addCriterion("END_TIME in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotIn(List<Long> values) {
            addCriterion("END_TIME not in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeBetween(Long value1, Long value2) {
            addCriterion("END_TIME between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotBetween(Long value1, Long value2) {
            addCriterion("END_TIME not between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andIsWriteCalednarIsNull() {
            addCriterion("IS_WRITE_CALEDNAR is null");
            return (Criteria) this;
        }

        public Criteria andIsWriteCalednarIsNotNull() {
            addCriterion("IS_WRITE_CALEDNAR is not null");
            return (Criteria) this;
        }

        public Criteria andIsWriteCalednarEqualTo(Integer value) {
            addCriterion("IS_WRITE_CALEDNAR =", value, "isWriteCalednar");
            return (Criteria) this;
        }

        public Criteria andIsWriteCalednarNotEqualTo(Integer value) {
            addCriterion("IS_WRITE_CALEDNAR <>", value, "isWriteCalednar");
            return (Criteria) this;
        }

        public Criteria andIsWriteCalednarGreaterThan(Integer value) {
            addCriterion("IS_WRITE_CALEDNAR >", value, "isWriteCalednar");
            return (Criteria) this;
        }

        public Criteria andIsWriteCalednarGreaterThanOrEqualTo(Integer value) {
            addCriterion("IS_WRITE_CALEDNAR >=", value, "isWriteCalednar");
            return (Criteria) this;
        }

        public Criteria andIsWriteCalednarLessThan(Integer value) {
            addCriterion("IS_WRITE_CALEDNAR <", value, "isWriteCalednar");
            return (Criteria) this;
        }

        public Criteria andIsWriteCalednarLessThanOrEqualTo(Integer value) {
            addCriterion("IS_WRITE_CALEDNAR <=", value, "isWriteCalednar");
            return (Criteria) this;
        }

        public Criteria andIsWriteCalednarIn(List<Integer> values) {
            addCriterion("IS_WRITE_CALEDNAR in", values, "isWriteCalednar");
            return (Criteria) this;
        }

        public Criteria andIsWriteCalednarNotIn(List<Integer> values) {
            addCriterion("IS_WRITE_CALEDNAR not in", values, "isWriteCalednar");
            return (Criteria) this;
        }

        public Criteria andIsWriteCalednarBetween(Integer value1, Integer value2) {
            addCriterion("IS_WRITE_CALEDNAR between", value1, value2, "isWriteCalednar");
            return (Criteria) this;
        }

        public Criteria andIsWriteCalednarNotBetween(Integer value1, Integer value2) {
            addCriterion("IS_WRITE_CALEDNAR not between", value1, value2, "isWriteCalednar");
            return (Criteria) this;
        }

        public Criteria andMeetNameIsNull() {
            addCriterion("MEET_NAME is null");
            return (Criteria) this;
        }

        public Criteria andMeetNameIsNotNull() {
            addCriterion("MEET_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andMeetNameEqualTo(String value) {
            addCriterion("MEET_NAME =", value, "meetName");
            return (Criteria) this;
        }

        public Criteria andMeetNameNotEqualTo(String value) {
            addCriterion("MEET_NAME <>", value, "meetName");
            return (Criteria) this;
        }

        public Criteria andMeetNameGreaterThan(String value) {
            addCriterion("MEET_NAME >", value, "meetName");
            return (Criteria) this;
        }

        public Criteria andMeetNameGreaterThanOrEqualTo(String value) {
            addCriterion("MEET_NAME >=", value, "meetName");
            return (Criteria) this;
        }

        public Criteria andMeetNameLessThan(String value) {
            addCriterion("MEET_NAME <", value, "meetName");
            return (Criteria) this;
        }

        public Criteria andMeetNameLessThanOrEqualTo(String value) {
            addCriterion("MEET_NAME <=", value, "meetName");
            return (Criteria) this;
        }

        public Criteria andMeetNameLike(String value) {
            addCriterion("MEET_NAME like", value, "meetName");
            return (Criteria) this;
        }

        public Criteria andMeetNameNotLike(String value) {
            addCriterion("MEET_NAME not like", value, "meetName");
            return (Criteria) this;
        }

        public Criteria andMeetNameIn(List<String> values) {
            addCriterion("MEET_NAME in", values, "meetName");
            return (Criteria) this;
        }

        public Criteria andMeetNameNotIn(List<String> values) {
            addCriterion("MEET_NAME not in", values, "meetName");
            return (Criteria) this;
        }

        public Criteria andMeetNameBetween(String value1, String value2) {
            addCriterion("MEET_NAME between", value1, value2, "meetName");
            return (Criteria) this;
        }

        public Criteria andMeetNameNotBetween(String value1, String value2) {
            addCriterion("MEET_NAME not between", value1, value2, "meetName");
            return (Criteria) this;
        }

        public Criteria andResendHourIsNull() {
            addCriterion("RESEND_HOUR is null");
            return (Criteria) this;
        }

        public Criteria andResendHourIsNotNull() {
            addCriterion("RESEND_HOUR is not null");
            return (Criteria) this;
        }

        public Criteria andResendHourEqualTo(Integer value) {
            addCriterion("RESEND_HOUR =", value, "resendHour");
            return (Criteria) this;
        }

        public Criteria andResendHourNotEqualTo(Integer value) {
            addCriterion("RESEND_HOUR <>", value, "resendHour");
            return (Criteria) this;
        }

        public Criteria andResendHourGreaterThan(Integer value) {
            addCriterion("RESEND_HOUR >", value, "resendHour");
            return (Criteria) this;
        }

        public Criteria andResendHourGreaterThanOrEqualTo(Integer value) {
            addCriterion("RESEND_HOUR >=", value, "resendHour");
            return (Criteria) this;
        }

        public Criteria andResendHourLessThan(Integer value) {
            addCriterion("RESEND_HOUR <", value, "resendHour");
            return (Criteria) this;
        }

        public Criteria andResendHourLessThanOrEqualTo(Integer value) {
            addCriterion("RESEND_HOUR <=", value, "resendHour");
            return (Criteria) this;
        }

        public Criteria andResendHourIn(List<Integer> values) {
            addCriterion("RESEND_HOUR in", values, "resendHour");
            return (Criteria) this;
        }

        public Criteria andResendHourNotIn(List<Integer> values) {
            addCriterion("RESEND_HOUR not in", values, "resendHour");
            return (Criteria) this;
        }

        public Criteria andResendHourBetween(Integer value1, Integer value2) {
            addCriterion("RESEND_HOUR between", value1, value2, "resendHour");
            return (Criteria) this;
        }

        public Criteria andResendHourNotBetween(Integer value1, Integer value2) {
            addCriterion("RESEND_HOUR not between", value1, value2, "resendHour");
            return (Criteria) this;
        }

        public Criteria andResendMinuteIsNull() {
            addCriterion("RESEND_MINUTE is null");
            return (Criteria) this;
        }

        public Criteria andResendMinuteIsNotNull() {
            addCriterion("RESEND_MINUTE is not null");
            return (Criteria) this;
        }

        public Criteria andResendMinuteEqualTo(Integer value) {
            addCriterion("RESEND_MINUTE =", value, "resendMinute");
            return (Criteria) this;
        }

        public Criteria andResendMinuteNotEqualTo(Integer value) {
            addCriterion("RESEND_MINUTE <>", value, "resendMinute");
            return (Criteria) this;
        }

        public Criteria andResendMinuteGreaterThan(Integer value) {
            addCriterion("RESEND_MINUTE >", value, "resendMinute");
            return (Criteria) this;
        }

        public Criteria andResendMinuteGreaterThanOrEqualTo(Integer value) {
            addCriterion("RESEND_MINUTE >=", value, "resendMinute");
            return (Criteria) this;
        }

        public Criteria andResendMinuteLessThan(Integer value) {
            addCriterion("RESEND_MINUTE <", value, "resendMinute");
            return (Criteria) this;
        }

        public Criteria andResendMinuteLessThanOrEqualTo(Integer value) {
            addCriterion("RESEND_MINUTE <=", value, "resendMinute");
            return (Criteria) this;
        }

        public Criteria andResendMinuteIn(List<Integer> values) {
            addCriterion("RESEND_MINUTE in", values, "resendMinute");
            return (Criteria) this;
        }

        public Criteria andResendMinuteNotIn(List<Integer> values) {
            addCriterion("RESEND_MINUTE not in", values, "resendMinute");
            return (Criteria) this;
        }

        public Criteria andResendMinuteBetween(Integer value1, Integer value2) {
            addCriterion("RESEND_MINUTE between", value1, value2, "resendMinute");
            return (Criteria) this;
        }

        public Criteria andResendMinuteNotBetween(Integer value1, Integer value2) {
            addCriterion("RESEND_MINUTE not between", value1, value2, "resendMinute");
            return (Criteria) this;
        }

        public Criteria andResendSeveralIsNull() {
            addCriterion("RESEND_SEVERAL is null");
            return (Criteria) this;
        }

        public Criteria andResendSeveralIsNotNull() {
            addCriterion("RESEND_SEVERAL is not null");
            return (Criteria) this;
        }

        public Criteria andResendSeveralEqualTo(Integer value) {
            addCriterion("RESEND_SEVERAL =", value, "resendSeveral");
            return (Criteria) this;
        }

        public Criteria andResendSeveralNotEqualTo(Integer value) {
            addCriterion("RESEND_SEVERAL <>", value, "resendSeveral");
            return (Criteria) this;
        }

        public Criteria andResendSeveralGreaterThan(Integer value) {
            addCriterion("RESEND_SEVERAL >", value, "resendSeveral");
            return (Criteria) this;
        }

        public Criteria andResendSeveralGreaterThanOrEqualTo(Integer value) {
            addCriterion("RESEND_SEVERAL >=", value, "resendSeveral");
            return (Criteria) this;
        }

        public Criteria andResendSeveralLessThan(Integer value) {
            addCriterion("RESEND_SEVERAL <", value, "resendSeveral");
            return (Criteria) this;
        }

        public Criteria andResendSeveralLessThanOrEqualTo(Integer value) {
            addCriterion("RESEND_SEVERAL <=", value, "resendSeveral");
            return (Criteria) this;
        }

        public Criteria andResendSeveralIn(List<Integer> values) {
            addCriterion("RESEND_SEVERAL in", values, "resendSeveral");
            return (Criteria) this;
        }

        public Criteria andResendSeveralNotIn(List<Integer> values) {
            addCriterion("RESEND_SEVERAL not in", values, "resendSeveral");
            return (Criteria) this;
        }

        public Criteria andResendSeveralBetween(Integer value1, Integer value2) {
            addCriterion("RESEND_SEVERAL between", value1, value2, "resendSeveral");
            return (Criteria) this;
        }

        public Criteria andResendSeveralNotBetween(Integer value1, Integer value2) {
            addCriterion("RESEND_SEVERAL not between", value1, value2, "resendSeveral");
            return (Criteria) this;
        }

        public Criteria andSms2RemindIsNull() {
            addCriterion("SMS2_REMIND is null");
            return (Criteria) this;
        }

        public Criteria andSms2RemindIsNotNull() {
            addCriterion("SMS2_REMIND is not null");
            return (Criteria) this;
        }

        public Criteria andSms2RemindEqualTo(String value) {
            addCriterion("SMS2_REMIND =", value, "sms2Remind");
            return (Criteria) this;
        }

        public Criteria andSms2RemindNotEqualTo(String value) {
            addCriterion("SMS2_REMIND <>", value, "sms2Remind");
            return (Criteria) this;
        }

        public Criteria andSms2RemindGreaterThan(String value) {
            addCriterion("SMS2_REMIND >", value, "sms2Remind");
            return (Criteria) this;
        }

        public Criteria andSms2RemindGreaterThanOrEqualTo(String value) {
            addCriterion("SMS2_REMIND >=", value, "sms2Remind");
            return (Criteria) this;
        }

        public Criteria andSms2RemindLessThan(String value) {
            addCriterion("SMS2_REMIND <", value, "sms2Remind");
            return (Criteria) this;
        }

        public Criteria andSms2RemindLessThanOrEqualTo(String value) {
            addCriterion("SMS2_REMIND <=", value, "sms2Remind");
            return (Criteria) this;
        }

        public Criteria andSms2RemindLike(String value) {
            addCriterion("SMS2_REMIND like", value, "sms2Remind");
            return (Criteria) this;
        }

        public Criteria andSms2RemindNotLike(String value) {
            addCriterion("SMS2_REMIND not like", value, "sms2Remind");
            return (Criteria) this;
        }

        public Criteria andSms2RemindIn(List<String> values) {
            addCriterion("SMS2_REMIND in", values, "sms2Remind");
            return (Criteria) this;
        }

        public Criteria andSms2RemindNotIn(List<String> values) {
            addCriterion("SMS2_REMIND not in", values, "sms2Remind");
            return (Criteria) this;
        }

        public Criteria andSms2RemindBetween(String value1, String value2) {
            addCriterion("SMS2_REMIND between", value1, value2, "sms2Remind");
            return (Criteria) this;
        }

        public Criteria andSms2RemindNotBetween(String value1, String value2) {
            addCriterion("SMS2_REMIND not between", value1, value2, "sms2Remind");
            return (Criteria) this;
        }

        public Criteria andSmsRemindIsNull() {
            addCriterion("SMS_REMIND is null");
            return (Criteria) this;
        }

        public Criteria andSmsRemindIsNotNull() {
            addCriterion("SMS_REMIND is not null");
            return (Criteria) this;
        }

        public Criteria andSmsRemindEqualTo(String value) {
            addCriterion("SMS_REMIND =", value, "smsRemind");
            return (Criteria) this;
        }

        public Criteria andSmsRemindNotEqualTo(String value) {
            addCriterion("SMS_REMIND <>", value, "smsRemind");
            return (Criteria) this;
        }

        public Criteria andSmsRemindGreaterThan(String value) {
            addCriterion("SMS_REMIND >", value, "smsRemind");
            return (Criteria) this;
        }

        public Criteria andSmsRemindGreaterThanOrEqualTo(String value) {
            addCriterion("SMS_REMIND >=", value, "smsRemind");
            return (Criteria) this;
        }

        public Criteria andSmsRemindLessThan(String value) {
            addCriterion("SMS_REMIND <", value, "smsRemind");
            return (Criteria) this;
        }

        public Criteria andSmsRemindLessThanOrEqualTo(String value) {
            addCriterion("SMS_REMIND <=", value, "smsRemind");
            return (Criteria) this;
        }

        public Criteria andSmsRemindLike(String value) {
            addCriterion("SMS_REMIND like", value, "smsRemind");
            return (Criteria) this;
        }

        public Criteria andSmsRemindNotLike(String value) {
            addCriterion("SMS_REMIND not like", value, "smsRemind");
            return (Criteria) this;
        }

        public Criteria andSmsRemindIn(List<String> values) {
            addCriterion("SMS_REMIND in", values, "smsRemind");
            return (Criteria) this;
        }

        public Criteria andSmsRemindNotIn(List<String> values) {
            addCriterion("SMS_REMIND not in", values, "smsRemind");
            return (Criteria) this;
        }

        public Criteria andSmsRemindBetween(String value1, String value2) {
            addCriterion("SMS_REMIND between", value1, value2, "smsRemind");
            return (Criteria) this;
        }

        public Criteria andSmsRemindNotBetween(String value1, String value2) {
            addCriterion("SMS_REMIND not between", value1, value2, "smsRemind");
            return (Criteria) this;
        }

        public Criteria andStartTimeIsNull() {
            addCriterion("START_TIME is null");
            return (Criteria) this;
        }

        public Criteria andStartTimeIsNotNull() {
            addCriterion("START_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andStartTimeEqualTo(Long value) {
            addCriterion("START_TIME =", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotEqualTo(Long value) {
            addCriterion("START_TIME <>", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeGreaterThan(Long value) {
            addCriterion("START_TIME >", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeGreaterThanOrEqualTo(Long value) {
            addCriterion("START_TIME >=", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeLessThan(Long value) {
            addCriterion("START_TIME <", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeLessThanOrEqualTo(Long value) {
            addCriterion("START_TIME <=", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeIn(List<Long> values) {
            addCriterion("START_TIME in", values, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotIn(List<Long> values) {
            addCriterion("START_TIME not in", values, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeBetween(Long value1, Long value2) {
            addCriterion("START_TIME between", value1, value2, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotBetween(Long value1, Long value2) {
            addCriterion("START_TIME not between", value1, value2, "startTime");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("STATUS is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("STATUS =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("STATUS <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("STATUS >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("STATUS >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("STATUS <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("STATUS <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("STATUS in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("STATUS not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("STATUS between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("STATUS not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andSubjectIsNull() {
            addCriterion("SUBJECT is null");
            return (Criteria) this;
        }

        public Criteria andSubjectIsNotNull() {
            addCriterion("SUBJECT is not null");
            return (Criteria) this;
        }

        public Criteria andSubjectEqualTo(String value) {
            addCriterion("SUBJECT =", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectNotEqualTo(String value) {
            addCriterion("SUBJECT <>", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectGreaterThan(String value) {
            addCriterion("SUBJECT >", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectGreaterThanOrEqualTo(String value) {
            addCriterion("SUBJECT >=", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectLessThan(String value) {
            addCriterion("SUBJECT <", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectLessThanOrEqualTo(String value) {
            addCriterion("SUBJECT <=", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectLike(String value) {
            addCriterion("SUBJECT like", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectNotLike(String value) {
            addCriterion("SUBJECT not like", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectIn(List<String> values) {
            addCriterion("SUBJECT in", values, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectNotIn(List<String> values) {
            addCriterion("SUBJECT not in", values, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectBetween(String value1, String value2) {
            addCriterion("SUBJECT between", value1, value2, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectNotBetween(String value1, String value2) {
            addCriterion("SUBJECT not between", value1, value2, "subject");
            return (Criteria) this;
        }

        public Criteria andManagerIdIsNull() {
            addCriterion("MANAGER_ID is null");
            return (Criteria) this;
        }

        public Criteria andManagerIdIsNotNull() {
            addCriterion("MANAGER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andManagerIdEqualTo(Integer value) {
            addCriterion("MANAGER_ID =", value, "managerId");
            return (Criteria) this;
        }

        public Criteria andManagerIdNotEqualTo(Integer value) {
            addCriterion("MANAGER_ID <>", value, "managerId");
            return (Criteria) this;
        }

        public Criteria andManagerIdGreaterThan(Integer value) {
            addCriterion("MANAGER_ID >", value, "managerId");
            return (Criteria) this;
        }

        public Criteria andManagerIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("MANAGER_ID >=", value, "managerId");
            return (Criteria) this;
        }

        public Criteria andManagerIdLessThan(Integer value) {
            addCriterion("MANAGER_ID <", value, "managerId");
            return (Criteria) this;
        }

        public Criteria andManagerIdLessThanOrEqualTo(Integer value) {
            addCriterion("MANAGER_ID <=", value, "managerId");
            return (Criteria) this;
        }

        public Criteria andManagerIdIn(List<Integer> values) {
            addCriterion("MANAGER_ID in", values, "managerId");
            return (Criteria) this;
        }

        public Criteria andManagerIdNotIn(List<Integer> values) {
            addCriterion("MANAGER_ID not in", values, "managerId");
            return (Criteria) this;
        }

        public Criteria andManagerIdBetween(Integer value1, Integer value2) {
            addCriterion("MANAGER_ID between", value1, value2, "managerId");
            return (Criteria) this;
        }

        public Criteria andManagerIdNotBetween(Integer value1, Integer value2) {
            addCriterion("MANAGER_ID not between", value1, value2, "managerId");
            return (Criteria) this;
        }

        public Criteria andMeetRoomIdIsNull() {
            addCriterion("MEET_ROOM_ID is null");
            return (Criteria) this;
        }

        public Criteria andMeetRoomIdIsNotNull() {
            addCriterion("MEET_ROOM_ID is not null");
            return (Criteria) this;
        }

        public Criteria andMeetRoomIdEqualTo(Integer value) {
            addCriterion("MEET_ROOM_ID =", value, "meetRoomId");
            return (Criteria) this;
        }

        public Criteria andMeetRoomIdNotEqualTo(Integer value) {
            addCriterion("MEET_ROOM_ID <>", value, "meetRoomId");
            return (Criteria) this;
        }

        public Criteria andMeetRoomIdGreaterThan(Integer value) {
            addCriterion("MEET_ROOM_ID >", value, "meetRoomId");
            return (Criteria) this;
        }

        public Criteria andMeetRoomIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("MEET_ROOM_ID >=", value, "meetRoomId");
            return (Criteria) this;
        }

        public Criteria andMeetRoomIdLessThan(Integer value) {
            addCriterion("MEET_ROOM_ID <", value, "meetRoomId");
            return (Criteria) this;
        }

        public Criteria andMeetRoomIdLessThanOrEqualTo(Integer value) {
            addCriterion("MEET_ROOM_ID <=", value, "meetRoomId");
            return (Criteria) this;
        }

        public Criteria andMeetRoomIdIn(List<Integer> values) {
            addCriterion("MEET_ROOM_ID in", values, "meetRoomId");
            return (Criteria) this;
        }

        public Criteria andMeetRoomIdNotIn(List<Integer> values) {
            addCriterion("MEET_ROOM_ID not in", values, "meetRoomId");
            return (Criteria) this;
        }

        public Criteria andMeetRoomIdBetween(Integer value1, Integer value2) {
            addCriterion("MEET_ROOM_ID between", value1, value2, "meetRoomId");
            return (Criteria) this;
        }

        public Criteria andMeetRoomIdNotBetween(Integer value1, Integer value2) {
            addCriterion("MEET_ROOM_ID not between", value1, value2, "meetRoomId");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("USER_ID is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("USER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("USER_ID =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("USER_ID <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("USER_ID >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("USER_ID >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("USER_ID <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("USER_ID <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Integer> values) {
            addCriterion("USER_ID in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Integer> values) {
            addCriterion("USER_ID not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("USER_ID between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("USER_ID not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andRecorderIdIsNull() {
            addCriterion("RECORDER_ID is null");
            return (Criteria) this;
        }

        public Criteria andRecorderIdIsNotNull() {
            addCriterion("RECORDER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andRecorderIdEqualTo(Integer value) {
            addCriterion("RECORDER_ID =", value, "recorderId");
            return (Criteria) this;
        }

        public Criteria andRecorderIdNotEqualTo(Integer value) {
            addCriterion("RECORDER_ID <>", value, "recorderId");
            return (Criteria) this;
        }

        public Criteria andRecorderIdGreaterThan(Integer value) {
            addCriterion("RECORDER_ID >", value, "recorderId");
            return (Criteria) this;
        }

        public Criteria andRecorderIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("RECORDER_ID >=", value, "recorderId");
            return (Criteria) this;
        }

        public Criteria andRecorderIdLessThan(Integer value) {
            addCriterion("RECORDER_ID <", value, "recorderId");
            return (Criteria) this;
        }

        public Criteria andRecorderIdLessThanOrEqualTo(Integer value) {
            addCriterion("RECORDER_ID <=", value, "recorderId");
            return (Criteria) this;
        }

        public Criteria andRecorderIdIn(List<Integer> values) {
            addCriterion("RECORDER_ID in", values, "recorderId");
            return (Criteria) this;
        }

        public Criteria andRecorderIdNotIn(List<Integer> values) {
            addCriterion("RECORDER_ID not in", values, "recorderId");
            return (Criteria) this;
        }

        public Criteria andRecorderIdBetween(Integer value1, Integer value2) {
            addCriterion("RECORDER_ID between", value1, value2, "recorderId");
            return (Criteria) this;
        }

        public Criteria andRecorderIdNotBetween(Integer value1, Integer value2) {
            addCriterion("RECORDER_ID not between", value1, value2, "recorderId");
            return (Criteria) this;
        }

        public Criteria andIsuploadsummaryIsNull() {
            addCriterion("ISUPLOADSUMMARY is null");
            return (Criteria) this;
        }

        public Criteria andIsuploadsummaryIsNotNull() {
            addCriterion("ISUPLOADSUMMARY is not null");
            return (Criteria) this;
        }

        public Criteria andIsuploadsummaryEqualTo(String value) {
            addCriterion("ISUPLOADSUMMARY =", value, "isuploadsummary");
            return (Criteria) this;
        }

        public Criteria andIsuploadsummaryNotEqualTo(String value) {
            addCriterion("ISUPLOADSUMMARY <>", value, "isuploadsummary");
            return (Criteria) this;
        }

        public Criteria andIsuploadsummaryGreaterThan(String value) {
            addCriterion("ISUPLOADSUMMARY >", value, "isuploadsummary");
            return (Criteria) this;
        }

        public Criteria andIsuploadsummaryGreaterThanOrEqualTo(String value) {
            addCriterion("ISUPLOADSUMMARY >=", value, "isuploadsummary");
            return (Criteria) this;
        }

        public Criteria andIsuploadsummaryLessThan(String value) {
            addCriterion("ISUPLOADSUMMARY <", value, "isuploadsummary");
            return (Criteria) this;
        }

        public Criteria andIsuploadsummaryLessThanOrEqualTo(String value) {
            addCriterion("ISUPLOADSUMMARY <=", value, "isuploadsummary");
            return (Criteria) this;
        }

        public Criteria andIsuploadsummaryLike(String value) {
            addCriterion("ISUPLOADSUMMARY like", value, "isuploadsummary");
            return (Criteria) this;
        }

        public Criteria andIsuploadsummaryNotLike(String value) {
            addCriterion("ISUPLOADSUMMARY not like", value, "isuploadsummary");
            return (Criteria) this;
        }

        public Criteria andIsuploadsummaryIn(List<String> values) {
            addCriterion("ISUPLOADSUMMARY in", values, "isuploadsummary");
            return (Criteria) this;
        }

        public Criteria andIsuploadsummaryNotIn(List<String> values) {
            addCriterion("ISUPLOADSUMMARY not in", values, "isuploadsummary");
            return (Criteria) this;
        }

        public Criteria andIsuploadsummaryBetween(String value1, String value2) {
            addCriterion("ISUPLOADSUMMARY between", value1, value2, "isuploadsummary");
            return (Criteria) this;
        }

        public Criteria andIsuploadsummaryNotBetween(String value1, String value2) {
            addCriterion("ISUPLOADSUMMARY not between", value1, value2, "isuploadsummary");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table meeting
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table meeting
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}