package com.xoa.model.meet;

public class MeetingEquuipment {
    private Integer sid;//自动递增ID
    private String equipmentName;//会议设备名称
    private String equipmentNo;//会议设备编号
    private String groupNo; //同类设备名称
    private Integer status; //设备状态  0-正常 1-不可用
    private Integer meetingRoomId;//会议室ID
    private String remark; //设备描述

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_equuipment.SID
     *
     * @return the value of meeting_equuipment.SID
     *
     * @mbggenerated
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_equuipment.SID
     *
     * @param sid the value for meeting_equuipment.SID
     *
     * @mbggenerated
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_equuipment.EQUIPMENT_NAME
     *
     * @return the value of meeting_equuipment.EQUIPMENT_NAME
     *
     * @mbggenerated
     */
    public String getEquipmentName() {
        return equipmentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_equuipment.EQUIPMENT_NAME
     *
     * @param equipmentName the value for meeting_equuipment.EQUIPMENT_NAME
     *
     * @mbggenerated
     */
    public void setEquipmentName(String equipmentName) {
        this.equipmentName = equipmentName == null ? null : equipmentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_equuipment.EQUIPMENT_NO
     *
     * @return the value of meeting_equuipment.EQUIPMENT_NO
     *
     * @mbggenerated
     */
    public String getEquipmentNo() {
        return equipmentNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_equuipment.EQUIPMENT_NO
     *
     * @param equipmentNo the value for meeting_equuipment.EQUIPMENT_NO
     *
     * @mbggenerated
     */
    public void setEquipmentNo(String equipmentNo) {
        this.equipmentNo = equipmentNo == null ? null : equipmentNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_equuipment.GROUP_NO
     *
     * @return the value of meeting_equuipment.GROUP_NO
     *
     * @mbggenerated
     */
    public String getGroupNo() {
        return groupNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_equuipment.GROUP_NO
     *
     * @param groupNo the value for meeting_equuipment.GROUP_NO
     *
     * @mbggenerated
     */
    public void setGroupNo(String groupNo) {
        this.groupNo = groupNo == null ? null : groupNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_equuipment.STATUS
     *
     * @return the value of meeting_equuipment.STATUS
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_equuipment.STATUS
     *
     * @param status the value for meeting_equuipment.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_equuipment.MEETING_ROOM_ID
     *
     * @return the value of meeting_equuipment.MEETING_ROOM_ID
     *
     * @mbggenerated
     */
    public Integer getMeetingRoomId() {
        return meetingRoomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_equuipment.MEETING_ROOM_ID
     *
     * @param meetingRoomId the value for meeting_equuipment.MEETING_ROOM_ID
     *
     * @mbggenerated
     */
    public void setMeetingRoomId(Integer meetingRoomId) {
        this.meetingRoomId = meetingRoomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_equuipment.REMARK
     *
     * @return the value of meeting_equuipment.REMARK
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_equuipment.REMARK
     *
     * @param remark the value for meeting_equuipment.REMARK
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}