package com.xoa.model.budget;

import java.util.Date;

public class BudgetLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column budget_log.LOG_ID
     *
     * @mbggenerated
     */
    private Integer logId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column budget_log.Budget_id
     *
     * @mbggenerated
     */
    private Integer budgetId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column budget_log.USER_ID
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column budget_log.TIME
     *
     * @mbggenerated
     */
    private String time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column budget_log.IP
     *
     * @mbggenerated
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column budget_log.TYPE
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column budget_log.REMARK
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column budget_log.budget_item_name
     *
     * @mbggenerated
     */
    private String budgetItemName;

    public Date getBudgetInputTime() {
        return budgetInputTime;
    }

    public void setBudgetInputTime(Date budgetInputTime) {
        this.budgetInputTime = budgetInputTime;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column budget_log.budget_input_time
     *
     * @mbggenerated
     */
    private Date budgetInputTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column budget_log.LOG_ID
     *
     * @return the value of budget_log.LOG_ID
     *
     * @mbggenerated
     */
    public Integer getLogId() {
        return logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column budget_log.LOG_ID
     *
     * @param logId the value for budget_log.LOG_ID
     *
     * @mbggenerated
     */
    public void setLogId(Integer logId) {
        this.logId = logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column budget_log.Budget_id
     *
     * @return the value of budget_log.Budget_id
     *
     * @mbggenerated
     */
    public Integer getBudgetId() {
        return budgetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column budget_log.Budget_id
     *
     * @param budgetId the value for budget_log.Budget_id
     *
     * @mbggenerated
     */
    public void setBudgetId(Integer budgetId) {
        this.budgetId = budgetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column budget_log.USER_ID
     *
     * @return the value of budget_log.USER_ID
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column budget_log.USER_ID
     *
     * @param userId the value for budget_log.USER_ID
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column budget_log.TIME
     *
     * @return the value of budget_log.TIME
     *
     * @mbggenerated
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column budget_log.TIME
     *
     * @param time the value for budget_log.TIME
     *
     * @mbggenerated
     */
    public void setTime(String time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column budget_log.IP
     *
     * @return the value of budget_log.IP
     *
     * @mbggenerated
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column budget_log.IP
     *
     * @param ip the value for budget_log.IP
     *
     * @mbggenerated
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column budget_log.TYPE
     *
     * @return the value of budget_log.TYPE
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column budget_log.TYPE
     *
     * @param type the value for budget_log.TYPE
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column budget_log.REMARK
     *
     * @return the value of budget_log.REMARK
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column budget_log.REMARK
     *
     * @param remark the value for budget_log.REMARK
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column budget_log.budget_item_name
     *
     * @return the value of budget_log.budget_item_name
     *
     * @mbggenerated
     */
    public String getBudgetItemName() {
        return budgetItemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column budget_log.budget_item_name
     *
     * @param budgetItemName the value for budget_log.budget_item_name
     *
     * @mbggenerated
     */
    public void setBudgetItemName(String budgetItemName) {
        this.budgetItemName = budgetItemName == null ? null : budgetItemName.trim();
    }


}