package com.xoa.model.budget;

import com.alibaba.fastjson.annotation.JSONField;
import com.xoa.model.enclosure.Attachment;
import org.springframework.format.annotation.DateTimeFormat;

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashMap;
import java.util.List;

public class BudgetItem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column budget_item.Budget_id
     *
     * @mbggenerated
     */
    private Integer flowId;

    private Integer budgetId;

    private Integer runId;

    private String runName;

    private BigDecimal remainingAmount;//剩余金额

    private String prcsId;

    private String flowStep;

    private String deptName;

    private List<Attachment> attachments;

    private String budgetIds;
    //预支出金额
    private BigDecimal allAdvance;

    private BigDecimal realRemainingAmount;

    public BigDecimal getAllAdvance() {
        return allAdvance;
    }

    public void setAllAdvance(BigDecimal allAdvance) {
        this.allAdvance = allAdvance;
    }

    public BigDecimal getRealRemainingAmount() {
        return realRemainingAmount;
    }

    public void setRealRemainingAmount(BigDecimal realRemainingAmount) {
        this.realRemainingAmount = realRemainingAmount;
    }

    public String getBudgetIds() {
        return budgetIds;
    }

    public void setBudgetIds(String budgetIds) {
        this.budgetIds = budgetIds;
    }

    public List<Attachment> getAttachments() {
        return attachments;
    }

    public void setAttachments(List<Attachment> attachments) {
        this.attachments = attachments;
    }

    public void setDeptName(String deptName) {
        this.deptName = deptName;
    }

    public String getDeptName() {
        return deptName;
    }

    public Integer getRunId() {
        return runId;
    }

    public void setRunId(Integer runId) {
        this.runId = runId;
    }

    public String getPrcsId() {
        return prcsId;
    }

    public void setPrcsId(String prcsId) {
        this.prcsId = prcsId;
    }

    public String getFlowStep() {
        return flowStep;
    }

    public void setFlowStep(String flowStep) {
        this.flowStep = flowStep;
    }

    public BigDecimal getRemainingAmount() {
        return remainingAmount;
    }

    public void setRemainingAmount(BigDecimal remainingAmount) {
        this.remainingAmount = remainingAmount;
    }

    private double expenditureRatio;//项目支出比例

    private HashMap<String,String> map1;

    public HashMap<String, String> getMap1() {
        return map1;
    }

    public void setMap1(HashMap<String, String> map1) {
        this.map1 = map1;
    }

    public String getRunName() {
        return runName;
    }

    public void setRunName(String runName) {
        this.runName = runName;
    }

    private String isOpen;

    private String baiFenBi;

    private String applicant;

    private String amountNum;

    // 查询开始时间
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JSONField(format = "yyyy-MM-dd HH:mm:ss")
    private Date applicantBeginTime;

    // 查询结束时间
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JSONField(format = "yyyy-MM-dd HH:mm:ss")
    private Date applicantEndTime;

    public Date getApplicantBeginTime() {
        return applicantBeginTime;
    }

    public void setApplicantBeginTime(Date applicantBeginTime) {
        this.applicantBeginTime = applicantBeginTime;
    }

    public Date getApplicantEndTime() {
        return applicantEndTime;
    }

    public void setApplicantEndTime(Date applicantEndTime) {
        this.applicantEndTime = applicantEndTime;
    }

    public String getAmountNum() {
        return amountNum;
    }

    public void setAmountNum(String amountNum) {
        this.amountNum = amountNum;
    }

    public String getAllow() {
        return allow;
    }

    public void setAllow(String allow) {
        this.allow = allow;
    }

    public String getApplicant() {

        return applicant;
    }

    public void setApplicant(String applicant) {
        this.applicant = applicant;
    }

    private  String allow;

    public String getBaiFenBi() {
        return baiFenBi;
    }

    public void setBaiFenBi(String baiFenBi) {
        this.baiFenBi = baiFenBi;
    }

    private String budgetLogSet;

    private BigDecimal isPayment;//可用金额

    public BigDecimal getActualExpenditure() {
        return actualExpenditure;
    }

    public void setActualExpenditure(BigDecimal actualExpenditure) {
        this.actualExpenditure = actualExpenditure;
    }

    private BigDecimal actualExpenditure;//支出金额

    public String getApplicationDate() {
        return applicationDate;
    }

    public void setApplicationDate(String applicationDate) {
        this.applicationDate = applicationDate;
    }

    private String applicationDate;//申请时间

    public double getExpenditureRatio() {
        return expenditureRatio;
    }

    public void setExpenditureRatio(double expenditureRatio) {
        this.expenditureRatio = expenditureRatio;
    }

    private String data168;

    private String beginTime;

    public String getData168() {
        return data168;
    }

    public void setData168(String data168) {
        this.data168 = data168;
    }

    private String data172;

    public String getBudgetLogSet() {
        return budgetLogSet;
    }

    public void setBudgetLogSet(String budgetLogSet) {
        this.budgetLogSet = budgetLogSet;
    }

    public String getIsOpen() {
        return isOpen;
    }

    public void setIsOpen(String isOpen) {
        this.isOpen = isOpen;
    }

    public Integer getbId() {
        return bId;
    }

    public void setbId(Integer bId) {
        this.bId = bId;
    }

    private Integer bId;

    private String quotaClassify;

    public String getQuotaClassify() {
        return quotaClassify;
    }

    public void setQuotaClassify(String quotaClassify) {
        this.quotaClassify = quotaClassify;
    }

    private String budgetItemName;

    private String[] budgetItemNames;

    private String year;

    public String getYear() {
        return year;
    }

    public void setYear(String year) {
        this.year = year;
    }

    public String[] getBudgetItemNames() {
        return budgetItemNames;
    }

    public void setBudgetItemNames(String[] budgetItemNames) {
        this.budgetItemNames = budgetItemNames;
    }

    public String getBudgetItemName() {
        return budgetItemName;
    }

    public void setBudgetItemName(String budgetItemName) {
        this.budgetItemName = budgetItemName;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column budget_item.budget_item_no
     *
     * @mbggenerated
     */
    private String budgetItemNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column budget_item.budget_item_begintime
     *
     * @mbggenerated
     */

    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JSONField(format = "yyyy-MM-dd HH:mm:ss")
    private Date budgetItemBegindate;

    private String budgetItemBegindate1;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column budget_item.budget_item_endtime
     *
     * @mbggenerated
     */

    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JSONField(format = "yyyy-MM-dd HH:mm:ss")
    private Date budgetItemEnddate;

    private String budgetItemEnddate1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column budget_item.Input_time
     *
     * @mbggenerated
     */

    private String budgetZhouQi;

    public String getBudgetZhouQi() {
        return budgetZhouQi;
    }

    public void setBudgetZhouQi(String budgetZhouQi) {
        this.budgetZhouQi = budgetZhouQi;
    }

    public BigDecimal getIsPayment() {
        return isPayment;
    }

    public void setIsPayment(BigDecimal isPayment) {
        this.isPayment = isPayment;
    }

    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JSONField(format = "yyyy-MM-dd HH:mm:ss")
    private Date inputTime;

    public String getInputTime1() {
        return inputTime1;
    }

    public void setInputTime1(String inputTime1) {
        this.inputTime1 = inputTime1;
    }

    private String inputTime1;

    public String getDeptId() {
        return deptId;
    }

    public void setDeptId(String deptId) {
        this.deptId = deptId;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column budget_item.department
     *
     * @mbggenerated
     */
    private String deptId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column budget_item.Line_No
     *
     * @mbggenerated
     */
    private String lineNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column budget_item.Prive_item
     *
     * @mbggenerated
     */
    private String priveItem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column budget_item.Item_money
     *
     * @mbggenerated
     */
    private BigDecimal itemMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column budget_item.Item_manager
     *
     * @mbggenerated
     */
    private String itemManager;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column budget_item.Item_executer
     *
     * @mbggenerated
     */
    private String itemExecuter;

    private String itemManagerName;

    private String itemExecuterName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column budget_item.Item_desc
     *
     * @mbggenerated
     */
    private String itemDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column budget_item.Attachment_name
     *
     * @mbggenerated
     */
    private String attachmentName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column budget_item.Attachment_url
     *
     * @mbggenerated
     */
    private String attachmentId;

    public String getItemExecuterName() {
        return itemExecuterName;
    }

    public void setItemExecuterName(String itemExecuterName) {
        this.itemExecuterName = itemExecuterName;
    }

    public String getItemManagerName() {
        return itemManagerName;
    }

    public void setItemManagerName(String itemManagerName) {
        this.itemManagerName = itemManagerName;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column budget_item.Writer_name
     *
     * @mbggenerated
     */
    private String userId;

    public String getUserPhone() {
        return userPhone;
    }

    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column budget_item.Writer_phone
     *
     * @mbggenerated
     */
    private String userPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column budget_item.status
     *
     * @mbggenerated
     */
    private String status;

    public Integer getFlowId() {
        return flowId;
    }

    public void setFlowId(Integer flowId) {
        this.flowId = flowId;
    }

    public Integer getBudgetId() {
        return budgetId;
    }

    public void setBudgetId(Integer budgetId) {
        this.budgetId = budgetId;
    }

    public String getBeginTime() {
        return beginTime;
    }

    public void setBeginTime(String beginTime) {
        this.beginTime = beginTime;
    }

    public String getData172() {
        return data172;
    }

    public void setData172(String data172) {
        this.data172 = data172;
    }

    public String getBudgetItemNo() {
        return budgetItemNo;
    }

    public void setBudgetItemNo(String budgetItemNo) {
        this.budgetItemNo = budgetItemNo;
    }

    public Date getBudgetItemBegindate() {
        return budgetItemBegindate;
    }

    public void setBudgetItemBegindate(Date budgetItemBegindate) {
        this.budgetItemBegindate = budgetItemBegindate;
    }

    public String getBudgetItemBegindate1() {
        return budgetItemBegindate1;
    }

    public void setBudgetItemBegindate1(String budgetItemBegindate1) {
        this.budgetItemBegindate1 = budgetItemBegindate1;
    }
    public Date getBudgetItemEnddate() {
        return budgetItemEnddate;
    }

    public void setBudgetItemEnddate(Date budgetItemEnddate) {
        this.budgetItemEnddate = budgetItemEnddate;
    }

    public String getBudgetItemEnddate1() {
        return budgetItemEnddate1;
    }

    public void setBudgetItemEnddate1(String budgetItemEnddate1) {
        this.budgetItemEnddate1 = budgetItemEnddate1;
    }

    public Date getInputTime() {
        return inputTime;
    }

    public void setInputTime(Date inputTime) {
        this.inputTime = inputTime;
    }

    public String getLineNo() {
        return lineNo;
    }

    public void setLineNo(String lineNo) {
        this.lineNo = lineNo;
    }

    public String getPriveItem() {
        return priveItem;
    }

    public void setPriveItem(String priveItem) {
        this.priveItem = priveItem;
    }

    public BigDecimal getItemMoney() {
        return itemMoney;
    }

    public void setItemMoney(BigDecimal itemMoney) {
        this.itemMoney = itemMoney;
    }

    public String getItemManager() {
        return itemManager;
    }

    public void setItemManager(String itemManager) {
        this.itemManager = itemManager;
    }

    public String getItemExecuter() {
        return itemExecuter;
    }

    public void setItemExecuter(String itemExecuter) {
        this.itemExecuter = itemExecuter;
    }

    public String getItemDesc() {
        return itemDesc;
    }

    public void setItemDesc(String itemDesc) {
        this.itemDesc = itemDesc;
    }

    public String getAttachmentName() {
        return attachmentName;
    }

    public void setAttachmentName(String attachmentName) {
        this.attachmentName = attachmentName;
    }

    public String getAttachmentId() {
        return attachmentId;
    }

    public void setAttachmentId(String attachmentId) {
        this.attachmentId = attachmentId;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }
}