package com.xoa.dao.officesupplies;

import com.xoa.model.officesupplies.OfficeProducts;
import com.xoa.model.officesupplies.OfficeProductsExample;
import com.xoa.model.officesupplies.OfficeProductsWithBLOBs;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface OfficeProductsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table office_products
     *
     * @mbggenerated
     */
    int countByExample(OfficeProductsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table office_products
     *
     * @mbggenerated
     */
    int deleteByExample(OfficeProductsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table office_products
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer proId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table office_products
     *
     * @mbggenerated
     */
    int insert(OfficeProductsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table office_products
     *
     * @mbggenerated
     */
    int insertSelective(OfficeProductsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table office_products
     *
     * @mbggenerated
     */
    List<OfficeProductsWithBLOBs> selectByExampleWithBLOBs(OfficeProductsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table office_products
     *
     * @mbggenerated
     */
    List<OfficeProducts> selectByExample(OfficeProductsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table office_products
     *
     * @mbggenerated
     */
    OfficeProductsWithBLOBs selectByPrimaryKey(Integer proId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table office_products
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") OfficeProductsWithBLOBs record, @Param("example") OfficeProductsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table office_products
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") OfficeProductsWithBLOBs record, @Param("example") OfficeProductsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table office_products
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") OfficeProducts record, @Param("example") OfficeProductsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table office_products
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OfficeProductsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table office_products
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(OfficeProductsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table office_products
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OfficeProducts record);

     void deleteOfficeProducts(@Param("proIds")String[] proIds);

   List<OfficeProductsWithBLOBs> selectOfficeProducts(Map<String,Object> map);

   OfficeProductsWithBLOBs selectSingleOfficeProducts(OfficeProductsWithBLOBs officeProductsWithBLOBs);

    List<OfficeProductsWithBLOBs> selectDownObject(String officeProductType);
    List<OfficeProductsWithBLOBs> getDownObjectLikeBytype(Map map);

    OfficeProductsWithBLOBs selByDepoAndTypeAndPro(OfficeProductsWithBLOBs officeProductsWithBLOBs);

    OfficeProducts getJingao(int proId);
    OfficeProducts getProName(Integer proId);

    List<OfficeProductsWithBLOBs> selProByNameList(Map map);
}