package com.xoa.dao.officesupplies;

import com.xoa.model.officesupplies.OfficeDepository;
import com.xoa.model.officesupplies.OfficeDepositoryExample;
import com.xoa.model.officesupplies.OfficeDepositoryWithBLOBs;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface OfficeDepositoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table office_depository
     *
     * @mbggenerated
     */
    int countByExample(OfficeDepositoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table office_depository
     *
     * @mbggenerated
     */
    int deleteByExample(OfficeDepositoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table office_depository
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table office_depository
     *
     * @mbggenerated
     */
    int insert(OfficeDepositoryWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table office_depository
     *
     * @mbggenerated
     */
    int insertSelective(OfficeDepositoryWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table office_depository
     *
     * @mbggenerated
     */
    List<OfficeDepositoryWithBLOBs> selectByExampleWithBLOBs(OfficeDepositoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table office_depository
     *
     * @mbggenerated
     */
    List<OfficeDepository> selectByExample(OfficeDepositoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table office_depository
     *
     * @mbggenerated
     */
    OfficeDepositoryWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table office_depository
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") OfficeDepositoryWithBLOBs record, @Param("example") OfficeDepositoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table office_depository
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") OfficeDepositoryWithBLOBs record, @Param("example") OfficeDepositoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table office_depository
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") OfficeDepository record, @Param("example") OfficeDepositoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table office_depository
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OfficeDepositoryWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table office_depository
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(OfficeDepositoryWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table office_depository
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OfficeDepository record);


    /**
     * 创建作者:   牛江丽
     * 创建日期:   2017年10月8日 上午11:00:00
     * 方法介绍:   添加办公用品库
     * 参数说明:   @param record
     * 返回值说明:
     */
    int insertDepository(OfficeDepositoryWithBLOBs record);

    /**
     * 创建作者:   牛江丽
     * 创建日期:   2017年10月8日 上午11:01:00
     * 方法介绍:   修改id办公用品库
     * 参数说明:   @param record
     * 返回值说明:
     */
    int updateDepositoryById(OfficeDepositoryWithBLOBs record);

    /**
     * 创建作者:   牛江丽
     * 创建日期:   2017年10月8日 上午11:02:00
     * 方法介绍:   根据id删除办公用品库
     * 参数说明:   @param id
     * 返回值说明:
     */
    int delDepositoryById(Integer id);

    /**
     * 创建作者:   牛江丽
     * 创建日期:   2017年10月8日 上午11:03:00
     * 方法介绍:   根据id查询办公用品库
     * 参数说明:   @param id
     * 返回值说明:
     */
    OfficeDepositoryWithBLOBs selDepositoryById(Integer id);

    /**
     * 创建作者:   牛江丽
     * 创建日期:   2017年10月8日 上午11:03:00
     * 方法介绍:   根据名称查询办公用品库
     * 参数说明:   @param id
     * 返回值说明:
     */
    OfficeDepositoryWithBLOBs selDepositoryByName(String depositoryName);


    /**
     * 创建作者:   牛江丽
     * 创建日期:   2017年10月8日 上午11:04:00
     * 方法介绍:   查询所有办公用品库
     * 参数说明:   @param
     * 返回值说明:
     */
    List<OfficeDepositoryWithBLOBs> selAllDepository();

    List<OfficeDepositoryWithBLOBs> selAllDepositoryPage(Map map);

    /**
     * 创建作者:   牛江丽
     * 创建日期:   2017年10月8日 上午11:04:00
     * 方法介绍:   根据当前登录人是否为所属部门进行查询
     * 参数说明:   @param
     * 返回值说明:
     */
    List<OfficeDepositoryWithBLOBs> selDepositoryByDept(String currentUser);


    /**
     * 创建作者:   牛江丽
     * 创建日期:   2017年10月8日 上午11:04:00
     * 方法介绍:   根据库id、类型id和用品id查询
     * 参数说明:   @param
     * 返回值说明:
     */
    List<OfficeDepositoryWithBLOBs> selByDepoAndTypeAndPro(Map<String,Object> map);

    List<OfficeDepositoryWithBLOBs> getAllDeposttoryTree();
}