package com.xoa.dao.salary.bonuspriv;

import com.xoa.model.salary.bonuspriv.BonusPriv;
import com.xoa.model.salary.bonuspriv.BonusPrivExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface BonusPrivMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bonus_priv
     *
     * @mbggenerated
     */
    int countByExample(BonusPrivExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bonus_priv
     *
     * @mbggenerated
     */
    int deleteByExample(BonusPrivExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bonus_priv
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bonus_priv
     *
     * @mbggenerated
     */
    int insert(BonusPriv record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bonus_priv
     *
     * @mbggenerated
     */
    int insertSelective(BonusPriv record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bonus_priv
     *
     * @mbggenerated
     */
    List<BonusPriv> selectByExampleWithBLOBs(BonusPrivExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bonus_priv
     *
     * @mbggenerated
     */
    List<BonusPriv> selectByExample(BonusPrivExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bonus_priv
     *
     * @mbggenerated
     */
    BonusPriv selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bonus_priv
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BonusPriv record, @Param("example") BonusPrivExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bonus_priv
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") BonusPriv record, @Param("example") BonusPrivExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bonus_priv
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BonusPriv record, @Param("example") BonusPrivExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bonus_priv
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BonusPriv record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bonus_priv
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(BonusPriv record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bonus_priv
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BonusPriv record);
    BonusPriv selectByManager(String manager);
    BonusPriv selectByManagerId(String manager);
    List<BonusPriv> selectAll(Map map);
}