package com.xoa.dao;

import com.xoa.model.projectManage.ProjExtInfo;
import com.xoa.model.projectManage.ProjExtInfoExample;
import com.xoa.model.projectManage.ProjExtInfoWithBLOBs;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ProjExtInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj_ext_info
     *
     * @mbggenerated
     */
    int countByExample(ProjExtInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj_ext_info
     *
     * @mbggenerated
     */
    int deleteByExample(ProjExtInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj_ext_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer projExtId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj_ext_info
     *
     * @mbggenerated
     */
    int insert(ProjExtInfoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj_ext_info
     *
     * @mbggenerated
     */
    int insertSelective(ProjExtInfoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj_ext_info
     *
     * @mbggenerated
     */
    List<ProjExtInfoWithBLOBs> selectByExampleWithBLOBs(ProjExtInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj_ext_info
     *
     * @mbggenerated
     */
    List<ProjExtInfo> selectByExample(ProjExtInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj_ext_info
     *
     * @mbggenerated
     */
    ProjExtInfoWithBLOBs selectByPrimaryKey(Integer projId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj_ext_info
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ProjExtInfoWithBLOBs record, @Param("example") ProjExtInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj_ext_info
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") ProjExtInfoWithBLOBs record, @Param("example") ProjExtInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj_ext_info
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ProjExtInfo record, @Param("example") ProjExtInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj_ext_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ProjExtInfoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj_ext_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(ProjExtInfoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj_ext_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ProjExtInfo record);
}