package com.xoa.model.myNotify;

import com.alibaba.fastjson.annotation.JSONField;
import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;

public class MyNotifyOpinion {
    /**
     * 任务发布时间
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JSONField(format = "yyyy-MM-dd HH:mm:ss")
    private Date  endTime;
    /**
     * 任务发布时间String
     */
    private String  endTimeStr;
    /**
     * 发布用户
     */
    private String  fromName;
    private String userName;

    private String deptName;

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getDeptName() {
        return deptName;
    }

    public void setDeptName(String deptName) {
        this.deptName = deptName;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notify_opinion.OP_ID
     *
     * @mbggenerated
     */
    private Integer opId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notify_opinion.NOTY_ID
     *
     * @mbggenerated
     */
    private Integer notyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notify_opinion.USER_ID
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notify_opinion.STATE
     *
     * @mbggenerated
     */
    private String state;

    /**
     * 状态
     */
    private String stateStr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notify_opinion.FIELD1
     *
     * @mbggenerated
     */
    private String field1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notify_opinion.FIELD2
     *
     * @mbggenerated
     */
    private String field2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notify_opinion.FIELD3
     *
     * @mbggenerated
     */
    private String field3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notify_opinion.FIELD4
     *
     * @mbggenerated
     */
    private String field4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notify_opinion.FIELD5
     *
     * @mbggenerated
     */
    private String field5;
    private String field6;
    private String field7;
    private String field8;
    private String field9;
    private String field10;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notify_opinion.INUPUT_TIME
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JSONField(format = "yyyy-MM-dd HH:mm:ss")
    private Date inuputTime;

    private String  inputTimeStr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notify_opinion.UPDATE_TIME
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JSONField(format = "yyyy-MM-dd HH:mm:ss")
    private Date updateTime;

    private String  updateTimeStr;

    public String getInputTimeStr() {
        return inputTimeStr;
    }

    public void setInputTimeStr(String inputTimeStr) {
        this.inputTimeStr = inputTimeStr;
    }

    public String getUpdateTimeStr() {
        return updateTimeStr;
    }

    public void setUpdateTimeStr(String updateTimeStr) {
        this.updateTimeStr = updateTimeStr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notify_opinion.OP_ID
     *
     * @return the value of notify_opinion.OP_ID
     *
     * @mbggenerated
     */
    public Integer getOpId() {
        return opId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notify_opinion.OP_ID
     *
     * @param opId the value for notify_opinion.OP_ID
     *
     * @mbggenerated
     */
    public void setOpId(Integer opId) {
        this.opId = opId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notify_opinion.NOTY_ID
     *
     * @return the value of notify_opinion.NOTY_ID
     *
     * @mbggenerated
     */
    public Integer getNotyId() {
        return notyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notify_opinion.NOTY_ID
     *
     * @param notyId the value for notify_opinion.NOTY_ID
     *
     * @mbggenerated
     */
    public void setNotyId(Integer notyId) {
        this.notyId = notyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notify_opinion.USER_ID
     *
     * @return the value of notify_opinion.USER_ID
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notify_opinion.USER_ID
     *
     * @param userId the value for notify_opinion.USER_ID
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notify_opinion.STATE
     *
     * @return the value of notify_opinion.STATE
     *
     * @mbggenerated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notify_opinion.STATE
     *
     * @param state the value for notify_opinion.STATE
     *
     * @mbggenerated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notify_opinion.FIELD1
     *
     * @return the value of notify_opinion.FIELD1
     *
     * @mbggenerated
     */
    public String getField1() {
        return field1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notify_opinion.FIELD1
     *
     * @param field1 the value for notify_opinion.FIELD1
     *
     * @mbggenerated
     */
    public void setField1(String field1) {
        this.field1 = field1 == null ? null : field1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notify_opinion.FIELD2
     *
     * @return the value of notify_opinion.FIELD2
     *
     * @mbggenerated
     */
    public String getField2() {
        return field2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notify_opinion.FIELD2
     *
     * @param field2 the value for notify_opinion.FIELD2
     *
     * @mbggenerated
     */
    public void setField2(String field2) {
        this.field2 = field2 == null ? null : field2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notify_opinion.FIELD3
     *
     * @return the value of notify_opinion.FIELD3
     *
     * @mbggenerated
     */
    public String getField3() {
        return field3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notify_opinion.FIELD3
     *
     * @param field3 the value for notify_opinion.FIELD3
     *
     * @mbggenerated
     */
    public void setField3(String field3) {
        this.field3 = field3 == null ? null : field3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notify_opinion.FIELD4
     *
     * @return the value of notify_opinion.FIELD4
     *
     * @mbggenerated
     */
    public String getField4() {
        return field4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notify_opinion.FIELD4
     *
     * @param field4 the value for notify_opinion.FIELD4
     *
     * @mbggenerated
     */
    public void setField4(String field4) {
        this.field4 = field4 == null ? null : field4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notify_opinion.FIELD5
     *
     * @return the value of notify_opinion.FIELD5
     *
     * @mbggenerated
     */
    public String getField5() {
        return field5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notify_opinion.FIELD5
     *
     * @param field5 the value for notify_opinion.FIELD5
     *
     * @mbggenerated
     */
    public void setField5(String field5) {
        this.field5 = field5 == null ? null : field5.trim();
    }


    public String getField6() {
        return field6;
    }

    public void setField6(String field6) {
        this.field6 = field6;
    }

    public String getField7() {
        return field7;
    }

    public void setField7(String field7) {
        this.field7 = field7;
    }

    public String getField8() {
        return field8;
    }

    public void setField8(String field8) {
        this.field8 = field8;
    }

    public String getField9() {
        return field9;
    }

    public void setField9(String field9) {
        this.field9 = field9;
    }

    public String getField10() {
        return field10;
    }

    public void setField10(String field10) {
        this.field10 = field10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notify_opinion.INUPUT_TIME
     *
     * @return the value of notify_opinion.INUPUT_TIME
     *
     * @mbggenerated
     */
    public Date getInuputTime() {
        return inuputTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notify_opinion.INUPUT_TIME
     *
     * @param inuputTime the value for notify_opinion.INUPUT_TIME
     *
     * @mbggenerated
     */
    public void setInuputTime(Date inuputTime) {
        this.inuputTime = inuputTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notify_opinion.UPDATE_TIME
     *
     * @return the value of notify_opinion.UPDATE_TIME
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notify_opinion.UPDATE_TIME
     *
     * @param updateTime the value for notify_opinion.UPDATE_TIME
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public Date getEndTime() {
        return endTime;
    }

    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    public String getFromName() {
        return fromName;
    }

    public void setFromName(String fromName) {
        this.fromName = fromName;
    }

    public String getStateStr() {
        return stateStr;
    }

    public void setStateStr(String stateStr) {
        this.stateStr = stateStr;
    }

    public String getEndTimeStr() {
        return endTimeStr;
    }

    public void setEndTimeStr(String endTimeStr) {
        this.endTimeStr = endTimeStr;
    }
}