package com.xoa.dao.knowledge;

import com.xoa.model.knowledge.KnowledgeSubscribe;
import com.xoa.model.knowledge.KnowledgeSubscribeExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface KnowledgeSubscribeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table knowledge_subscribe
     *
     * @mbggenerated
     */
    int countByExample(KnowledgeSubscribeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table knowledge_subscribe
     *
     * @mbggenerated
     */
    int deleteByExample(KnowledgeSubscribeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table knowledge_subscribe
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer subscribeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table knowledge_subscribe
     *
     * @mbggenerated
     */
    int insert(KnowledgeSubscribe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table knowledge_subscribe
     *
     * @mbggenerated
     */
    int insertSelective(KnowledgeSubscribe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table knowledge_subscribe
     *
     * @mbggenerated
     */
    List<KnowledgeSubscribe> selectByExample(KnowledgeSubscribeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table knowledge_subscribe
     *
     * @mbggenerated
     */
    KnowledgeSubscribe selectByPrimaryKey(Integer subscribeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table knowledge_subscribe
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") KnowledgeSubscribe record, @Param("example") KnowledgeSubscribeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table knowledge_subscribe
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") KnowledgeSubscribe record, @Param("example") KnowledgeSubscribeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table knowledge_subscribe
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(KnowledgeSubscribe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table knowledge_subscribe
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(KnowledgeSubscribe record);

    List<KnowledgeSubscribe> getSubscription();

    KnowledgeSubscribe selectByDocIdAndUserId(@Param("docfileId") Integer docfileId, @Param("userId") String userId);

    int findUnWork(KnowledgeSubscribe record);

    //分页 根据客户id和文档id查询所有数据
    List<KnowledgeSubscribe> selectByCustomerIdAndFildId(Map map);
}