package com.xoa.dao.message;

import com.xoa.model.message.Message;
import com.xoa.model.message.MessageExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

/**
 * 李阳
 * 2018.8.13
 * 微讯
 */
public interface MessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbggenerated
     */
    int countByExample(MessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbggenerated
     */
    int deleteByExample(MessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer msgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbggenerated
     */
    int insert(Message record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbggenerated
     */
    int insertSelective(Message record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbggenerated
     */
    List<Message> selectByExample(MessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbggenerated
     */
    Message selectByPrimaryKey(Integer msgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Message record, @Param("example") MessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Message record, @Param("example") MessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Message record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Message record);

    /**
     * 查找当前登录人所有未确认的微讯
     * @return
     */
    List<Message> getStatusWQR(@Param("map") Map<String,Object> map,@Param("toUid") String UID);

    /**
     * 删除微讯
     * 收件人删除或发件人删除
     * @return
     */
    int delMessage(Message message);

    /**
     * 根据 msgId查询微讯
     * @param msgId
     * @return
     */
    List<Message> messageList(@Param("msgId") String[] msgId);

    /**
     * 新增微讯
     * @param message
     * @return
     */
    int addMessage(Message message);

    /**
     * 根据 当前登录人UID和点击获取人UID查询微讯聊天记录
     * @param
     * @return
     */
    List<Message> getMessageInfo(Map<String,Object> map);

    /**
     * 点击回复获取发件人
     * @return
     */
    String clickReply(String msgId);

    /**
     * 查询 导出 微讯
     * @param map
     * @return
     */
    List<Message> selectMessage(Map<String,Object> map);
    /**
     * 查找当前登录人所有未确认的微讯 总数
     * @return
     */
    Integer getStatusWQRCount(@Param("toUid") String UID);
    /**
     * 根据 微讯聊天记录 总条数
     * @param
     * @return
     */
    Integer getMessageInfoCount(Map<String,Object> map);
    /**
     * 查询 导出 微讯 总条数
     * @param map
     * @return
     */
    Integer selectMessageCount(Map<String,Object> map);

    /**
     * 根据主键查询微讯
     * @param msgId
     * @return
     */
    Message getMessage(@Param("msgId") String msgId);
}