package com.xoa.model.monitoring;

public class MptCate {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mpt_cate.MPT_CATE_ID
     *
     * @mbggenerated
     */
    private Integer mptCateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mpt_cate.MPT_CATE_NAME
     *
     * @mbggenerated
     */
    private String mptCateName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mpt_cate.MPT_IV
     *
     * @mbggenerated
     */
    private String mptIv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mpt_cate.MPT_V
     *
     * @mbggenerated
     */
    private String mptV;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mpt_cate.MPT_VI
     *
     * @mbggenerated
     */
    private String mptVi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mpt_cate.MPT_VII
     *
     * @mbggenerated
     */
    private String mptVii;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mpt_cate.MPT_VIII
     *
     * @mbggenerated
     */
    private String mptViii;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mpt_cate.MPT_CATE_ID
     *
     * @return the value of mpt_cate.MPT_CATE_ID
     *
     * @mbggenerated
     */
    public Integer getMptCateId() {
        return mptCateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mpt_cate.MPT_CATE_ID
     *
     * @param mptCateId the value for mpt_cate.MPT_CATE_ID
     *
     * @mbggenerated
     */
    public void setMptCateId(Integer mptCateId) {
        this.mptCateId = mptCateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mpt_cate.MPT_CATE_NAME
     *
     * @return the value of mpt_cate.MPT_CATE_NAME
     *
     * @mbggenerated
     */
    public String getMptCateName() {
        return mptCateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mpt_cate.MPT_CATE_NAME
     *
     * @param mptCateName the value for mpt_cate.MPT_CATE_NAME
     *
     * @mbggenerated
     */
    public void setMptCateName(String mptCateName) {
        this.mptCateName = mptCateName == null ? null : mptCateName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mpt_cate.MPT_IV
     *
     * @return the value of mpt_cate.MPT_IV
     *
     * @mbggenerated
     */
    public String getMptIv() {
        return mptIv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mpt_cate.MPT_IV
     *
     * @param mptIv the value for mpt_cate.MPT_IV
     *
     * @mbggenerated
     */
    public void setMptIv(String mptIv) {
        this.mptIv = mptIv == null ? null : mptIv.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mpt_cate.MPT_V
     *
     * @return the value of mpt_cate.MPT_V
     *
     * @mbggenerated
     */
    public String getMptV() {
        return mptV;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mpt_cate.MPT_V
     *
     * @param mptV the value for mpt_cate.MPT_V
     *
     * @mbggenerated
     */
    public void setMptV(String mptV) {
        this.mptV = mptV == null ? null : mptV.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mpt_cate.MPT_VI
     *
     * @return the value of mpt_cate.MPT_VI
     *
     * @mbggenerated
     */
    public String getMptVi() {
        return mptVi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mpt_cate.MPT_VI
     *
     * @param mptVi the value for mpt_cate.MPT_VI
     *
     * @mbggenerated
     */
    public void setMptVi(String mptVi) {
        this.mptVi = mptVi == null ? null : mptVi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mpt_cate.MPT_VII
     *
     * @return the value of mpt_cate.MPT_VII
     *
     * @mbggenerated
     */
    public String getMptVii() {
        return mptVii;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mpt_cate.MPT_VII
     *
     * @param mptVii the value for mpt_cate.MPT_VII
     *
     * @mbggenerated
     */
    public void setMptVii(String mptVii) {
        this.mptVii = mptVii == null ? null : mptVii.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mpt_cate.MPT_VIII
     *
     * @return the value of mpt_cate.MPT_VIII
     *
     * @mbggenerated
     */
    public String getMptViii() {
        return mptViii;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mpt_cate.MPT_VIII
     *
     * @param mptViii the value for mpt_cate.MPT_VIII
     *
     * @mbggenerated
     */
    public void setMptViii(String mptViii) {
        this.mptViii = mptViii == null ? null : mptViii.trim();
    }
}