package com.xoa.model.todayCarNo;

import com.alibaba.fastjson.annotation.JSONField;
import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;

public class TodayCarNo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column today_car_no.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column today_car_no.DATE
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    @JSONField(format = "yyyy-MM-dd")
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column today_car_no.CITY
     *
     * @mbggenerated
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column today_car_no.RESTRICTION_FLAG
     *
     * @mbggenerated
     */
    private String restrictionFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column today_car_no.RESTRICTION_NUM
     *
     * @mbggenerated
     */
    private String restrictionNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column today_car_no.ID
     *
     * @return the value of today_car_no.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column today_car_no.ID
     *
     * @param id the value for today_car_no.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column today_car_no.DATE
     *
     * @return the value of today_car_no.DATE
     *
     * @mbggenerated
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column today_car_no.DATE
     *
     * @param date the value for today_car_no.DATE
     *
     * @mbggenerated
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column today_car_no.CITY
     *
     * @return the value of today_car_no.CITY
     *
     * @mbggenerated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column today_car_no.CITY
     *
     * @param city the value for today_car_no.CITY
     *
     * @mbggenerated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column today_car_no.RESTRICTION_FLAG
     *
     * @return the value of today_car_no.RESTRICTION_FLAG
     *
     * @mbggenerated
     */
    public String getRestrictionFlag() {
        return restrictionFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column today_car_no.RESTRICTION_FLAG
     *
     * @param restrictionFlag the value for today_car_no.RESTRICTION_FLAG
     *
     * @mbggenerated
     */
    public void setRestrictionFlag(String restrictionFlag) {
        this.restrictionFlag = restrictionFlag == null ? null : restrictionFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column today_car_no.RESTRICTION_NUM
     *
     * @return the value of today_car_no.RESTRICTION_NUM
     *
     * @mbggenerated
     */
    public String getRestrictionNum() {
        return restrictionNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column today_car_no.RESTRICTION_NUM
     *
     * @param restrictionNum the value for today_car_no.RESTRICTION_NUM
     *
     * @mbggenerated
     */
    public void setRestrictionNum(String restrictionNum) {
        this.restrictionNum = restrictionNum == null ? null : restrictionNum.trim();
    }
}