package com.xoa.dao.equipment;


import com.xoa.model.equipment.LimsEquipEventPlanPara;
import com.xoa.model.equipment.LimsEquipEventPlanParaExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface LimsEquipEventPlanParaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_equip_event_plan_para
     *
     * @mbggenerated
     */
    int countByExample(LimsEquipEventPlanParaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_equip_event_plan_para
     *
     * @mbggenerated
     */
    int deleteByExample(LimsEquipEventPlanParaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_equip_event_plan_para
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer planParaId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_equip_event_plan_para
     *
     * @mbggenerated
     */
    int insert(LimsEquipEventPlanPara record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_equip_event_plan_para
     *
     * @mbggenerated
     */
    int insertSelective(LimsEquipEventPlanPara record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_equip_event_plan_para
     *
     * @mbggenerated
     */
    List<LimsEquipEventPlanPara> selectByExample(LimsEquipEventPlanParaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_equip_event_plan_para
     *
     * @mbggenerated
     */
    LimsEquipEventPlanPara selectByPrimaryKey(Integer planParaId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_equip_event_plan_para
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") LimsEquipEventPlanPara record, @Param("example") LimsEquipEventPlanParaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_equip_event_plan_para
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") LimsEquipEventPlanPara record, @Param("example") LimsEquipEventPlanParaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_equip_event_plan_para
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(LimsEquipEventPlanPara record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_equip_event_plan_para
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(LimsEquipEventPlanPara record);

    List<LimsEquipEventPlanPara> queryByEventId(Integer eventId);

    List<LimsEquipEventPlanPara> selectByEventId(Map map);

    int deleteByIds(@Param("ids") String[] ids);

}