package com.xoa.dao.equipment;

import com.xoa.model.equipment.LimsEquipInveCont;
import com.xoa.model.equipment.LimsEquipInveContExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface LimsEquipInveContMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_equip_inve_cont
     *
     * @mbggenerated
     */
    int countByExample(LimsEquipInveContExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_equip_inve_cont
     *
     * @mbggenerated
     */
    int deleteByExample(LimsEquipInveContExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_equip_inve_cont
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer contId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_equip_inve_cont
     *
     * @mbggenerated
     */
    int insert(LimsEquipInveCont record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_equip_inve_cont
     *
     * @mbggenerated
     */
    int insertSelective(LimsEquipInveCont record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_equip_inve_cont
     *
     * @mbggenerated
     */
    List<LimsEquipInveCont> selectByExample(LimsEquipInveContExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_equip_inve_cont
     *
     * @mbggenerated
     */
    LimsEquipInveCont selectByPrimaryKey(Integer contId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_equip_inve_cont
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") LimsEquipInveCont record, @Param("example") LimsEquipInveContExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_equip_inve_cont
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") LimsEquipInveCont record, @Param("example") LimsEquipInveContExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_equip_inve_cont
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(LimsEquipInveCont record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_equip_inve_cont
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(LimsEquipInveCont record);

    int delContByInveId(Map map);

    LimsEquipInveCont findContInfoByInveId(Integer inveId);
}