package com.xoa.dao.equipment;

import com.xoa.model.equipment.LimsEquipCapyType;
import com.xoa.model.equipment.LimsEquipCapyTypeExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface LimsEquipCapyTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_equip_capy_type
     *
     * @mbggenerated
     */
    int countByExample(LimsEquipCapyTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_equip_capy_type
     *
     * @mbggenerated
     */
    int deleteByExample(LimsEquipCapyTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_equip_capy_type
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer typeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_equip_capy_type
     *
     * @mbggenerated
     */
    int insert(LimsEquipCapyType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_equip_capy_type
     *
     * @mbggenerated
     */
    int insertSelective(LimsEquipCapyType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_equip_capy_type
     *
     * @mbggenerated
     */
    List<LimsEquipCapyType> selectByExample(LimsEquipCapyTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_equip_capy_type
     *
     * @mbggenerated
     */
    LimsEquipCapyType selectByPrimaryKey(Integer typeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_equip_capy_type
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") LimsEquipCapyType record, @Param("example") LimsEquipCapyTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_equip_capy_type
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") LimsEquipCapyType record, @Param("example") LimsEquipCapyTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_equip_capy_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(LimsEquipCapyType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_equip_capy_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(LimsEquipCapyType record);

    List<LimsEquipCapyType> equipTypeCodeList();
    List<LimsEquipCapyType> typeInfo(Map map);

    LimsEquipCapyType selByTypeCode(String typeCode);
}