package com.xoa.dao.equipment;

import com.xoa.model.equipment.LimsEquipOwnerlist;
import com.xoa.model.equipment.LimsEquipOwnerlistExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface LimsEquipOwnerlistMapper {
    //根据主表id或者equipId或者主键查询
    List<LimsEquipOwnerlist> findBylogId(Map map);
    //根据主键删除
    int delByKey(Map map);
    //修改接受状态
    int updRecStatus(Map map);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_equip_ownerlist
     *
     * @mbggenerated
     */
    int countByExample(LimsEquipOwnerlistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_equip_ownerlist
     *
     * @mbggenerated
     */
    int deleteByExample(LimsEquipOwnerlistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_equip_ownerlist
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer ownerlistId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_equip_ownerlist
     *
     * @mbggenerated
     */
    int insert(LimsEquipOwnerlist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_equip_ownerlist
     *
     * @mbggenerated
     */
    int insertSelective(LimsEquipOwnerlist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_equip_ownerlist
     *
     * @mbggenerated
     */
    List<LimsEquipOwnerlist> selectByExample(LimsEquipOwnerlistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_equip_ownerlist
     *
     * @mbggenerated
     */
    LimsEquipOwnerlist selectByPrimaryKey(Integer ownerlistId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_equip_ownerlist
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") LimsEquipOwnerlist record, @Param("example") LimsEquipOwnerlistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_equip_ownerlist
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") LimsEquipOwnerlist record, @Param("example") LimsEquipOwnerlistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_equip_ownerlist
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(LimsEquipOwnerlist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_equip_ownerlist
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(LimsEquipOwnerlist record);
}