package com.xoa.dao.equipment;

import com.xoa.model.equipment.LimsEquipScraplog;
import com.xoa.model.equipment.LimsEquipScraplogExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface LimsEquipScraplogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_equip_scraplog
     *
     * @mbggenerated
     */
    int countByExample(LimsEquipScraplogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_equip_scraplog
     *
     * @mbggenerated
     */
    int deleteByExample(LimsEquipScraplogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_equip_scraplog
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer scraplogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_equip_scraplog
     *
     * @mbggenerated
     */
    int insert(LimsEquipScraplog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_equip_scraplog
     *
     * @mbggenerated
     */
    int insertSelective(LimsEquipScraplog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_equip_scraplog
     *
     * @mbggenerated
     */
    List<LimsEquipScraplog> selectByExample(LimsEquipScraplogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_equip_scraplog
     *
     * @mbggenerated
     */
    LimsEquipScraplog selectByPrimaryKey(Integer scraplogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_equip_scraplog
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") LimsEquipScraplog record, @Param("example") LimsEquipScraplogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_equip_scraplog
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") LimsEquipScraplog record, @Param("example") LimsEquipScraplogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_equip_scraplog
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(LimsEquipScraplog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_equip_scraplog
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(LimsEquipScraplog record);

    //通用查询所有设备报废申请并分页
    List<LimsEquipScraplog> selectAllScraplog(Map map);

    //查询最新新添加的一条设备报废申请
    LimsEquipScraplog selectLastData();

    //通用得条件查询方法
    List<LimsEquipScraplog> selectByCondition(Map map);

    //通过deptId查询数据
    List<LimsEquipScraplog> selectByDeptId(Integer deptId);

    //通过status状态查询数据
    List<LimsEquipScraplog> selectByStatus(String status);
}