package com.xoa.dao.equipment;

import com.xoa.model.equipment.LimsEquipEventsCapy;
import com.xoa.model.equipment.LimsEquipEventsCapyExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface LimsEquipEventsCapyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_equip_events_capy
     *
     * @mbggenerated
     */
    int countByExample(LimsEquipEventsCapyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_equip_events_capy
     *
     * @mbggenerated
     */
    int deleteByExample(LimsEquipEventsCapyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_equip_events_capy
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer eventCapyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_equip_events_capy
     *
     * @mbggenerated
     */
    int insert(LimsEquipEventsCapy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_equip_events_capy
     *
     * @mbggenerated
     */
    int insertSelective(LimsEquipEventsCapy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_equip_events_capy
     *
     * @mbggenerated
     */
    List<LimsEquipEventsCapy> selectByExample(LimsEquipEventsCapyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_equip_events_capy
     *
     * @mbggenerated
     */
    LimsEquipEventsCapy selectByPrimaryKey(Integer eventCapyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_equip_events_capy
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") LimsEquipEventsCapy record, @Param("example") LimsEquipEventsCapyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_equip_events_capy
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") LimsEquipEventsCapy record, @Param("example") LimsEquipEventsCapyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_equip_events_capy
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(LimsEquipEventsCapy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_equip_events_capy
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(LimsEquipEventsCapy record);

    int deleteByIds(@Param("ids") String[] ids);

    List<LimsEquipEventsCapy> showByEventLogId(Map map);
}