package com.xoa.dao.equipment;

import com.xoa.model.equipment.LimsEquipScraplist;
import com.xoa.model.equipment.LimsEquipScraplistExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface LimsEquipScraplistMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_equip_scraplist
     *
     * @mbggenerated
     */
    int countByExample(LimsEquipScraplistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_equip_scraplist
     *
     * @mbggenerated
     */
    int deleteByExample(LimsEquipScraplistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_equip_scraplist
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer scraplistId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_equip_scraplist
     *
     * @mbggenerated
     */
    int insert(LimsEquipScraplist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_equip_scraplist
     *
     * @mbggenerated
     */
    int insertSelective(LimsEquipScraplist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_equip_scraplist
     *
     * @mbggenerated
     */
    List<LimsEquipScraplist> selectByExample(LimsEquipScraplistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_equip_scraplist
     *
     * @mbggenerated
     */
    LimsEquipScraplist selectByPrimaryKey(Integer scraplistId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_equip_scraplist
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") LimsEquipScraplist record, @Param("example") LimsEquipScraplistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_equip_scraplist
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") LimsEquipScraplist record, @Param("example") LimsEquipScraplistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_equip_scraplist
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(LimsEquipScraplist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_equip_scraplist
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(LimsEquipScraplist record);

    //根据id查询数据并分页
    List<LimsEquipScraplist> selectScraplistById(Map map);

    //查询报废申请下的设备
    List<LimsEquipScraplist> selectScraplistByScraplogId(int scraplogId);

    //查询固定申请下得设备
    LimsEquipScraplist selectByEquipId(Map map);

    //通过联合查询，查出有无指定状态得数据
    List<LimsEquipScraplist> queryStatus(Map map);

    //通过报废申请id修改报废设备信息
    void updateByScraologId(LimsEquipScraplist limsEquipScraplist);
}