package com.xoa.dao.equipment;

import com.xoa.model.equipment.LimsEquipLendlist;
import com.xoa.model.equipment.LimsEquipLendlistExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface LimsEquipLendlistMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_equip_lendlist
     *
     * @mbggenerated
     */
    int countByExample(LimsEquipLendlistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_equip_lendlist
     *
     * @mbggenerated
     */
    int deleteByExample(LimsEquipLendlistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_equip_lendlist
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer lendListId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_equip_lendlist
     *
     * @mbggenerated
     */
    int insert(LimsEquipLendlist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_equip_lendlist
     *
     * @mbggenerated
     */
    int insertSelective(LimsEquipLendlist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_equip_lendlist
     *
     * @mbggenerated
     */
    List<LimsEquipLendlist> selectByExample(LimsEquipLendlistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_equip_lendlist
     *
     * @mbggenerated
     */
    LimsEquipLendlist selectByPrimaryKey(Integer lendListId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_equip_lendlist
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") LimsEquipLendlist record, @Param("example") LimsEquipLendlistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_equip_lendlist
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") LimsEquipLendlist record, @Param("example") LimsEquipLendlistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_equip_lendlist
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(LimsEquipLendlist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lims_equip_lendlist
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(LimsEquipLendlist record);

    List<LimsEquipLendlist> select(Map map);

    int updateBylendId(LimsEquipLendlist limsEquipLendlist);

    int deleteBylendId(@Param("lendId") Integer lendId);

    List<LimsEquipLendlist> resulrApproval(@Param("lendIds") Integer lendIds);

    List<LimsEquipLendlist> resultCult(@Param("equipId") Integer equipId);

    LimsEquipLendlist resultCult1(Map map);

    List<LimsEquipLendlist> findEquipIdByLendIdand0(Integer lendId);

}