package com.xoa.dao.position;

import com.xoa.model.position.UserJobDutyHistory;
import com.xoa.model.position.UserJobDutyHistoryExample;
import com.xoa.model.position.UserJobDutyHistoryWithBLOBs;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface UserJobDutyHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_job_duty_history
     *
     * @mbggenerated
     */
    int countByExample(UserJobDutyHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_job_duty_history
     *
     * @mbggenerated
     */
    int deleteByExample(UserJobDutyHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_job_duty_history
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer historyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_job_duty_history
     *
     * @mbggenerated
     */
    int insert(UserJobDutyHistoryWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_job_duty_history
     *
     * @mbggenerated
     */
    int insertSelective(UserJobDutyHistoryWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_job_duty_history
     *
     * @mbggenerated
     */
    List<UserJobDutyHistoryWithBLOBs> selectByExampleWithBLOBs(UserJobDutyHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_job_duty_history
     *
     * @mbggenerated
     */
    List<UserJobDutyHistory> selectByExample(UserJobDutyHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_job_duty_history
     *
     * @mbggenerated
     */
    UserJobDutyHistoryWithBLOBs selectByPrimaryKey(Integer historyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_job_duty_history
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UserJobDutyHistoryWithBLOBs record, @Param("example") UserJobDutyHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_job_duty_history
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") UserJobDutyHistoryWithBLOBs record, @Param("example") UserJobDutyHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_job_duty_history
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UserJobDutyHistory record, @Param("example") UserJobDutyHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_job_duty_history
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserJobDutyHistoryWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_job_duty_history
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(UserJobDutyHistoryWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_job_duty_history
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserJobDutyHistory record);


    List<UserJobDutyHistoryWithBLOBs> getUserJobDutyHistory(Map<String, Object> map);
}