package com.xoa.dao.position;

import com.xoa.model.position.UserJobDuty;
import com.xoa.model.position.UserJobDutyExample;
import com.xoa.model.position.UserJobDutyWithBLOBs;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface UserJobDutyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_job_duty
     *
     * @mbggenerated
     */
    int countByExample(UserJobDutyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_job_duty
     *
     * @mbggenerated
     */
    int deleteByExample(UserJobDutyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_job_duty
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer dutyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_job_duty
     *
     * @mbggenerated
     */
    int insert(UserJobDutyWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_job_duty
     *
     * @mbggenerated
     */
    int insertSelective(UserJobDutyWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_job_duty
     *
     * @mbggenerated
     */
    List<UserJobDutyWithBLOBs> selectByExampleWithBLOBs(UserJobDutyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_job_duty
     *
     * @mbggenerated
     */
    List<UserJobDuty> selectByExample(UserJobDutyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_job_duty
     *
     * @mbggenerated
     */
    UserJobDutyWithBLOBs selectByPrimaryKey(Integer dutyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_job_duty
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UserJobDutyWithBLOBs record, @Param("example") UserJobDutyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_job_duty
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") UserJobDutyWithBLOBs record, @Param("example") UserJobDutyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_job_duty
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UserJobDuty record, @Param("example") UserJobDutyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_job_duty
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserJobDutyWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_job_duty
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(UserJobDutyWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_job_duty
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserJobDuty record);

    int saveIsFinalNode(int dutyId);

    List<UserJobDutyWithBLOBs> selectAllDataByDutyType(Map<String,Object> map);

    List<UserJobDutyWithBLOBs> getData(Map<String,Object> map);

    List<UserJobDutyWithBLOBs> getChildByDutyId(int dutyId);


}