package com.xoa.dao.appoauser;

import com.xoa.model.appoauser.AppOaUser;
import com.xoa.model.appoauser.AppOaUserExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import java.util.List;

public interface AppOaUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_oa_user
     *
     * @mbggenerated
     */
    int countByExample(AppOaUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_oa_user
     *
     * @mbggenerated
     */
    int deleteByExample(AppOaUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_oa_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_oa_user
     *
     * @mbggenerated
     */
    int insert(AppOaUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_oa_user
     *
     * @mbggenerated
     */
    int insertSelective(AppOaUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_oa_user
     *
     * @mbggenerated
     */
    List<AppOaUser> selectByExample(AppOaUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_oa_user
     *
     * @mbggenerated
     */
    AppOaUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_oa_user
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") AppOaUser record, @Param("example") AppOaUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_oa_user
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") AppOaUser record, @Param("example") AppOaUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_oa_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AppOaUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_oa_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AppOaUser record);

    @Select("SELECT\n" +
            "\tAPP_ID as appId ,\n" +
            "\tMOBIL_NO as mobilNo ,\n" +
            "\tOID as oid ,\n" +
            "\tUSER_ID as userId \n" +
            "FROM\n" +
            "\t`app_oa_user` \n" +
            "WHERE\n" +
            "\tMOBIL_NO = #{mobilNo}")
    AppOaUser selUserByOpenId(@Param("mobilNo") String mobilNo);
}