package com.xoa.dao.verification.MobileVerify;

import com.xoa.model.verification.MobileVerify.MobileVerify;
import com.xoa.model.verification.MobileVerify.MobileVerifyExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface MobileVerifyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_verify
     *
     * @mbggenerated
     */
    int countByExample(MobileVerifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_verify
     *
     * @mbggenerated
     */
    int deleteByExample(MobileVerifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_verify
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer verifyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_verify
     *
     * @mbggenerated
     */
    int insert(MobileVerify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_verify
     *
     * @mbggenerated
     */
    int insertSelective(MobileVerify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_verify
     *
     * @mbggenerated
     */
    List<MobileVerify> selectByExample(MobileVerifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_verify
     *
     * @mbggenerated
     */
    MobileVerify selectByPrimaryKey(Integer verifyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_verify
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") MobileVerify record, @Param("example") MobileVerifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_verify
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") MobileVerify record, @Param("example") MobileVerifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_verify
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MobileVerify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_verify
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MobileVerify record);

    MobileVerify getMobileVerify (@Param("userId") String userId,@Param("mobilNo") String mobilNo);
}