package com.xoa.dao.meet;

import com.xoa.model.meet.MeetingRoom;
import com.xoa.model.meet.MeetingRoomExample;
import com.xoa.model.meet.MeetingRoomWithBLOBs;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import java.util.List;
import java.util.Map;

public interface MeetingRoomMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_room
     *
     * @mbggenerated
     */
    int countByExample(MeetingRoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_room
     *
     * @mbggenerated
     */
    int deleteByExample(MeetingRoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_room
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_room
     *
     * @mbggenerated
     */
    int insert(MeetingRoomWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_room
     *
     * @mbggenerated
     */
    int insertSelective(MeetingRoomWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_room
     *
     * @mbggenerated
     */
    List<MeetingRoomWithBLOBs> selectByExampleWithBLOBs(MeetingRoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_room
     *
     * @mbggenerated
     */
    List<MeetingRoom> selectByExample(MeetingRoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_room
     *
     * @mbggenerated
     */
    MeetingRoomWithBLOBs selectByPrimaryKey(Integer sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_room
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") MeetingRoomWithBLOBs record, @Param("example") MeetingRoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_room
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") MeetingRoomWithBLOBs record, @Param("example") MeetingRoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_room
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") MeetingRoom record, @Param("example") MeetingRoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_room
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MeetingRoomWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_room
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(MeetingRoomWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_room
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MeetingRoom record);

    List<MeetingRoomWithBLOBs> getAllMeetRoomInfo(Map<String,Object>map);

    MeetingRoomWithBLOBs getMeetRoomBySid(@Param(value = "sid") Integer sid);

     void deleteMeetRoomBySid(@Param(value = "sid") Integer sid);

     void editMeetRoom(MeetingRoomWithBLOBs meetingRoomWithBLOBs);

    List<MeetingRoomWithBLOBs> getSomeMeetRoom(Map<String,Object>map);

    //查询会议室ID
    Integer getRoomConditionId(@Param("name") String name);

    @Select("SELECT MR_NAME FROM meeting_room WHERE SID = #{sid}")
    String getRoomName(@Param(value = "sid") Integer sid);

}