package com.xoa.model.qiyeWeixin;

import com.xoa.util.common.StringUtils;

public class QiyeWeixinConfig {

    // CorpID
    private String corpid;

    // 服务商密钥
    private String providerSecret;

    // 应用id
    private String suiteId;

    // 应用secret
    private String suiteSecret;

    // 企业微信后台推送ticket的url
    private String suiteTicketUrl;

    // 应用的凭证密钥
    private String corpsecret;

    // 应用id
    private String agentid;

    // 企业微信永久授权码
    private String permanentCode;

    // oa访问地址
    private String oaUrl;

    // 企业微信API接口域名
    private String apiDomain;

    // 通讯录密钥
    private String addressSecret;

    public String getAddressSecret() {
        return addressSecret;
    }

    public void setAddressSecret(String addressSecret) {
        this.addressSecret = addressSecret;
    }

    public String getApiDomain() {
        if(StringUtils.checkNull(apiDomain)){
            return "https://qyapi.weixin.qq.com";
        }
        return apiDomain;
    }

    public void setApiDomain(String apiDomain) {
        this.apiDomain = apiDomain;
    }

    public String getOaUrl() {
        return oaUrl;
    }

    public void setOaUrl(String oaUrl) {
        this.oaUrl = oaUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qiyeweixin_config.corpid
     *
     * @return the value of qiyeweixin_config.corpid
     *
     * @mbggenerated
     */
    public String getCorpid() {
        return corpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qiyeweixin_config.corpid
     *
     * @param corpid the value for qiyeweixin_config.corpid
     *
     * @mbggenerated
     */
    public void setCorpid(String corpid) {
        this.corpid = corpid == null ? null : corpid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qiyeweixin_config.provider_secret
     *
     * @return the value of qiyeweixin_config.provider_secret
     *
     * @mbggenerated
     */
    public String getProviderSecret() {
        return providerSecret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qiyeweixin_config.provider_secret
     *
     * @param providerSecret the value for qiyeweixin_config.provider_secret
     *
     * @mbggenerated
     */
    public void setProviderSecret(String providerSecret) {
        this.providerSecret = providerSecret == null ? null : providerSecret.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qiyeweixin_config.suite_id
     *
     * @return the value of qiyeweixin_config.suite_id
     *
     * @mbggenerated
     */
    public String getSuiteId() {
        return suiteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qiyeweixin_config.suite_id
     *
     * @param suiteId the value for qiyeweixin_config.suite_id
     *
     * @mbggenerated
     */
    public void setSuiteId(String suiteId) {
        this.suiteId = suiteId == null ? null : suiteId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qiyeweixin_config.suite_secret
     *
     * @return the value of qiyeweixin_config.suite_secret
     *
     * @mbggenerated
     */
    public String getSuiteSecret() {
        return suiteSecret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qiyeweixin_config.suite_secret
     *
     * @param suiteSecret the value for qiyeweixin_config.suite_secret
     *
     * @mbggenerated
     */
    public void setSuiteSecret(String suiteSecret) {
        this.suiteSecret = suiteSecret == null ? null : suiteSecret.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qiyeweixin_config.suite_ticket_url
     *
     * @return the value of qiyeweixin_config.suite_ticket_url
     *
     * @mbggenerated
     */
    public String getSuiteTicketUrl() {
        return suiteTicketUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qiyeweixin_config.suite_ticket_url
     *
     * @param suiteTicketUrl the value for qiyeweixin_config.suite_ticket_url
     *
     * @mbggenerated
     */
    public void setSuiteTicketUrl(String suiteTicketUrl) {
        this.suiteTicketUrl = suiteTicketUrl == null ? null : suiteTicketUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qiyeweixin_config.corpsecret
     *
     * @return the value of qiyeweixin_config.corpsecret
     *
     * @mbggenerated
     */
    public String getCorpsecret() {
        return corpsecret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qiyeweixin_config.corpsecret
     *
     * @param corpsecret the value for qiyeweixin_config.corpsecret
     *
     * @mbggenerated
     */
    public void setCorpsecret(String corpsecret) {
        this.corpsecret = corpsecret == null ? null : corpsecret.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qiyeweixin_config.agentid
     *
     * @return the value of qiyeweixin_config.agentid
     *
     * @mbggenerated
     */
    public String getAgentid() {
        return agentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qiyeweixin_config.agentid
     *
     * @param agentid the value for qiyeweixin_config.agentid
     *
     * @mbggenerated
     */
    public void setAgentid(String agentid) {
        this.agentid = agentid == null ? null : agentid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qiyeweixin_config.permanent_code
     *
     * @return the value of qiyeweixin_config.permanent_code
     *
     * @mbggenerated
     */
    public String getPermanentCode() {
        return permanentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qiyeweixin_config.permanent_code
     *
     * @param permanentCode the value for qiyeweixin_config.permanent_code
     *
     * @mbggenerated
     */
    public void setPermanentCode(String permanentCode) {
        this.permanentCode = permanentCode == null ? null : permanentCode.trim();
    }
}