package com.xoa.dao.comlicense;

import com.xoa.model.comlicense.ComlicenseVersion;
import com.xoa.model.comlicense.ComlicenseVersionExample;
import com.xoa.model.comlicense.ComlicenseVersionWithBLOBs;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ComlicenseVersionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comlicense_version
     *
     * @mbggenerated
     */
    int countByExample(ComlicenseVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comlicense_version
     *
     * @mbggenerated
     */
    int deleteByExample(ComlicenseVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comlicense_version
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer versionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comlicense_version
     *
     * @mbggenerated
     */
    int insert(ComlicenseVersionWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comlicense_version
     *
     * @mbggenerated
     */
    int insertSelective(ComlicenseVersionWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comlicense_version
     *
     * @mbggenerated
     */
    List<ComlicenseVersionWithBLOBs> selectByExampleWithBLOBs(ComlicenseVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comlicense_version
     *
     * @mbggenerated
     */
    List<ComlicenseVersion> selectByExample(ComlicenseVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comlicense_version
     *
     * @mbggenerated
     */
    ComlicenseVersionWithBLOBs selectByPrimaryKey(Integer versionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comlicense_version
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ComlicenseVersionWithBLOBs record, @Param("example") ComlicenseVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comlicense_version
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") ComlicenseVersionWithBLOBs record, @Param("example") ComlicenseVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comlicense_version
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ComlicenseVersion record, @Param("example") ComlicenseVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comlicense_version
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ComlicenseVersionWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comlicense_version
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(ComlicenseVersionWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comlicense_version
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ComlicenseVersion record);
}