package com.xoa.model.users;

public class UserSet {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_set.SET_ID
     *
     * @mbggenerated
     */
    private Integer setId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_set.USER_ID
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_set.SET_ITEM
     *
     * @mbggenerated
     */
    private String setItem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_set.SET_VALUE
     *
     * @mbggenerated
     */
    private String setValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_set.SET_ID
     *
     * @return the value of user_set.SET_ID
     *
     * @mbggenerated
     */
    public Integer getSetId() {
        return setId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_set.SET_ID
     *
     * @param setId the value for user_set.SET_ID
     *
     * @mbggenerated
     */
    public void setSetId(Integer setId) {
        this.setId = setId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_set.USER_ID
     *
     * @return the value of user_set.USER_ID
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_set.USER_ID
     *
     * @param userId the value for user_set.USER_ID
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_set.SET_ITEM
     *
     * @return the value of user_set.SET_ITEM
     *
     * @mbggenerated
     */
    public String getSetItem() {
        return setItem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_set.SET_ITEM
     *
     * @param setItem the value for user_set.SET_ITEM
     *
     * @mbggenerated
     */
    public void setSetItem(String setItem) {
        this.setItem = setItem == null ? null : setItem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_set.SET_VALUE
     *
     * @return the value of user_set.SET_VALUE
     *
     * @mbggenerated
     */
    public String getSetValue() {
        return setValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_set.SET_VALUE
     *
     * @param setValue the value for user_set.SET_VALUE
     *
     * @mbggenerated
     */
    public void setSetValue(String setValue) {
        this.setValue = setValue == null ? null : setValue.trim();
    }
}