package com.xoa.dao.ueTemplate;

import com.xoa.model.ueTemplate.UeTemplate;
import com.xoa.model.ueTemplate.UeTemplateExample;
import com.xoa.model.ueTemplate.UeTemplateWithBLOBs;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UeTemplateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ue_template
     *
     * @mbggenerated
     */
    int countByExample(UeTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ue_template
     *
     * @mbggenerated
     */
    int deleteByExample(UeTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ue_template
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ue_template
     *
     * @mbggenerated
     */
    int insert(UeTemplateWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ue_template
     *
     * @mbggenerated
     */
    int insertSelective(UeTemplateWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ue_template
     *
     * @mbggenerated
     */
    List<UeTemplateWithBLOBs> selectByExampleWithBLOBs(UeTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ue_template
     *
     * @mbggenerated
     */
    List<UeTemplate> selectByExample(UeTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ue_template
     *
     * @mbggenerated
     */
    UeTemplateWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ue_template
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UeTemplateWithBLOBs record, @Param("example") UeTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ue_template
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") UeTemplateWithBLOBs record, @Param("example") UeTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ue_template
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UeTemplate record, @Param("example") UeTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ue_template
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UeTemplateWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ue_template
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(UeTemplateWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ue_template
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UeTemplate record);

    List<UeTemplateWithBLOBs> getUeTemplateList();
}