package com.xoa.model.securityApproval;

import com.xoa.model.enclosure.Attachment;

import java.util.List;

public class SecurityApprovalWithBLOBs extends SecurityApproval {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column security_approval.OPERATION_CONTENT
     *
     * @mbggenerated
     */
    private String operationContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column security_approval.OPERATION_REASON
     *
     * @mbggenerated
     */
    private String operationReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column security_approval.ATTACHMENT_ID
     *
     * @mbggenerated
     */
    private String attachmentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column security_approval.ATTACHMENT_NAME
     *
     * @mbggenerated
     */
    private String attachmentName;

    private List<Attachment> attachmentList;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column security_approval.APPROVAL_OPINION
     *
     * @mbggenerated
     */
    private String approvalOpinion;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column security_approval.OPERATION_CONTENT
     *
     * @return the value of security_approval.OPERATION_CONTENT
     *
     * @mbggenerated
     */
    public String getOperationContent() {
        return operationContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column security_approval.OPERATION_CONTENT
     *
     * @param operationContent the value for security_approval.OPERATION_CONTENT
     *
     * @mbggenerated
     */
    public void setOperationContent(String operationContent) {
        this.operationContent = operationContent == null ? null : operationContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column security_approval.OPERATION_REASON
     *
     * @return the value of security_approval.OPERATION_REASON
     *
     * @mbggenerated
     */
    public String getOperationReason() {
        return operationReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column security_approval.OPERATION_REASON
     *
     * @param operationReason the value for security_approval.OPERATION_REASON
     *
     * @mbggenerated
     */
    public void setOperationReason(String operationReason) {
        this.operationReason = operationReason == null ? null : operationReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column security_approval.ATTACHMENT_ID
     *
     * @return the value of security_approval.ATTACHMENT_ID
     *
     * @mbggenerated
     */
    public String getAttachmentId() {
        return attachmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column security_approval.ATTACHMENT_ID
     *
     * @param attachmentId the value for security_approval.ATTACHMENT_ID
     *
     * @mbggenerated
     */
    public void setAttachmentId(String attachmentId) {
        this.attachmentId = attachmentId == null ? null : attachmentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column security_approval.ATTACHMENT_NAME
     *
     * @return the value of security_approval.ATTACHMENT_NAME
     *
     * @mbggenerated
     */
    public String getAttachmentName() {
        return attachmentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column security_approval.ATTACHMENT_NAME
     *
     * @param attachmentName the value for security_approval.ATTACHMENT_NAME
     *
     * @mbggenerated
     */
    public void setAttachmentName(String attachmentName) {
        this.attachmentName = attachmentName == null ? null : attachmentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column security_approval.APPROVAL_OPINION
     *
     * @return the value of security_approval.APPROVAL_OPINION
     *
     * @mbggenerated
     */
    public String getApprovalOpinion() {
        return approvalOpinion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column security_approval.APPROVAL_OPINION
     *
     * @param approvalOpinion the value for security_approval.APPROVAL_OPINION
     *
     * @mbggenerated
     */
    public void setApprovalOpinion(String approvalOpinion) {
        this.approvalOpinion = approvalOpinion == null ? null : approvalOpinion.trim();
    }

    public List<Attachment> getAttachmentList() {
        return attachmentList;
    }

    public void setAttachmentList(List<Attachment> attachmentList) {
        this.attachmentList = attachmentList;
    }
}