package com.xoa.model.securityApproval;

import com.xoa.model.department.Department;
import com.xoa.model.users.Users;

import java.util.Date;

public class SecurityApproval {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column security_approval.SP_ID
     *
     * @mbggenerated
     */
    private Integer spId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column security_approval.MODULE_TABLE
     *
     * @mbggenerated
     */
    private String moduleTable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column security_approval.RECORD_ID
     *
     * @mbggenerated
     */
    private Integer recordId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column security_approval.OPERATION_USER_ID
     *
     * @mbggenerated
     */
    private String operationUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column security_approval.OPERATION_TIME
     *
     * @mbggenerated
     */
    private Date operationTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column security_approval.OPERATION_TYPE
     *
     * @mbggenerated
     */
    private String operationType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column security_approval.APPROVER_USER_ID
     *
     * @mbggenerated
     */
    private String approverUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column security_approval.APPROVAL_TIME
     *
     * @mbggenerated
     */
    private Date approvalTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column security_approval.APPROVAL_STATUS
     *
     * @mbggenerated
     */
    private String approvalStatus;

    private Users users;

    private Department department;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column security_approval.SP_ID
     *
     * @return the value of security_approval.SP_ID
     *
     * @mbggenerated
     */
    public Integer getSpId() {
        return spId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column security_approval.SP_ID
     *
     * @param spId the value for security_approval.SP_ID
     *
     * @mbggenerated
     */
    public void setSpId(Integer spId) {
        this.spId = spId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column security_approval.MODULE_TABLE
     *
     * @return the value of security_approval.MODULE_TABLE
     *
     * @mbggenerated
     */
    public String getModuleTable() {
        return moduleTable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column security_approval.MODULE_TABLE
     *
     * @param moduleTable the value for security_approval.MODULE_TABLE
     *
     * @mbggenerated
     */
    public void setModuleTable(String moduleTable) {
        this.moduleTable = moduleTable == null ? null : moduleTable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column security_approval.RECORD_ID
     *
     * @return the value of security_approval.RECORD_ID
     *
     * @mbggenerated
     */
    public Integer getRecordId() {
        return recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column security_approval.RECORD_ID
     *
     * @param recordId the value for security_approval.RECORD_ID
     *
     * @mbggenerated
     */
    public void setRecordId(Integer recordId) {
        this.recordId = recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column security_approval.OPERATION_USER_ID
     *
     * @return the value of security_approval.OPERATION_USER_ID
     *
     * @mbggenerated
     */
    public String getOperationUserId() {
        return operationUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column security_approval.OPERATION_USER_ID
     *
     * @param operationUserId the value for security_approval.OPERATION_USER_ID
     *
     * @mbggenerated
     */
    public void setOperationUserId(String operationUserId) {
        this.operationUserId = operationUserId == null ? null : operationUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column security_approval.OPERATION_TIME
     *
     * @return the value of security_approval.OPERATION_TIME
     *
     * @mbggenerated
     */
    public Date getOperationTime() {
        return operationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column security_approval.OPERATION_TIME
     *
     * @param operationTime the value for security_approval.OPERATION_TIME
     *
     * @mbggenerated
     */
    public void setOperationTime(Date operationTime) {
        this.operationTime = operationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column security_approval.OPERATION_TYPE
     *
     * @return the value of security_approval.OPERATION_TYPE
     *
     * @mbggenerated
     */
    public String getOperationType() {
        return operationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column security_approval.OPERATION_TYPE
     *
     * @param operationType the value for security_approval.OPERATION_TYPE
     *
     * @mbggenerated
     */
    public void setOperationType(String operationType) {
        this.operationType = operationType == null ? null : operationType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column security_approval.APPROVER_USER_ID
     *
     * @return the value of security_approval.APPROVER_USER_ID
     *
     * @mbggenerated
     */
    public String getApproverUserId() {
        return approverUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column security_approval.APPROVER_USER_ID
     *
     * @param approverUserId the value for security_approval.APPROVER_USER_ID
     *
     * @mbggenerated
     */
    public void setApproverUserId(String approverUserId) {
        this.approverUserId = approverUserId == null ? null : approverUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column security_approval.APPROVAL_TIME
     *
     * @return the value of security_approval.APPROVAL_TIME
     *
     * @mbggenerated
     */
    public Date getApprovalTime() {
        return approvalTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column security_approval.APPROVAL_TIME
     *
     * @param approvalTime the value for security_approval.APPROVAL_TIME
     *
     * @mbggenerated
     */
    public void setApprovalTime(Date approvalTime) {
        this.approvalTime = approvalTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column security_approval.APPROVAL_STATUS
     *
     * @return the value of security_approval.APPROVAL_STATUS
     *
     * @mbggenerated
     */
    public String getApprovalStatus() {
        return approvalStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column security_approval.APPROVAL_STATUS
     *
     * @param approvalStatus the value for security_approval.APPROVAL_STATUS
     *
     * @mbggenerated
     */
    public void setApprovalStatus(String approvalStatus) {
        this.approvalStatus = approvalStatus == null ? null : approvalStatus.trim();
    }

    public Users getUsers() {
        return users;
    }

    public void setUsers(Users users) {
        this.users = users;
    }

    public Department getDepartment() {
        return department;
    }

    public void setDepartment(Department department) {
        this.department = department;
    }
}