package com.xoa.model.projectManage;

import com.alibaba.fastjson.annotation.JSONField;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.xoa.util.common.DataTree;
import org.springframework.format.annotation.DateTimeFormat;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

public class PlbProj extends DataTree {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plb_proj.PROJ_ID
     *
     * @mbggenerated
     */
    private Integer projId;

    private String thorProjNamef;

    private String projectFundsControl;

    private BigDecimal annualProjectFunds;

    public BigDecimal getAnnualProjectFunds() {
        return annualProjectFunds;
    }

    public void setAnnualProjectFunds(BigDecimal annualProjectFunds) {
        this.annualProjectFunds = annualProjectFunds;
    }

    public String getProjectFundsControl() {
        return projectFundsControl;
    }

    public void setProjectFundsControl(String projectFundsControl) {
        this.projectFundsControl = projectFundsControl;
    }

    public String getThorProjNamef() {
        return thorProjNamef;
    }

    public void setThorProjNamef(String thorProjNamef) {
        this.thorProjNamef = thorProjNamef;
    }

    private String deptName;
    private List<PlbProj> plbProjList;

    public List<PlbProj> getPlbProjList() {
        return plbProjList;
    }

    public void setPlbProjList(List<PlbProj> plbProjList) {
        this.plbProjList = plbProjList;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plb_proj.PROJ_NO
     *
     * @mbggenerated
     */
    private String projNo;
    private List<PbagExtInfo> pbagExtInfo;

    public List<PbagExtInfo> getPbagExtInfo() {
        return pbagExtInfo;
    }

    public void setPbagExtInfo(List<PbagExtInfo> pbagExtInfo) {
        this.pbagExtInfo = pbagExtInfo;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plb_proj.SORT_NO
     *
     * @mbggenerated
     */
    private Integer sortNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plb_proj.PROJ_PARENT
     *
     * @mbggenerated
     */
    private Integer projParent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plb_proj.BELONG_PROJ
     *
     * @mbggenerated
     */
    private Integer belongProj;

    public String getBelongProjMoney() {
        return belongProjMoney;
    }

    public void setBelongProjMoney(String belongProjMoney) {
        this.belongProjMoney = belongProjMoney;
    }

    private String belongProjMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plb_proj.PROJ_NAME
     *
     * @mbggenerated
     */
    private String projName;
    private String thorProjName;

    public String getThorProjName() {
        return thorProjName;
    }

    public void setThorProjName(String thorProjName) {
        this.thorProjName = thorProjName;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plb_proj.PROJ_ABBREVIATION
     *
     * @mbggenerated
     */
    private String projAbbreviation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plb_proj.PROJECT_STATUS
     *
     * @mbggenerated
     */
    private String projectStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plb_proj.BREAK_TIMES
     *
     * @mbggenerated
     */
    private Integer breakTimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plb_proj.DEPT_ID
     *
     * @mbggenerated
     */
    private Integer deptId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plb_proj.PROJ_LEVEL
     *
     * @mbggenerated
     */
    private String projLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plb_proj.PLAN_STATRT_TIME
     *
     * @mbggenerated
     */

    @DateTimeFormat(pattern = "yyyy-MM-dd")
    @JSONField(format = "yyyy-MM-dd")
    @JsonFormat(pattern = "yyyy-MM-dd")
    private Date planStatrtTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plb_proj.PLAN_END_TIME
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    @JSONField(format = "yyyy-MM-dd")
    @JsonFormat(pattern = "yyyy-MM-dd")
    private Date planEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plb_proj.REAL_BEGIN_DATE
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    @JSONField(format = "yyyy-MM-dd")
    @JsonFormat(pattern = "yyyy-MM-dd")
    private Date realBeginDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plb_proj.REAL_END_DATE
     *
     * @mbggenerated
     */

    @DateTimeFormat(pattern = "yyyy-MM-dd")
    @JSONField(format = "yyyy-MM-dd")
    @JsonFormat(pattern = "yyyy-MM-dd")
    private Date realEndDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plb_proj.BUDGET_YN
     *
     * @mbggenerated
     */
    private String budgetYn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plb_proj.RUN_ID
     *
     * @mbggenerated
     */
    private Integer runId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plb_proj.APPROVAL_STATUS
     *
     * @mbggenerated
     */
    private String approvalStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plb_proj.DEL_FLAG
     *
     * @mbggenerated
     */
    private String delFlag;
    private String projType;

    public String getProjType() {
        return projType;
    }

    public void setProjType(String projType) {
        this.projType = projType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plb_proj.PROJ_ID
     *
     * @return the value of plb_proj.PROJ_ID
     *
     * @mbggenerated
     */
    public Integer getProjId() {
        return projId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plb_proj.PROJ_ID
     *
     * @param projId the value for plb_proj.PROJ_ID
     *
     * @mbggenerated
     */
    public void setProjId(Integer projId) {
        this.projId = projId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plb_proj.PROJ_NO
     *
     * @return the value of plb_proj.PROJ_NO
     *
     * @mbggenerated
     */
    public String getProjNo() {
        return projNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plb_proj.PROJ_NO
     *
     * @param projNo the value for plb_proj.PROJ_NO
     *
     * @mbggenerated
     */
    public void setProjNo(String projNo) {
        this.projNo = projNo == null ? null : projNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plb_proj.SORT_NO
     *
     * @return the value of plb_proj.SORT_NO
     *
     * @mbggenerated
     */
    public Integer getSortNo() {
        return sortNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plb_proj.SORT_NO
     *
     * @param sortNo the value for plb_proj.SORT_NO
     *
     * @mbggenerated
     */
    public void setSortNo(Integer sortNo) {
        this.sortNo = sortNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plb_proj.PROJ_PARENT
     *
     * @return the value of plb_proj.PROJ_PARENT
     *
     * @mbggenerated
     */
    public Integer getProjParent() {
        return projParent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plb_proj.PROJ_PARENT
     *
     * @param projParent the value for plb_proj.PROJ_PARENT
     *
     * @mbggenerated
     */
    public void setProjParent(Integer projParent) {
        this.projParent = projParent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plb_proj.BELONG_PROJ
     *
     * @return the value of plb_proj.BELONG_PROJ
     *
     * @mbggenerated
     */
    public Integer getBelongProj() {
        return belongProj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plb_proj.BELONG_PROJ
     *
     * @param belongProj the value for plb_proj.BELONG_PROJ
     *
     * @mbggenerated
     */
    public void setBelongProj(Integer belongProj) {
        this.belongProj = belongProj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plb_proj.PROJ_NAME
     *
     * @return the value of plb_proj.PROJ_NAME
     *
     * @mbggenerated
     */
    public String getProjName() {
        return projName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plb_proj.PROJ_NAME
     *
     * @param projName the value for plb_proj.PROJ_NAME
     *
     * @mbggenerated
     */
    public void setProjName(String projName) {
        this.projName = projName == null ? null : projName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plb_proj.PROJ_ABBREVIATION
     *
     * @return the value of plb_proj.PROJ_ABBREVIATION
     *
     * @mbggenerated
     */
    public String getProjAbbreviation() {
        return projAbbreviation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plb_proj.PROJ_ABBREVIATION
     *
     * @param projAbbreviation the value for plb_proj.PROJ_ABBREVIATION
     *
     * @mbggenerated
     */
    public void setProjAbbreviation(String projAbbreviation) {
        this.projAbbreviation = projAbbreviation == null ? null : projAbbreviation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plb_proj.PROJECT_STATUS
     *
     * @return the value of plb_proj.PROJECT_STATUS
     *
     * @mbggenerated
     */
    public String getProjectStatus() {
        return projectStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plb_proj.PROJECT_STATUS
     *
     * @param projectStatus the value for plb_proj.PROJECT_STATUS
     *
     * @mbggenerated
     */
    public void setProjectStatus(String projectStatus) {
        this.projectStatus = projectStatus == null ? null : projectStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plb_proj.BREAK_TIMES
     *
     * @return the value of plb_proj.BREAK_TIMES
     *
     * @mbggenerated
     */
    public Integer getBreakTimes() {
        return breakTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plb_proj.BREAK_TIMES
     *
     * @param breakTimes the value for plb_proj.BREAK_TIMES
     *
     * @mbggenerated
     */
    public void setBreakTimes(Integer breakTimes) {
        this.breakTimes = breakTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plb_proj.DEPT_ID
     *
     * @return the value of plb_proj.DEPT_ID
     *
     * @mbggenerated
     */
    public Integer getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plb_proj.DEPT_ID
     *
     * @param deptId the value for plb_proj.DEPT_ID
     *
     * @mbggenerated
     */
    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plb_proj.PROJ_LEVEL
     *
     * @return the value of plb_proj.PROJ_LEVEL
     *
     * @mbggenerated
     */
    public String getProjLevel() {
        return projLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plb_proj.PROJ_LEVEL
     *
     * @param projLevel the value for plb_proj.PROJ_LEVEL
     *
     * @mbggenerated
     */
    public void setProjLevel(String projLevel) {
        this.projLevel = projLevel == null ? null : projLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plb_proj.PLAN_STATRT_TIME
     *
     * @return the value of plb_proj.PLAN_STATRT_TIME
     *
     * @mbggenerated
     */
    public Date getPlanStatrtTime() {
        return planStatrtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plb_proj.PLAN_STATRT_TIME
     *
     * @param planStatrtTime the value for plb_proj.PLAN_STATRT_TIME
     *
     * @mbggenerated
     */
    public void setPlanStatrtTime(Date planStatrtTime) {
        this.planStatrtTime = planStatrtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plb_proj.PLAN_END_TIME
     *
     * @return the value of plb_proj.PLAN_END_TIME
     *
     * @mbggenerated
     */
    public Date getPlanEndTime() {
        return planEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plb_proj.PLAN_END_TIME
     *
     * @param planEndTime the value for plb_proj.PLAN_END_TIME
     *
     * @mbggenerated
     */
    public void setPlanEndTime(Date planEndTime) {
        this.planEndTime = planEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plb_proj.REAL_BEGIN_DATE
     *
     * @return the value of plb_proj.REAL_BEGIN_DATE
     *
     * @mbggenerated
     */
    public Date getRealBeginDate() {
        return realBeginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plb_proj.REAL_BEGIN_DATE
     *
     * @param realBeginDate the value for plb_proj.REAL_BEGIN_DATE
     *
     * @mbggenerated
     */
    public void setRealBeginDate(Date realBeginDate) {
        this.realBeginDate = realBeginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plb_proj.REAL_END_DATE
     *
     * @return the value of plb_proj.REAL_END_DATE
     *
     * @mbggenerated
     */
    public Date getRealEndDate() {
        return realEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plb_proj.REAL_END_DATE
     *
     * @param realEndDate the value for plb_proj.REAL_END_DATE
     *
     * @mbggenerated
     */
    public void setRealEndDate(Date realEndDate) {
        this.realEndDate = realEndDate;
    }
    private String buildContent;

    public String getCheckStandard() {
        return checkStandard;
    }

    public void setCheckStandard(String checkStandard) {
        this.checkStandard = checkStandard;
    }

    private String checkStandard;

    public String getBuildContent() {
        return buildContent;
    }

    public void setBuildContent(String buildContent) {
        this.buildContent = buildContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plb_proj.BUDGET_YN
     *
     * @return the value of plb_proj.BUDGET_YN
     *
     * @mbggenerated
     */
    public String getBudgetYn() {
        return budgetYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plb_proj.BUDGET_YN
     *
     * @param budgetYn the value for plb_proj.BUDGET_YN
     *
     * @mbggenerated
     */
    public void setBudgetYn(String budgetYn) {
        this.budgetYn = budgetYn == null ? null : budgetYn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plb_proj.RUN_ID
     *
     * @return the value of plb_proj.RUN_ID
     *
     * @mbggenerated
     */
    public Integer getRunId() {
        return runId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plb_proj.RUN_ID
     *
     * @param runId the value for plb_proj.RUN_ID
     *
     * @mbggenerated
     */
    public void setRunId(Integer runId) {
        this.runId = runId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plb_proj.APPROVAL_STATUS
     *
     * @return the value of plb_proj.APPROVAL_STATUS
     *
     * @mbggenerated
     */
    public String getApprovalStatus() {
        return approvalStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plb_proj.APPROVAL_STATUS
     *
     * @param approvalStatus the value for plb_proj.APPROVAL_STATUS
     *
     * @mbggenerated
     */
    public void setApprovalStatus(String approvalStatus) {
        this.approvalStatus = approvalStatus == null ? null : approvalStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plb_proj.DEL_FLAG
     *
     * @return the value of plb_proj.DEL_FLAG
     *
     * @mbggenerated
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plb_proj.DEL_FLAG
     *
     * @param delFlag the value for plb_proj.DEL_FLAG
     *
     * @mbggenerated
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag == null ? null : delFlag.trim();
    }

    public String getDeptName() {
        return deptName;
    }

    public void setDeptName(String deptName) {
        this.deptName = deptName;
    }
}