package com.xoa.model.projectManage;

import com.alibaba.fastjson.annotation.JSONField;
import com.fasterxml.jackson.annotation.JsonFormat;
import org.springframework.format.annotation.DateTimeFormat;

import java.math.BigDecimal;
import java.util.Date;

public class ProjExtInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proj_ext_info.PROJ_EXT_ID
     *
     * @mbggenerated
     */
    private Integer projExtId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proj_ext_info.PROJ_ID
     *
     * @mbggenerated
     */
    private Integer projId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proj_ext_info.PROJ_TYPE
     *
     * @mbggenerated
     */
    private String projType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proj_ext_info.MANAGE_MODEL
     *
     * @mbggenerated
     */
    private String manageModel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proj_ext_info.OPERATE_MODEL
     *
     * @mbggenerated
     */
    private String operateModel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proj_ext_info.PROJ_PLACE
     *
     * @mbggenerated
     */
    private String projPlace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proj_ext_info.LONGITUDE
     *
     * @mbggenerated
     */
    private String longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proj_ext_info.LATITUDE
     *
     * @mbggenerated
     */
    private String latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proj_ext_info.BUILTUP_AREA
     *
     * @mbggenerated
     */
    private BigDecimal builtupArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proj_ext_info.OWNER_UNIT
     *
     * @mbggenerated
     */
    private String ownerUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proj_ext_info.MANAGE_UNIT
     *
     * @mbggenerated
     */
    private String manageUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proj_ext_info.WINNING_DATE
     *
     * @mbggenerated
     */

    @DateTimeFormat(pattern = "yyyy-MM-dd")
    @JSONField(format = "yyyy-MM-dd")
    @JsonFormat(pattern = "yyyy-MM-dd")
    private Date winningDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proj_ext_info.CONTRACT_DATE
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    @JSONField(format = "yyyy-MM-dd")
    @JsonFormat(pattern = "yyyy-MM-dd")
    private Date contractDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proj_ext_info.CONTRACT_START_DATE
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    @JSONField(format = "yyyy-MM-dd")
    @JsonFormat(pattern = "yyyy-MM-dd")
    private Date contractStartDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proj_ext_info.CONTRACT_END_DATE
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    @JSONField(format = "yyyy-MM-dd")
    @JsonFormat(pattern = "yyyy-MM-dd")
    private Date contractEndDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proj_ext_info.ESTABLISHMENT_DATE
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    @JSONField(format = "yyyy-MM-dd")
    @JsonFormat(pattern = "yyyy-MM-dd")
    private Date establishmentDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proj_ext_info.APPOINTMENT_DATE
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    @JSONField(format = "yyyy-MM-dd")
    @JsonFormat(pattern = "yyyy-MM-dd")
    private Date appointmentDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proj_ext_info.CONTRACT_CONTINUED_DATE
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    @JSONField(format = "yyyy-MM-dd")
    @JsonFormat(pattern = "yyyy-MM-dd")
    private String contractContinuedDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proj_ext_info.CONTRACT_MONEY
     *
     * @mbggenerated
     */
    private BigDecimal contractMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proj_ext_info.INVESTMENT_TYPE
     *
     * @mbggenerated
     */
    private String investmentType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proj_ext_info.INVESTMENT_SCALE
     *
     * @mbggenerated
     */
    private BigDecimal investmentScale;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proj_ext_info.OPERATION_SUBJECT
     *
     * @mbggenerated
     */
    private Integer customerId;

    public Integer getCustomerId() {
        return customerId;
    }

    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proj_ext_info.INCOME_MODE
     *
     * @mbggenerated
     */
    private String incomeMode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proj_ext_info.INVESTMENT_GC_SCALE
     *
     * @mbggenerated
     */
    private BigDecimal investmentGcScale;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proj_ext_info.PUT_OPERATION
     *
     * @mbggenerated
     */
    private String putOperation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proj_ext_info.EQUITY_RATIO
     *
     * @mbggenerated
     */
    private String equityRatio;

    private String delFlag;

    public String getDelFlag() {
        return delFlag;
    }

    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proj_ext_info.OPERATION_DATE
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    @JSONField(format = "yyyy-MM-dd")
    @JsonFormat(pattern = "yyyy-MM-dd")
    private Date operationDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proj_ext_info.PROJ_EXT_ID
     *
     * @return the value of proj_ext_info.PROJ_EXT_ID
     *
     * @mbggenerated
     */
    public Integer getProjExtId() {
        return projExtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proj_ext_info.PROJ_EXT_ID
     *
     * @param projExtId the value for proj_ext_info.PROJ_EXT_ID
     *
     * @mbggenerated
     */
    public void setProjExtId(Integer projExtId) {
        this.projExtId = projExtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proj_ext_info.PROJ_ID
     *
     * @return the value of proj_ext_info.PROJ_ID
     *
     * @mbggenerated
     */
    public Integer getProjId() {
        return projId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proj_ext_info.PROJ_ID
     *
     * @param projId the value for proj_ext_info.PROJ_ID
     *
     * @mbggenerated
     */
    public void setProjId(Integer projId) {
        this.projId = projId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proj_ext_info.PROJ_TYPE
     *
     * @return the value of proj_ext_info.PROJ_TYPE
     *
     * @mbggenerated
     */
    public String getProjType() {
        return projType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proj_ext_info.PROJ_TYPE
     *
     * @param projType the value for proj_ext_info.PROJ_TYPE
     *
     * @mbggenerated
     */
    public void setProjType(String projType) {
        this.projType = projType == null ? null : projType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proj_ext_info.MANAGE_MODEL
     *
     * @return the value of proj_ext_info.MANAGE_MODEL
     *
     * @mbggenerated
     */
    public String getManageModel() {
        return manageModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proj_ext_info.MANAGE_MODEL
     *
     * @param manageModel the value for proj_ext_info.MANAGE_MODEL
     *
     * @mbggenerated
     */
    public void setManageModel(String manageModel) {
        this.manageModel = manageModel == null ? null : manageModel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proj_ext_info.OPERATE_MODEL
     *
     * @return the value of proj_ext_info.OPERATE_MODEL
     *
     * @mbggenerated
     */
    public String getOperateModel() {
        return operateModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proj_ext_info.OPERATE_MODEL
     *
     * @param operateModel the value for proj_ext_info.OPERATE_MODEL
     *
     * @mbggenerated
     */
    public void setOperateModel(String operateModel) {
        this.operateModel = operateModel == null ? null : operateModel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proj_ext_info.PROJ_PLACE
     *
     * @return the value of proj_ext_info.PROJ_PLACE
     *
     * @mbggenerated
     */
    public String getProjPlace() {
        return projPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proj_ext_info.PROJ_PLACE
     *
     * @param projPlace the value for proj_ext_info.PROJ_PLACE
     *
     * @mbggenerated
     */
    public void setProjPlace(String projPlace) {
        this.projPlace = projPlace == null ? null : projPlace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proj_ext_info.LONGITUDE
     *
     * @return the value of proj_ext_info.LONGITUDE
     *
     * @mbggenerated
     */
    public String getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proj_ext_info.LONGITUDE
     *
     * @param longitude the value for proj_ext_info.LONGITUDE
     *
     * @mbggenerated
     */
    public void setLongitude(String longitude) {
        this.longitude = longitude == null ? null : longitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proj_ext_info.LATITUDE
     *
     * @return the value of proj_ext_info.LATITUDE
     *
     * @mbggenerated
     */
    public String getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proj_ext_info.LATITUDE
     *
     * @param latitude the value for proj_ext_info.LATITUDE
     *
     * @mbggenerated
     */
    public void setLatitude(String latitude) {
        this.latitude = latitude == null ? null : latitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proj_ext_info.BUILTUP_AREA
     *
     * @return the value of proj_ext_info.BUILTUP_AREA
     *
     * @mbggenerated
     */
    public BigDecimal getBuiltupArea() {
        return builtupArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proj_ext_info.BUILTUP_AREA
     *
     * @param builtupArea the value for proj_ext_info.BUILTUP_AREA
     *
     * @mbggenerated
     */
    public void setBuiltupArea(BigDecimal builtupArea) {
        this.builtupArea = builtupArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proj_ext_info.OWNER_UNIT
     *
     * @return the value of proj_ext_info.OWNER_UNIT
     *
     * @mbggenerated
     */
    public String getOwnerUnit() {
        return ownerUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proj_ext_info.OWNER_UNIT
     *
     * @param ownerUnit the value for proj_ext_info.OWNER_UNIT
     *
     * @mbggenerated
     */
    public void setOwnerUnit(String ownerUnit) {
        this.ownerUnit = ownerUnit == null ? null : ownerUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proj_ext_info.MANAGE_UNIT
     *
     * @return the value of proj_ext_info.MANAGE_UNIT
     *
     * @mbggenerated
     */
    public String getManageUnit() {
        return manageUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proj_ext_info.MANAGE_UNIT
     *
     * @param manageUnit the value for proj_ext_info.MANAGE_UNIT
     *
     * @mbggenerated
     */
    public void setManageUnit(String manageUnit) {
        this.manageUnit = manageUnit == null ? null : manageUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proj_ext_info.WINNING_DATE
     *
     * @return the value of proj_ext_info.WINNING_DATE
     *
     * @mbggenerated
     */
    public Date getWinningDate() {
        return winningDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proj_ext_info.WINNING_DATE
     *
     * @param winningDate the value for proj_ext_info.WINNING_DATE
     *
     * @mbggenerated
     */
    public void setWinningDate(Date winningDate) {
        this.winningDate = winningDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proj_ext_info.CONTRACT_DATE
     *
     * @return the value of proj_ext_info.CONTRACT_DATE
     *
     * @mbggenerated
     */
    public Date getContractDate() {
        return contractDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proj_ext_info.CONTRACT_DATE
     *
     * @param contractDate the value for proj_ext_info.CONTRACT_DATE
     *
     * @mbggenerated
     */
    public void setContractDate(Date contractDate) {
        this.contractDate = contractDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proj_ext_info.CONTRACT_START_DATE
     *
     * @return the value of proj_ext_info.CONTRACT_START_DATE
     *
     * @mbggenerated
     */
    public Date getContractStartDate() {
        return contractStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proj_ext_info.CONTRACT_START_DATE
     *
     * @param contractStartDate the value for proj_ext_info.CONTRACT_START_DATE
     *
     * @mbggenerated
     */
    public void setContractStartDate(Date contractStartDate) {
        this.contractStartDate = contractStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proj_ext_info.CONTRACT_END_DATE
     *
     * @return the value of proj_ext_info.CONTRACT_END_DATE
     *
     * @mbggenerated
     */
    public Date getContractEndDate() {
        return contractEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proj_ext_info.CONTRACT_END_DATE
     *
     * @param contractEndDate the value for proj_ext_info.CONTRACT_END_DATE
     *
     * @mbggenerated
     */
    public void setContractEndDate(Date contractEndDate) {
        this.contractEndDate = contractEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proj_ext_info.ESTABLISHMENT_DATE
     *
     * @return the value of proj_ext_info.ESTABLISHMENT_DATE
     *
     * @mbggenerated
     */
    public Date getEstablishmentDate() {
        return establishmentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proj_ext_info.ESTABLISHMENT_DATE
     *
     * @param establishmentDate the value for proj_ext_info.ESTABLISHMENT_DATE
     *
     * @mbggenerated
     */
    public void setEstablishmentDate(Date establishmentDate) {
        this.establishmentDate = establishmentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proj_ext_info.APPOINTMENT_DATE
     *
     * @return the value of proj_ext_info.APPOINTMENT_DATE
     *
     * @mbggenerated
     */
    public Date getAppointmentDate() {
        return appointmentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proj_ext_info.APPOINTMENT_DATE
     *
     * @param appointmentDate the value for proj_ext_info.APPOINTMENT_DATE
     *
     * @mbggenerated
     */
    public void setAppointmentDate(Date appointmentDate) {
        this.appointmentDate = appointmentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proj_ext_info.CONTRACT_CONTINUED_DATE
     *
     * @return the value of proj_ext_info.CONTRACT_CONTINUED_DATE
     *
     * @mbggenerated
     */
    public String getContractContinuedDate() {
        return contractContinuedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proj_ext_info.CONTRACT_CONTINUED_DATE
     *
     * @param contractContinuedDate the value for proj_ext_info.CONTRACT_CONTINUED_DATE
     *
     * @mbggenerated
     */
    public void setContractContinuedDate(String contractContinuedDate) {
        this.contractContinuedDate = contractContinuedDate == null ? null : contractContinuedDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proj_ext_info.CONTRACT_MONEY
     *
     * @return the value of proj_ext_info.CONTRACT_MONEY
     *
     * @mbggenerated
     */
    public BigDecimal getContractMoney() {
        return contractMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proj_ext_info.CONTRACT_MONEY
     *
     * @param contractMoney the value for proj_ext_info.CONTRACT_MONEY
     *
     * @mbggenerated
     */
    public void setContractMoney(BigDecimal contractMoney) {
        this.contractMoney = contractMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proj_ext_info.INVESTMENT_TYPE
     *
     * @return the value of proj_ext_info.INVESTMENT_TYPE
     *
     * @mbggenerated
     */
    public String getInvestmentType() {
        return investmentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proj_ext_info.INVESTMENT_TYPE
     *
     * @param investmentType the value for proj_ext_info.INVESTMENT_TYPE
     *
     * @mbggenerated
     */
    public void setInvestmentType(String investmentType) {
        this.investmentType = investmentType == null ? null : investmentType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proj_ext_info.INVESTMENT_SCALE
     *
     * @return the value of proj_ext_info.INVESTMENT_SCALE
     *
     * @mbggenerated
     */
    public BigDecimal getInvestmentScale() {
        return investmentScale;
    }

    public void setInvestmentScale(BigDecimal investmentScale) {
        this.investmentScale = investmentScale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proj_ext_info.OPERATION_SUBJECT
     *
     * @return the value of proj_ext_info.OPERATION_SUBJECT
     *
     * @mbggenerated
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proj_ext_info.INCOME_MODE
     *
     * @return the value of proj_ext_info.INCOME_MODE
     *
     * @mbggenerated
     */
    public String getIncomeMode() {
        return incomeMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proj_ext_info.INCOME_MODE
     *
     * @param incomeMode the value for proj_ext_info.INCOME_MODE
     *
     * @mbggenerated
     */
    public void setIncomeMode(String incomeMode) {
        this.incomeMode = incomeMode == null ? null : incomeMode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proj_ext_info.INVESTMENT_GC_SCALE
     *
     * @return the value of proj_ext_info.INVESTMENT_GC_SCALE
     *
     * @mbggenerated
     */
    public BigDecimal getInvestmentGcScale() {
        return investmentGcScale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proj_ext_info.INVESTMENT_GC_SCALE
     *
     * @param investmentGcScale the value for proj_ext_info.INVESTMENT_GC_SCALE
     *
     * @mbggenerated
     */
    public void setInvestmentGcScale(BigDecimal investmentGcScale) {
        this.investmentGcScale = investmentGcScale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proj_ext_info.PUT_OPERATION
     *
     * @return the value of proj_ext_info.PUT_OPERATION
     *
     * @mbggenerated
     */
    public String getPutOperation() {
        return putOperation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proj_ext_info.PUT_OPERATION
     *
     * @param putOperation the value for proj_ext_info.PUT_OPERATION
     *
     * @mbggenerated
     */
    public void setPutOperation(String putOperation) {
        this.putOperation = putOperation == null ? null : putOperation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proj_ext_info.EQUITY_RATIO
     *
     * @return the value of proj_ext_info.EQUITY_RATIO
     *
     * @mbggenerated
     */
    public String getEquityRatio() {
        return equityRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proj_ext_info.EQUITY_RATIO
     *
     * @param equityRatio the value for proj_ext_info.EQUITY_RATIO
     *
     * @mbggenerated
     */
    public void setEquityRatio(String equityRatio) {
        this.equityRatio = equityRatio == null ? null : equityRatio.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proj_ext_info.OPERATION_DATE
     *
     * @return the value of proj_ext_info.OPERATION_DATE
     *
     * @mbggenerated
     */
    public Date getOperationDate() {
        return operationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proj_ext_info.OPERATION_DATE
     *
     * @param operationDate the value for proj_ext_info.OPERATION_DATE
     *
     * @mbggenerated
     */
    public void setOperationDate(Date operationDate) {
        this.operationDate = operationDate;
    }
}