package com.xoa.dao.users;

import com.xoa.model.users.UserExt2;
import com.xoa.model.users.UserExt2Example;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UserExt2Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_ext2
     *
     * @mbggenerated
     */
    int countByExample(UserExt2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_ext2
     *
     * @mbggenerated
     */
    int deleteByExample(UserExt2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_ext2
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_ext2
     *
     * @mbggenerated
     */
    int insert(UserExt2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_ext2
     *
     * @mbggenerated
     */
    int insertSelective(UserExt2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_ext2
     *
     * @mbggenerated
     */
    List<UserExt2> selectByExample(UserExt2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_ext2
     *
     * @mbggenerated
     */
    UserExt2 selectByPrimaryKey(Integer uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_ext2
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UserExt2 record, @Param("example") UserExt2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_ext2
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UserExt2 record, @Param("example") UserExt2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_ext2
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserExt2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_ext2
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserExt2 record);

    int addUserExt(UserExt2 userExt2);

    int editUserExt(UserExt2 userExt2);

    UserExt2 userExt2Info(UserExt2 userExt2);
}