package com.xoa.dao.users;

import com.xoa.model.users.UserMobile;
import com.xoa.model.users.UserMobileExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface UserMobileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_mobile
     *
     * @mbggenerated
     */
    int countByExample(UserMobileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_mobile
     *
     * @mbggenerated
     */
    int deleteByExample(UserMobileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_mobile
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer muserId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_mobile
     *
     * @mbggenerated
     */
    int insert(UserMobile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_mobile
     *
     * @mbggenerated
     */
    int insertSelective(UserMobile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_mobile
     *
     * @mbggenerated
     */
    List<UserMobile> selectByExample(UserMobileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_mobile
     *
     * @mbggenerated
     */
    UserMobile selectByPrimaryKey(Integer muserId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_mobile
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UserMobile record, @Param("example") UserMobileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_mobile
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UserMobile record, @Param("example") UserMobileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_mobile
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserMobile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_mobile
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserMobile record);

    List<UserMobile> selectByMap(Map map);
}