package com.xoa.model.alidaas;

public class AlidaasSet {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alidaas_set.IDAAS_ID
     *
     * @mbggenerated
     */
    private Integer idaasId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alidaas_set.APP_ID
     *
     * @mbggenerated
     */
    private String appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alidaas_set.APP_NAME
     *
     * @mbggenerated
     */
    private String appName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alidaas_set.API_DOMAIN
     *
     * @mbggenerated
     */
    private String apiDomain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alidaas_set.IDAAS_BASE_URL
     *
     * @mbggenerated
     */
    private String idaasBaseUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alidaas_set.API_KEY
     *
     * @mbggenerated
     */
    private String apiKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alidaas_set.API_SECRET
     *
     * @mbggenerated
     */
    private String apiSecret;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alidaas_set.OID
     *
     * @mbggenerated
     */
    private String oid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alidaas_set.JWT_PUBLICKEY
     *
     * @mbggenerated
     */
    private String jwtPublickey;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alidaas_set.IDAAS_ID
     *
     * @return the value of alidaas_set.IDAAS_ID
     *
     * @mbggenerated
     */
    public Integer getIdaasId() {
        return idaasId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alidaas_set.IDAAS_ID
     *
     * @param idaasId the value for alidaas_set.IDAAS_ID
     *
     * @mbggenerated
     */
    public void setIdaasId(Integer idaasId) {
        this.idaasId = idaasId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alidaas_set.APP_ID
     *
     * @return the value of alidaas_set.APP_ID
     *
     * @mbggenerated
     */
    public String getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alidaas_set.APP_ID
     *
     * @param appId the value for alidaas_set.APP_ID
     *
     * @mbggenerated
     */
    public void setAppId(String appId) {
        this.appId = appId == null ? null : appId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alidaas_set.APP_NAME
     *
     * @return the value of alidaas_set.APP_NAME
     *
     * @mbggenerated
     */
    public String getAppName() {
        return appName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alidaas_set.APP_NAME
     *
     * @param appName the value for alidaas_set.APP_NAME
     *
     * @mbggenerated
     */
    public void setAppName(String appName) {
        this.appName = appName == null ? null : appName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alidaas_set.API_DOMAIN
     *
     * @return the value of alidaas_set.API_DOMAIN
     *
     * @mbggenerated
     */
    public String getApiDomain() {
        return apiDomain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alidaas_set.API_DOMAIN
     *
     * @param apiDomain the value for alidaas_set.API_DOMAIN
     *
     * @mbggenerated
     */
    public void setApiDomain(String apiDomain) {
        this.apiDomain = apiDomain == null ? null : apiDomain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alidaas_set.IDAAS_BASE_URL
     *
     * @return the value of alidaas_set.IDAAS_BASE_URL
     *
     * @mbggenerated
     */
    public String getIdaasBaseUrl() {
        return idaasBaseUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alidaas_set.IDAAS_BASE_URL
     *
     * @param idaasBaseUrl the value for alidaas_set.IDAAS_BASE_URL
     *
     * @mbggenerated
     */
    public void setIdaasBaseUrl(String idaasBaseUrl) {
        this.idaasBaseUrl = idaasBaseUrl == null ? null : idaasBaseUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alidaas_set.API_KEY
     *
     * @return the value of alidaas_set.API_KEY
     *
     * @mbggenerated
     */
    public String getApiKey() {
        return apiKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alidaas_set.API_KEY
     *
     * @param apiKey the value for alidaas_set.API_KEY
     *
     * @mbggenerated
     */
    public void setApiKey(String apiKey) {
        this.apiKey = apiKey == null ? null : apiKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alidaas_set.API_SECRET
     *
     * @return the value of alidaas_set.API_SECRET
     *
     * @mbggenerated
     */
    public String getApiSecret() {
        return apiSecret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alidaas_set.API_SECRET
     *
     * @param apiSecret the value for alidaas_set.API_SECRET
     *
     * @mbggenerated
     */
    public void setApiSecret(String apiSecret) {
        this.apiSecret = apiSecret == null ? null : apiSecret.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alidaas_set.OID
     *
     * @return the value of alidaas_set.OID
     *
     * @mbggenerated
     */
    public String getOid() {
        return oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alidaas_set.OID
     *
     * @param oid the value for alidaas_set.OID
     *
     * @mbggenerated
     */
    public void setOid(String oid) {
        this.oid = oid == null ? null : oid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alidaas_set.JWT_PUBLICKEY
     *
     * @return the value of alidaas_set.JWT_PUBLICKEY
     *
     * @mbggenerated
     */
    public String getJwtPublickey() {
        return jwtPublickey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alidaas_set.JWT_PUBLICKEY
     *
     * @param jwtPublickey the value for alidaas_set.JWT_PUBLICKEY
     *
     * @mbggenerated
     */
    public void setJwtPublickey(String jwtPublickey) {
        this.jwtPublickey = jwtPublickey == null ? null : jwtPublickey.trim();
    }
}