package com.xoa.model.alidaas;

import java.util.Date;

public class SysHrStaffLeave {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr_staff_leave.LEAVE_ID
     *
     * @mbggenerated
     */
    private Integer leaveId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr_staff_leave.CREATE_USER_ID
     *
     * @mbggenerated
     */
    private String createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr_staff_leave.CREATE_DEPT_ID
     *
     * @mbggenerated
     */
    private Integer createDeptId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr_staff_leave.QUIT_TIME_PLAN
     *
     * @mbggenerated
     */
    private Date quitTimePlan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr_staff_leave.QUIT_TYPE
     *
     * @mbggenerated
     */
    private String quitType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr_staff_leave.LAST_SALARY_TIME
     *
     * @mbggenerated
     */
    private Date lastSalaryTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr_staff_leave.QUIT_TIME_FACT
     *
     * @mbggenerated
     */
    private Date quitTimeFact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr_staff_leave.LEAVE_PERSON
     *
     * @mbggenerated
     */
    private String leavePerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr_staff_leave.DESPACHO_PERSON
     *
     * @mbggenerated
     */
    private String despachoPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr_staff_leave.POSITION
     *
     * @mbggenerated
     */
    private String position;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr_staff_leave.ADD_TIME
     *
     * @mbggenerated
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr_staff_leave.LAST_UPDATE_TIME
     *
     * @mbggenerated
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr_staff_leave.ATTACHMENT_ID
     *
     * @mbggenerated
     */
    private String attachmentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr_staff_leave.ATTACHMENT_NAME
     *
     * @mbggenerated
     */
    private String attachmentName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr_staff_leave.APPLICATION_DATE
     *
     * @mbggenerated
     */
    private Date applicationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr_staff_leave.LEAVE_DEPT
     *
     * @mbggenerated
     */
    private String leaveDept;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr_staff_leave.IS_REINSTATEMENT
     *
     * @mbggenerated
     */
    private Integer isReinstatement;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr_staff_leave.SALARY
     *
     * @mbggenerated
     */
    private Integer salary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr_staff_leave.STAFF_CARD_NO
     *
     * @mbggenerated
     */
    private String staffCardNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr_staff_leave.IS_BLACKLIST
     *
     * @mbggenerated
     */
    private Boolean isBlacklist;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr_staff_leave.AUDIT_STATE
     *
     * @mbggenerated
     */
    private String auditState;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr_staff_leave.LEAVE_ID
     *
     * @return the value of hr_staff_leave.LEAVE_ID
     *
     * @mbggenerated
     */
    public Integer getLeaveId() {
        return leaveId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr_staff_leave.LEAVE_ID
     *
     * @param leaveId the value for hr_staff_leave.LEAVE_ID
     *
     * @mbggenerated
     */
    public void setLeaveId(Integer leaveId) {
        this.leaveId = leaveId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr_staff_leave.CREATE_USER_ID
     *
     * @return the value of hr_staff_leave.CREATE_USER_ID
     *
     * @mbggenerated
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr_staff_leave.CREATE_USER_ID
     *
     * @param createUserId the value for hr_staff_leave.CREATE_USER_ID
     *
     * @mbggenerated
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId == null ? null : createUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr_staff_leave.CREATE_DEPT_ID
     *
     * @return the value of hr_staff_leave.CREATE_DEPT_ID
     *
     * @mbggenerated
     */
    public Integer getCreateDeptId() {
        return createDeptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr_staff_leave.CREATE_DEPT_ID
     *
     * @param createDeptId the value for hr_staff_leave.CREATE_DEPT_ID
     *
     * @mbggenerated
     */
    public void setCreateDeptId(Integer createDeptId) {
        this.createDeptId = createDeptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr_staff_leave.QUIT_TIME_PLAN
     *
     * @return the value of hr_staff_leave.QUIT_TIME_PLAN
     *
     * @mbggenerated
     */
    public Date getQuitTimePlan() {
        return quitTimePlan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr_staff_leave.QUIT_TIME_PLAN
     *
     * @param quitTimePlan the value for hr_staff_leave.QUIT_TIME_PLAN
     *
     * @mbggenerated
     */
    public void setQuitTimePlan(Date quitTimePlan) {
        this.quitTimePlan = quitTimePlan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr_staff_leave.QUIT_TYPE
     *
     * @return the value of hr_staff_leave.QUIT_TYPE
     *
     * @mbggenerated
     */
    public String getQuitType() {
        return quitType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr_staff_leave.QUIT_TYPE
     *
     * @param quitType the value for hr_staff_leave.QUIT_TYPE
     *
     * @mbggenerated
     */
    public void setQuitType(String quitType) {
        this.quitType = quitType == null ? null : quitType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr_staff_leave.LAST_SALARY_TIME
     *
     * @return the value of hr_staff_leave.LAST_SALARY_TIME
     *
     * @mbggenerated
     */
    public Date getLastSalaryTime() {
        return lastSalaryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr_staff_leave.LAST_SALARY_TIME
     *
     * @param lastSalaryTime the value for hr_staff_leave.LAST_SALARY_TIME
     *
     * @mbggenerated
     */
    public void setLastSalaryTime(Date lastSalaryTime) {
        this.lastSalaryTime = lastSalaryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr_staff_leave.QUIT_TIME_FACT
     *
     * @return the value of hr_staff_leave.QUIT_TIME_FACT
     *
     * @mbggenerated
     */
    public Date getQuitTimeFact() {
        return quitTimeFact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr_staff_leave.QUIT_TIME_FACT
     *
     * @param quitTimeFact the value for hr_staff_leave.QUIT_TIME_FACT
     *
     * @mbggenerated
     */
    public void setQuitTimeFact(Date quitTimeFact) {
        this.quitTimeFact = quitTimeFact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr_staff_leave.LEAVE_PERSON
     *
     * @return the value of hr_staff_leave.LEAVE_PERSON
     *
     * @mbggenerated
     */
    public String getLeavePerson() {
        return leavePerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr_staff_leave.LEAVE_PERSON
     *
     * @param leavePerson the value for hr_staff_leave.LEAVE_PERSON
     *
     * @mbggenerated
     */
    public void setLeavePerson(String leavePerson) {
        this.leavePerson = leavePerson == null ? null : leavePerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr_staff_leave.DESPACHO_PERSON
     *
     * @return the value of hr_staff_leave.DESPACHO_PERSON
     *
     * @mbggenerated
     */
    public String getDespachoPerson() {
        return despachoPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr_staff_leave.DESPACHO_PERSON
     *
     * @param despachoPerson the value for hr_staff_leave.DESPACHO_PERSON
     *
     * @mbggenerated
     */
    public void setDespachoPerson(String despachoPerson) {
        this.despachoPerson = despachoPerson == null ? null : despachoPerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr_staff_leave.POSITION
     *
     * @return the value of hr_staff_leave.POSITION
     *
     * @mbggenerated
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr_staff_leave.POSITION
     *
     * @param position the value for hr_staff_leave.POSITION
     *
     * @mbggenerated
     */
    public void setPosition(String position) {
        this.position = position == null ? null : position.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr_staff_leave.ADD_TIME
     *
     * @return the value of hr_staff_leave.ADD_TIME
     *
     * @mbggenerated
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr_staff_leave.ADD_TIME
     *
     * @param addTime the value for hr_staff_leave.ADD_TIME
     *
     * @mbggenerated
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr_staff_leave.LAST_UPDATE_TIME
     *
     * @return the value of hr_staff_leave.LAST_UPDATE_TIME
     *
     * @mbggenerated
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr_staff_leave.LAST_UPDATE_TIME
     *
     * @param lastUpdateTime the value for hr_staff_leave.LAST_UPDATE_TIME
     *
     * @mbggenerated
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr_staff_leave.ATTACHMENT_ID
     *
     * @return the value of hr_staff_leave.ATTACHMENT_ID
     *
     * @mbggenerated
     */
    public String getAttachmentId() {
        return attachmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr_staff_leave.ATTACHMENT_ID
     *
     * @param attachmentId the value for hr_staff_leave.ATTACHMENT_ID
     *
     * @mbggenerated
     */
    public void setAttachmentId(String attachmentId) {
        this.attachmentId = attachmentId == null ? null : attachmentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr_staff_leave.ATTACHMENT_NAME
     *
     * @return the value of hr_staff_leave.ATTACHMENT_NAME
     *
     * @mbggenerated
     */
    public String getAttachmentName() {
        return attachmentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr_staff_leave.ATTACHMENT_NAME
     *
     * @param attachmentName the value for hr_staff_leave.ATTACHMENT_NAME
     *
     * @mbggenerated
     */
    public void setAttachmentName(String attachmentName) {
        this.attachmentName = attachmentName == null ? null : attachmentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr_staff_leave.APPLICATION_DATE
     *
     * @return the value of hr_staff_leave.APPLICATION_DATE
     *
     * @mbggenerated
     */
    public Date getApplicationDate() {
        return applicationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr_staff_leave.APPLICATION_DATE
     *
     * @param applicationDate the value for hr_staff_leave.APPLICATION_DATE
     *
     * @mbggenerated
     */
    public void setApplicationDate(Date applicationDate) {
        this.applicationDate = applicationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr_staff_leave.LEAVE_DEPT
     *
     * @return the value of hr_staff_leave.LEAVE_DEPT
     *
     * @mbggenerated
     */
    public String getLeaveDept() {
        return leaveDept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr_staff_leave.LEAVE_DEPT
     *
     * @param leaveDept the value for hr_staff_leave.LEAVE_DEPT
     *
     * @mbggenerated
     */
    public void setLeaveDept(String leaveDept) {
        this.leaveDept = leaveDept == null ? null : leaveDept.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr_staff_leave.IS_REINSTATEMENT
     *
     * @return the value of hr_staff_leave.IS_REINSTATEMENT
     *
     * @mbggenerated
     */
    public Integer getIsReinstatement() {
        return isReinstatement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr_staff_leave.IS_REINSTATEMENT
     *
     * @param isReinstatement the value for hr_staff_leave.IS_REINSTATEMENT
     *
     * @mbggenerated
     */
    public void setIsReinstatement(Integer isReinstatement) {
        this.isReinstatement = isReinstatement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr_staff_leave.SALARY
     *
     * @return the value of hr_staff_leave.SALARY
     *
     * @mbggenerated
     */
    public Integer getSalary() {
        return salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr_staff_leave.SALARY
     *
     * @param salary the value for hr_staff_leave.SALARY
     *
     * @mbggenerated
     */
    public void setSalary(Integer salary) {
        this.salary = salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr_staff_leave.STAFF_CARD_NO
     *
     * @return the value of hr_staff_leave.STAFF_CARD_NO
     *
     * @mbggenerated
     */
    public String getStaffCardNo() {
        return staffCardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr_staff_leave.STAFF_CARD_NO
     *
     * @param staffCardNo the value for hr_staff_leave.STAFF_CARD_NO
     *
     * @mbggenerated
     */
    public void setStaffCardNo(String staffCardNo) {
        this.staffCardNo = staffCardNo == null ? null : staffCardNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr_staff_leave.IS_BLACKLIST
     *
     * @return the value of hr_staff_leave.IS_BLACKLIST
     *
     * @mbggenerated
     */
    public Boolean getIsBlacklist() {
        return isBlacklist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr_staff_leave.IS_BLACKLIST
     *
     * @param isBlacklist the value for hr_staff_leave.IS_BLACKLIST
     *
     * @mbggenerated
     */
    public void setIsBlacklist(Boolean isBlacklist) {
        this.isBlacklist = isBlacklist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr_staff_leave.AUDIT_STATE
     *
     * @return the value of hr_staff_leave.AUDIT_STATE
     *
     * @mbggenerated
     */
    public String getAuditState() {
        return auditState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr_staff_leave.AUDIT_STATE
     *
     * @param auditState the value for hr_staff_leave.AUDIT_STATE
     *
     * @mbggenerated
     */
    public void setAuditState(String auditState) {
        this.auditState = auditState == null ? null : auditState.trim();
    }
}