package com.xoa.dao.rms;

import com.xoa.model.rms.RmsFile;
import com.xoa.model.rms.RmsFileExample;
import com.xoa.model.rms.RmsFileWithBLOBs;
import com.xoa.model.rms.RmsRollWithBLOBs;
import org.apache.ibatis.annotations.Param;

import java.util.Date;
import java.util.List;
import java.util.Map;

public interface RmsFileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rms_file
     *
     * @mbggenerated
     */
    int countByExample(RmsFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rms_file
     *
     * @mbggenerated
     */
    int deleteByExample(RmsFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rms_file
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer fileId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rms_file
     *
     * @mbggenerated
     */
    int insert(RmsFileWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rms_file
     *
     * @mbggenerated
     */
    int insertSelective(RmsFileWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rms_file
     *
     * @mbggenerated
     */
    List<RmsFileWithBLOBs> selectByExampleWithBLOBs(RmsFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rms_file
     *
     * @mbggenerated
     */
    List<RmsFile> selectByExample(RmsFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rms_file
     *
     * @mbggenerated
     */
    RmsFileWithBLOBs selectByPrimaryKey(Integer fileId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rms_file
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") RmsFileWithBLOBs record, @Param("example") RmsFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rms_file
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") RmsFileWithBLOBs record, @Param("example") RmsFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rms_file
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") RmsFile record, @Param("example") RmsFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rms_file
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RmsFileWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rms_file
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(RmsFileWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rms_file
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RmsFile record);


    /**
     * 作者: 张航宁
     * 日期: 2017/12/26
     * 说明: 根据条件查询查询
     */
    List<RmsFileWithBLOBs> query(Map<String, Object> map);


    /**
     * 作者: 张航宁
     * 日期: 2017/12/26
     * 说明: 销毁
     */
    void destroy(@Param(value = "fileIds") String[] fileIds, @Param(value = "delUser") String userId, @Param(value = "delTime") Date delTime);

    /**
     * 作者: 张航宁
     * 日期: 2018/1/2
     * 说明: 批量删除接口
     */
    void delete(@Param(value = "fileIds") String[] fileIds);

    /**
     * 作者: 张航宁
     * 日期: 2018/1/2
     * 说明:销毁后的还原接口
     */
    void restore(@Param(value = "fileIds") String[] fileIds);

    /**
     * 作者: 张航宁
     * 日期: 2018/1/3
     * 说明: 批量移卷接口
     */
    void updateRollBath(@Param(value = "fileIds") String[] fileIds,@Param(value = "rollId")Integer rollId);

    /**
     * 作者: 张航宁
     * 日期: 2018/1/3
     * 说明: 根据ids查询接口
     */
    List<RmsFileWithBLOBs> selectByFileIds(@Param(value = "fileIds") String[] fileIds);

    List<RmsFileWithBLOBs> leaderQuery(Map<String, Object> map);

    List<RmsFileWithBLOBs> selectByRunId(Integer runId);


    List<RmsFileWithBLOBs> queryAll(Map<String, Object> map);

    List<RmsFileWithBLOBs> selectByRollId(@Param(value = "rollId")String rollId);

    List<RmsFileWithBLOBs> selectByFileId(@Param(value = "fileId")String fileId);
}
